
CREATE VIEW [dbo].[EXPENSE_ATTACHMENTS_VIEW]
AS
SELECT CAST([HEADERREFERENCE] AS VARCHAR) AS DOCUMENTNUMBER
       , CASE
	   WHEN [NOTES] like 'ht%' THEN [NOTES]
	   ELSE [PATH]
	   END AS DOCUMENTLINK 
FROM [dbo].[D365_VendorInvoiceAttachments]
UNION ALL 
SELECT [PURCHASEORDERNUMBER] AS DOCUMENTNUMBER
      ,CAST([PATH] AS TEXT) AS DOCUMENTLINK  
FROM [dbo].[D365_POHeaderAttachments]
GO

