SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP VIEW [dbo].[GL_DATA_VIEW]
GO
CREATE VIEW [dbo].[GL_DATA_VIEW]
AS
SELECT  
       GL.[JOURNALNUMBER]
      ,GL.[VOUCHER]
	  ,GL.[ACCOUNTINGDATE]
	  ,GL.[LEDGERACCOUNT]
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 1, 3) AS YARD
	  ,YD.NAME AS YARD_NAME
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 5, 4) AS LOCATION
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 10, 4) AS LOB_ID
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 15, 4) AS FUTURE
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 20, 6) AS GL_ACCOUNT
	  ,SUBSTRING(GL.[LEDGERACCOUNT], 27, 3) AS LEGAL_ENTITY
	  ,CASE 
			WHEN [XXMKT_CUSTOM] = 'GC ? Gulf Coast' THEN 'GC - Gulf Coast' 
			WHEN [XXMKT_CUSTOM] = 'NE ? Northeast' THEN 'NE - Northeast' 
			WHEN [XXMKT_CUSTOM] = 'PB ? Permian Basin' THEN 'PB - Permian Basin' 
			WHEN [XXMKT_CUSTOM] = 'RM ? Rocky Mountain' THEN 'RM - Rocky Mountain' 
			WHEN [XXMKT_CUSTOM] = 'WC ? West Coast' THEN 'WC - West Coast' 
			ELSE [XXMKT_CUSTOM]
	   END AS MarketPlace
	  ,YD.XXLOB_CUSTOM AS LOB
	  ,RP.Level1
	  ,RP.Level2
	  ,RP.Level3
	  ,RP.Level_Of_Detail
	  ,MA.[NAME]
      ,GL.[DESCRIPTION]
      ,GL.[REPORTINGCURRENCYAMOUNT]
      ,GL.[POSTINGTYPE]
	  --, CASE
	  --		WHEN CAST(GL.[DOCUMENTNUMBER] AS VARCHAR) = '' THEN VT.[INVOICE]
	  --		ELSE GL.[DOCUMENTNUMBER]
	  -- END AS DOCUMENTNUMBER
      ,VT.[INVOICE] AS DOCUMENTNUMBER
	  --,GL.[DOCUMENTNUMBER]
      ,GL.[QUANTITY]
	  ,GL.[CUSTOMERACCOUNT]
      ,GL.[CUSTOMERNAME]
	  ,GL.[VENDORACCOUNT]
	  ,GL.[VENDORNAME]
	  ,CASE 
	   	    WHEN GL.[CUSTOMERACCOUNT] IS NULL AND GL.[VENDORACCOUNT] IS NOT NULL THEN CAST(GL.[VENDORACCOUNT] AS varchar)
			WHEN GL.[CUSTOMERACCOUNT] IS NOT NULL AND GL.[VENDORACCOUNT] IS NULL THEN GL.[CUSTOMERACCOUNT]
			ELSE CAST(GL.[VENDORACCOUNT] AS varchar)
	   END AS PARTNERACCOUNT
	   ,CASE 
	   	   	WHEN GL.[CUSTOMERACCOUNT] IS NULL AND GL.[VENDORACCOUNT] IS NOT NULL THEN GL.[VENDORNAME]
			WHEN GL.[CUSTOMERACCOUNT] IS NOT NULL AND GL.[VENDORACCOUNT] IS NULL THEN GL.[CUSTOMERNAME]
	   	    --WHEN GL.[CUSTOMERNAME] IS NULL AND GL.[VENDORNAME] IS NOT NULL THEN GL.[VENDORNAME]
			--WHEN GL.[CUSTOMERNAME] IS NOT NULL AND GL.[VENDORNAME] IS NULL THEN GL.[CUSTOMERNAME]
			ELSE GL.[VENDORNAME]
	   END AS PARTNERNAME
	   ,JV.[JOURNALBATCHNUMBER]
  FROM [dbo].[D365_General_Journal_entry] GL 
       LEFT OUTER JOIN [dbo].[D365_MainAccount] MA ON SUBSTRING(GL.[LEDGERACCOUNT], 20, 6) = MA.[MAINACCOUNTID] 
	   LEFT OUTER JOIN [dbo].[D365_Yard] YD ON SUBSTRING(GL.[LEDGERACCOUNT], 1, 3) = YD.[FunctionalLocationID]
	   LEFT OUTER JOIN [dbo].[GL_REPORTING_BUCKETS_DTL] RP ON SUBSTRING(GL.[LEDGERACCOUNT], 20, 6) = RP.GL_ACCOUNT 
	   LEFT OUTER JOIN [dbo].[D365_KES_Vend_Trans] VT ON CAST(GL.[VOUCHER] AS VARCHAR(MAX)) = CAST(VT.[VOUCHER] AS VARCHAR(MAX))
	   LEFT OUTER JOIN [dbo].[JOURNALBATCHNUM_VOUCHER] JV ON CAST(GL.[VOUCHER] AS VARCHAR(MAX)) = JV.[VOUCHER]
GO