SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP VIEW IF EXISTS  [dbo].[GL_DATA_VIEW_MDMQA]
GO
CREATE VIEW [dbo].[GL_DATA_VIEW_MDMQA]
AS
SELECT  
       GL.JOURNALNUMBER
      ,GL.VOUCHER
	  ,GL.ACCOUNTINGDATE
	  ,GL.LEDGERACCOUNT
	  ,GL.FN_LOC AS YARD
	  ,CAST(YD.NAME AS VARCHAR(80)) AS YARD_NAME
	  ,SUBSTRING(GL.LEDGERACCOUNT, 5, 4) AS LOCATION
	  ,SUBSTRING(GL.LEDGERACCOUNT, 10, 4) AS LOB_ID
	  ,SUBSTRING(GL.LEDGERACCOUNT, 15, 4) AS FUTURE
	  ,GL.GL_ACCOUNT
	  ,SUBSTRING(GL.LEDGERACCOUNT, 27, 3) AS LEGAL_ENTITY
	  ,CASE 
			WHEN [KES_Marketplace] = 'GC ? Gulf Coast' THEN 'GC - Gulf Coast' 
			WHEN [KES_Marketplace] = 'NE ? Northeast' THEN 'NE - Northeast' 
			WHEN [KES_Marketplace] = 'PB ? Permian Basin' THEN 'PB - Permian Basin' 
			WHEN [KES_Marketplace] = 'RM ? Rocky Mountain' THEN 'RM - Rocky Mountain' 
			WHEN [KES_Marketplace] = 'WC ? West Coast' THEN 'WC - West Coast' 
			ELSE [KES_Marketplace]
	   END AS MarketPlace
	  ,CAST(YD.XXLOB_CUSTOM AS VARCHAR(80)) AS LOB
	  ,RP.Level1
	  ,RP.Level2
	  ,RP.Level3
	  ,RP.Level_Of_Detail
	  ,CAST(MA.[NAME] AS VARCHAR(20)) AS NAME
      ,DESCRIPTION
      ,GL.REPORTINGCURRENCYAMOUNT
      ,GL.POSTINGTYPE
	  --, CASE
	  --		WHEN DOCUMENTNUMBER] AS VARCHAR) = '' THEN VT.[INVOICE]
	  --		ELSE GL.DOCUMENTNUMBER]
	  -- END AS DOCUMENTNUMBER
      ,VT.[INVOICE] AS DOCUMENTNUMBER
	  --,GL.DOCUMENTNUMBER]
      ,GL.QUANTITY
	  ,GL.CUSTOMERACCOUNT
      ,GL.CUSTOMERNAME
	  ,GL.VENDORACCOUNT
	  ,GL.VENDORNAME
	  ,CASE 
	   	    WHEN GL.CUSTOMERACCOUNT IS NULL AND GL.VENDORACCOUNT IS NOT NULL THEN GL.VENDORACCOUNT
			WHEN GL.CUSTOMERACCOUNT IS NOT NULL AND GL.VENDORACCOUNT IS NULL THEN GL.CUSTOMERACCOUNT
			ELSE GL.VENDORACCOUNT
	   END AS PARTNERACCOUNT
	   ,CASE 
	   	   	WHEN GL.CUSTOMERACCOUNT IS NULL AND GL.VENDORACCOUNT IS NOT NULL THEN GL.VENDORNAME
			WHEN GL.CUSTOMERACCOUNT IS NOT NULL AND GL.VENDORACCOUNT IS NULL THEN GL.CUSTOMERNAME
	   	    --WHEN GL.CUSTOMERNAME IS NULL AND GL.VENDORNAME IS NOT NULL THEN GL.VENDORNAME
			--WHEN GL.CUSTOMERNAME IS NOT NULL AND GL.VENDORNAME IS NULL THEN GL.CUSTOMERNAME
			ELSE GL.VENDORNAME
	   END AS PARTNERNAME
	   ,JV.[JOURNALBATCHNUMBER]
  FROM [dbo].[D365_General_Journal_entry] GL 
       LEFT OUTER JOIN [dbo].[D365_MainAccount] MA ON GL.GL_ACCOUNT = MA.[MAINACCOUNTID] 
	   LEFT OUTER JOIN [dbo].[D365_Yard] YD ON GL.FN_LOC = YD.[FunctionalLocationID]
	   LEFT OUTER JOIN [dbo].[GL_REPORTING_BUCKETS_DTL] RP ON GL.GL_ACCOUNT = RP.GL_ACCOUNT 
	   LEFT OUTER JOIN [dbo].[D365_KES_Vend_Trans] VT ON GL.VOUCHER = CAST(VT.[VOUCHER] AS VARCHAR(MAX))
	   LEFT OUTER JOIN [dbo].[JOURNALBATCHNUM_VOUCHER] JV ON GL.VOUCHER = JV.[VOUCHER]
GO
