/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW dbo.JOURNALBATCHNUM_VOUCHER
WITH SCHEMABINDING
AS
SELECT 
    [JOURNALBATCHNUMBER], 
    [VOUCHER]
FROM dbo.D365_VendorJournalLines
GROUP BY 
    [JOURNALBATCHNUMBER], 
    [VOUCHER]
GO

