



CREATE VIEW [dbo].[VENDOR_INVOICE_SEARCH_VIEW]
AS
SELECT JH.[JOURNALBATCHNUMBER]
      ,JH.[DESCRIPTION]
      ,JH.[ISPOSTED]
      ,JH.[JOURNALNAME]
      ,JH.[SALESTAXINCLUDED]
	  ,GDV.[PARTNERACCOUNT]
      ,GDV.[PARTNERNAME]
	  ,GDV.DOCUMENTNUMBER
	  ,GDV.ACCOUNTINGDATE
	  ,GDV.NAME
	  ,GDV.DESCRIPTION AS JOURNAL_DESCRIPTION
	  , CASE 
			WHEN VIA.TYPEID IS NULL THEN GJA.NOTES
			WHEN CAST(VIA.TYPEID AS VARCHAR) = 'AP File' THEN VIA.PATH
			ELSE VIA.[NOTES]
		END AS 'NOTES'
  FROM [dbo].[D365_VendorJournalHeader] JH
  LEFT OUTER JOIN [dbo].[D365_GeneralJournalAttachments] GJA ON JH.JOURNALBATCHNUMBER = CAST(GJA.JOURNALBATCHNUMBER AS VARCHAR)
  LEFT OUTER JOIN [GL_DATA_VIEW] GDV ON JH.JOURNALBATCHNUMBER = GDV.JOURNALBATCHNUMBER
  LEFT OUTER JOIN [dbo].[D365_VendorInvoiceAttachments] VIA ON CAST(GDV.DOCUMENTNUMBER AS VARCHAR) = CAST(VIA.[HEADERREFERENCE] AS VARCHAR)
GO

