
--DROP View [dbo].[VOUCHER_ATTACHMENTS_VIEW] 
Create View [dbo].[VOUCHER_ATTACHMENTS_VIEW] AS (
SELECT DISTINCT CAST(GJ.[VOUCHER] AS VARCHAR) AS VOUCHER
	   , CASE
	   WHEN VI.[NOTES] like 'ht%' THEN CAST(VI.[NOTES] AS VARCHAR(150))
	   WHEN VI.PATH like 'ht%' THEN CAST(VI.PATH AS VARCHAR(150))
	   WHEN GA.[NOTES] like 'ht%' THEN CAST(GA.[NOTES] AS VARCHAR(150))
	   WHEN GA.[PATH] like 'ht%' THEN CAST(GA.[PATH] AS VARCHAR(150))
	   WHEN GA.RESTRICTION like 'ht%' THEN CAST(GA.[RESTRICTION] AS VARCHAR(150))
	   END AS ATTACHMENT 
	   --, GJ.DESCRIPTION, GJ.DOCUMENTNUMBER, GJ.JOURNALCATEGORY, GJ.POSTINGTYPE, VI.HEADERREFERENCE, VI.NOTES, VI.PATH, VI.RESTRICTION, GA.NOTES, GA.PATH, GA.RESTRICTION
FROM [dbo].[D365_General_Journal_entry] GJ
LEFT OUTER JOIN [dbo].[GJ_ATTACHMENTS_VIEW] GA ON CAST(GJ.VOUCHER AS VARCHAR) = GA.VOUCHER
LEFT OUTER JOIN [dbo].[D365_VendorInvoiceAttachments] VI ON CAST(GJ.DOCUMENTNUMBER AS VARCHAR) = CAST(VI.HEADERREFERENCE AS VARCHAR)
WHERE GA.[RESTRICTION] like 'ht%' 
OR VI.NOTES like 'ht%'
OR VI.PATH like 'ht%'
OR GA.NOTES like 'ht%'
OR GA.PATH like 'ht%'
)
GO

