

CREATE VIEW [dbo].[WORK_ORDER_ASSET_VIEW]
AS

SELECT t1.[WORKORDERID]
      ,[ACTIVE]
      ,[ACTUALEND]
      ,[ACTUALSTART]
      ,[COSTTYPE]
      ,[DESCRIPTION]
      ,[EXPECTEDEND]
      ,[EXPECTEDSTART]
      ,[ISWORKORDERSCHEDULEDFORSINGLEWORKER]
      ,[NEXTWORKORDERLIFECYCLESTATEID]
      ,[ORDERBILLINGCUSTOMERACCOUNTNUMBER]
      ,[ORDERPROJECTCONTRACTID]
      ,[PARENTWORKORDERID]
      ,[RESPONSIBLEWORKERPERSONNELNUMBER]
      ,[SCHEDULEDEND]
      ,[SCHEDULEDSTART]
      ,t1.[SCHEDULEDWORKERPERSONNELNUMBER]
      ,[SERVICELEVEL]
      ,[WORKERGROUPID]
      ,[WORKORDERLIFECYCLESTATEID]
      ,[WORKORDERMAINTENANCEASSETCRITICALITYNAME]
      ,[WORKORDERMAINTENANCEASSETCRITICALITYVALUE]
      ,[WORKORDERTYPEID]
      ,t1.[ExecutionRunId] 
	  ,t2.[MA_FUNCTIONALLOCATIONID]
      ,t2.[MA_ID]
	  ,t3.asset_class
	  ,t3.status
	  ,t3.status_desc
  FROM [dbo].[D365_WorkOrders] t1,
       [dbo].[D365_WorkOrderJobs] t2,
	   [reporting].[MDM_Assets] t3
  WHERE t1.[WORKORDERID] = t2.[WORKORDERID]
  AND   cast(t2.[MA_ID] as varchar) = cast(t3.[asset_id] as varchar)
GO

