CREATE VIEW [hr_reporting].[ADP_POSITION_TENURE_DETAILED_VW] AS 

WITH __BASEDATA__ AS (
    SELECT 
        E.EIN,
        CASE WHEN ORGINALDATEOFHIRE IS NULL THEN E.HIRE_DATE ELSE ORGINALDATEOFHIRE END AS ORGINALDATEOFHIRE,
        CASE WHEN EFFECTIVEDATE IS NULL THEN E.HIRE_DATE ELSE EFFECTIVEDATE END AS EFFECTIVEDATE,
        CASE WHEN JOBTITLE IS NULL THEN E.JOB_FAMILY ELSE JOBTITLE END AS JOBTITLE,
        CASE WHEN EMPLOYEESTATUS IS NULL THEN E.STATUS ELSE EMPLOYEESTATUS END AS EMPLOYEESTATUS, -- LEAVE OF ABESENSE COUNTS TOWARDS THEIR LENGTH OF EMPLOYMENT ?
        PAYGROUP, 
        REG_TEMP,
        FULL_PART,
        CASE WHEN HOURLY_SALARY IS NULL THEN E.PAY_TYPE ELSE HOURLY_SALARY END AS HOURLY_SALARY,
        CASE WHEN WORKLOCATION IS NULL THEN E.PHYSICAL_LOCATION ELSE WORKLOCATION END AS WORKLOCATION,
        CASE WHEN MARKETPLACE IS NULL THEN E.MP_NAME ELSE MARKETPLACE END AS MARKETPLACE,
        CONCAT(LOCATIONCODE,'.', LEVEL1, '.', LEVEL2 ) AS LOCO_CODE,
        DEPT_DISTRICTID,
        REPORTSTOMANGERID,
        ROW_NUMBER() OVER (PARTITION BY EMPLOYEEID ORDER BY EFFECTIVEDATE) AS _ROWNUMBER 
    FROM DBO.EMPLOYEES E 
    LEFT JOIN (SELECT * FROM DBO.ADP_TRANSACTIONS WHERE WORKLOCATION <> 'ZTERM') A ON (E.EIN = A.EMPLOYEEID )
)

, __JOBTITLE__ AS (
    /* TRACK HOW LONG SOMEONE WORKED IN A JOBTITLE */
    SELECT 
        EIN,
        JOBTITLE, 
        MARKETPLACE,
        WORKLOCATION,
        LOCO_CODE,
        DEPT_DISTRICTID,
        REPORTSTOMANGERID,
        PAYGROUP,
        REG_TEMP,
        FULL_PART,
        HOURLY_SALARY,
        EMPLOYEESTATUS,
        CASE 
            WHEN ROW_NUMBER() OVER (PARTITION BY EIN ORDER BY EFFECTIVEDATE ASC) = 1 THEN ORGINALDATEOFHIRE --FIRST JOBTITLE
            ELSE EFFECTIVEDATE END AS STARTDATE,
        CASE 
            WHEN EMPLOYEESTATUS IN ('T','D') THEN EFFECTIVEDATE 
            WHEN LEAD(EFFECTIVEDATE) OVER (PARTITION BY EIN ORDER BY EFFECTIVEDATE) IS NULL THEN CONVERT(DATE, GETDATE()) -- PERSON STILL EMPLOYED 
            ELSE CONVERT(DATE, DATEADD(DAY, -1, LEAD(EFFECTIVEDATE) OVER (PARTITION BY EIN ORDER BY EFFECTIVEDATE))) 
            END AS ENDDATE
    FROM (
        SELECT 
            EIN,
            JOBTITLE,
            MARKETPLACE,
            WORKLOCATION,
            LOCO_CODE,
            DEPT_DISTRICTID,
            REPORTSTOMANGERID,
            PAYGROUP,
            REG_TEMP,
            FULL_PART,
            HOURLY_SALARY,
            EMPLOYEESTATUS,
            ORGINALDATEOFHIRE,
            MIN(EFFECTIVEDATE) AS EFFECTIVEDATE 
        FROM __BASEDATA__
        GROUP BY EIN, JOBTITLE, MARKETPLACE, WORKLOCATION, LOCO_CODE, DEPT_DISTRICTID, REPORTSTOMANGERID, PAYGROUP, REG_TEMP, FULL_PART, HOURLY_SALARY,EMPLOYEESTATUS, ORGINALDATEOFHIRE 
    ) J 
 
)

, __DATASET__ AS (
    SELECT 
        D.EIN,
        D.JOBTITLE, 
        D.EMPLOYEESTATUS,
        D.MARKETPLACE,
        D.WORKLOCATION,
        D.DEPT_DISTRICTID,
        D.REPORTSTOMANGERID,
        D.PAYGROUP,
        D.REG_TEMP,
        D.FULL_PART,
        D.HOURLY_SALARY,
        D.STARTDATE,
        D.ENDDATE,
        DATEDIFF(DAY, D.STARTDATE, D.ENDDATE) + 1 AS DAYS_IN_POSITION,
        H.LOCO_CODE,
        H.LOCO_NAME,
        H.LOCA_CODE,
        H.LOCA_NAME,
        H.AREA_CODE,
        H.AREA_NAME,
        H.MKTP_CODE,
        H.MKTP_NAME,
        LVL1_NAME,
        LOB_CODE,
        LOB_NAME,
        SERV_NAME,
        SEGM_NAME,
        LVL2_NAME,
        DEPT_CODE,
        DEPT_NAME,
        DIST_NAME,
        MARE_NAME,
        YARD_NAME,
        YARD_CODE
    FROM __JOBTITLE__ AS D 
    LEFT JOIN DBO.LOCO_HIERARCHY AS H ON (D.LOCO_CODE = H.LOCO_CODE)
)

SELECT * FROM __DATASET__
WHERE DAYS_IN_POSITION > 0
GO

