SELECT [ID]
      ,[RuleName]
      ,[RuleType]
      ,[DatabaseName]
      ,[SchemaName]
      ,[TableName]
      ,[ColumnName]
      ,[RuleDefinition]
      ,[ExpectedResult]
      ,[IsActive]
      ,[Severity]
  FROM [dataquality].[DQ_Rules]