SELECT TOP (1000) [AssetsHashKey]
      ,[AssetsChkSum]
      ,[LoadDate]
      ,[SourceSystem]
      ,[LastSeenDate]
      ,[ID]
      ,[Asset_Num]
      ,[Asset_Desc]
      ,[Asset_Class]
      ,[Manufacturer]
      ,[Model]
      ,[Model_Year]
      ,[Series]
      ,[Serial_Num]
      ,[Status]
      ,[Status_Desc]
      ,[Source]
      ,[Marketed]
      ,[Revenue_Track]
      ,[Parent_Asset_Num]
      ,[Child_Relationship_Type]
      ,[Loco_Code]
      ,[Loco_Name]
      ,[Loca_Code]
      ,[Loca_Name]
      ,[MKTP_Code]
      ,[MKTP_Name]
      ,[LVL1_Code]
      ,[LVL1_Name]
      ,[LOB_Code]
      ,[LOB_Name]
      ,[Dist_Code]
      ,[Dist_Name]
      ,[Mare_Code]
      ,[Mare_Name]
      ,[Yard_Code]
      ,[Yard_Name]
      ,[W_Status]
      ,[Crew_Needed]
      ,[Avail_Date]
      ,[LastWT_Date]
      ,[Mod_Date]
      ,[Mod_User]
      ,[Note]
      ,[Customer]
      ,[JobType]
      ,[Supervisor]
      ,[Operator]
      ,[Directions]
      ,[CompanyMan]
      ,[CompanyManPhone]
      ,[Daylight24HR]
      ,[Size]
      ,[UsedByRigYard]
      ,[UsedByRigNum]
      ,[Source_LastUpdateDate]
      ,[Source_LastUpdateBy]
  FROM [curated].[vw_changed_asset_recs]

SELECT Asset_Desc, LEN(Asset_Desc) Length1, COUNT(*) CNT 
FROM [curated].[vw_changed_asset_recs]
GROUP BY Asset_Desc, LEN(Asset_Desc) 
ORDER BY 2 ASC
;

