CREATE PROCEDURE [staging].[InsertMDM_Assets]
 --   @AssetNumHash NVARCHAR(32),
    @StagingLoadTimestamp DATETIME2,
    @StagingSourceSystem NVARCHAR(50),
    @RawLoadTimestamp DATETIME2,
    @EffectiveStartDate DATE,
    @EffectiveEndDate DATE,
    @CuratedLoadTimestamp DATETIME2,
    @CuratedTransformedBy NVARCHAR(200),
    @ID INT,
    @Asset_Num NVARCHAR(60),
    @Asset_Desc NVARCHAR(255),
    @Asset_Class NVARCHAR(255),
    @Manufacturer NVARCHAR(255),
    @Model NVARCHAR(255),
    @Model_Year NVARCHAR(255),
    @Series NVARCHAR(255),
    @Serial_Num NVARCHAR(255),
    @Status NVARCHAR(20),
    @Status_Desc NVARCHAR(255),
    @Source NVARCHAR(20),
    @Marketed BIT,
    @Revenue_Track BIT,
    @Parent_Asset_Num NVARCHAR(20),
    @Child_Relationship_Type NVARCHAR(80),
    @LOCO_CODE NVARCHAR(20),
    @LOCO_NAME NVARCHAR(100),
    @LOCA_CODE NVARCHAR(20),
    @LOCA_NAME NVARCHAR(100),
    @MKTP_CODE NVARCHAR(20),
    @MKTP_NAME NVARCHAR(100),
    @LVL1_CODE NVARCHAR(20),
    @LVL1_NAME NVARCHAR(100),
    @LOB_CODE NVARCHAR(20),
    @LOB_NAME NVARCHAR(100),
    @DIST_CODE NVARCHAR(20),
    @DIST_NAME NVARCHAR(100),
    @MARE_CODE NVARCHAR(20),
    @MARE_NAME NVARCHAR(100),
    @YARD_CODE NVARCHAR(20),
    @YARD_NAME NVARCHAR(100),
    @W_Status NVARCHAR(10),
    @Crew_Needed BIT,
    @Avail_Date DATE,
    @LastWT_Date DATE,
    @Mod_Date DATE,
    @Mod_User NVARCHAR(128),
    @Note NVARCHAR(512),
    @Customer NVARCHAR(100),
    @JobType NVARCHAR(50),
    @Supervisor NVARCHAR(50),
    @Operator NVARCHAR(50),
    @Directions NVARCHAR(512),
    @CompanyMan NVARCHAR(50),
    @CompanyManPhone NVARCHAR(50),
    @Daylight24HR NVARCHAR(50),
    @Size NVARCHAR(50),
    @UsedByRigYard NVARCHAR(20),
    @UsedByRigNum NVARCHAR(20),
    @Source_LastUpdateDate DATETIME2,
    @Source_LastUpdateBy NVARCHAR(128)
AS
BEGIN
    INSERT INTO [staging].[MDM_Assets] (
    --    AssetNumHash,
        StagingLoadTimestamp,
        StagingSourceSystem,
        RawLoadTimestamp,
        EffectiveStartDate,
        EffectiveEndDate,
        CuratedLoadTimestamp,
        CuratedTransformedBy,
        ID,
        Asset_Num,
        Asset_Desc,
        Asset_Class,
        Manufacturer,
        Model,
        Model_Year,
        Series,
        Serial_Num,
        Status,
        Status_Desc,
        Source,
        Marketed,
        Revenue_Track,
        Parent_Asset_Num,
        Child_Relationship_Type,
        LOCO_CODE,
        LOCO_NAME,
        LOCA_CODE,
        LOCA_NAME,
        MKTP_CODE,
        MKTP_NAME,
        LVL1_CODE,
        LVL1_NAME,
        LOB_CODE,
        LOB_NAME,
        DIST_CODE,
        DIST_NAME,
        MARE_CODE,
        MARE_NAME,
        YARD_CODE,
        YARD_NAME,
        W_Status,
        Crew_Needed,
        Avail_Date,
        LastWT_Date,
        Mod_Date,
        Mod_User,
        Note,
        Customer,
        JobType,
        Supervisor,
        Operator,
        Directions,
        CompanyMan,
        CompanyManPhone,
        Daylight24HR,
        Size,
        UsedByRigYard,
        UsedByRigNum,
        Source_LastUpdateDate,
        Source_LastUpdateBy
    ) VALUES (
     --   @AssetNumHash,
        @StagingLoadTimestamp,
        @StagingSourceSystem,
        @RawLoadTimestamp,
        @EffectiveStartDate,
        @EffectiveEndDate,
        @CuratedLoadTimestamp,
        @CuratedTransformedBy,
        @ID,
        @Asset_Num,
        @Asset_Desc,
        @Asset_Class,
        @Manufacturer,
        @Model,
        @Model_Year,
        @Series,
        @Serial_Num,
        @Status,
        @Status_Desc,
        @Source,
        @Marketed,
        @Revenue_Track,
        @Parent_Asset_Num,
        @Child_Relationship_Type,
        @LOCO_CODE,
        @LOCO_NAME,
        @LOCA_CODE,
        @LOCA_NAME,
        @MKTP_CODE,
        @MKTP_NAME,
        @LVL1_CODE,
        @LVL1_NAME,
        @LOB_CODE,
        @LOB_NAME,
        @DIST_CODE,
        @DIST_NAME,
        @MARE_CODE,
        @MARE_NAME,
        @YARD_CODE,
        @YARD_NAME,
        @W_Status,
        @Crew_Needed,
        @Avail_Date,
        @LastWT_Date,
        @Mod_Date,
        @Mod_User,
        @Note,
        @Customer,
        @JobType,
        @Supervisor,
        @Operator,
        @Directions,
        @CompanyMan,
        @CompanyManPhone,
        @Daylight24HR,
        @Size,
        @UsedByRigYard,
        @UsedByRigNum,
        @Source_LastUpdateDate,
        @Source_LastUpdateBy
    );
END;

GO

