CREATE TABLE [reporting].[IScout_159094] (
    [link]                                                                    NVARCHAR (128) NULL,
    [report]                                                                  NVARCHAR (128) NULL,
    [report_number]                                                           NVARCHAR (20)  NULL,
    [report_date]                                                             DATETIME       NULL,
    [updated]                                                                 DATETIME       NULL,
    [updated_time]                                                            NVARCHAR (20)  NULL,
    [version]                                                                 NVARCHAR (5)   NULL,
    [observer]                                                                NVARCHAR (64)  NULL,
    [observer_emp_num]                                                        NVARCHAR (64)  NULL,
    [duration]                                                                NVARCHAR (10)  NULL,
    [latitude]                                                                FLOAT (53)     NULL,
    [longitude]                                                               FLOAT (53)     NULL,
    [temperature]                                                             FLOAT (53)     NULL,
    [wind_speed]                                                              NVARCHAR (20)  NULL,
    [weather]                                                                 NVARCHAR (20)  NULL,
    [score_percent]                                                           NVARCHAR (10)  NULL,
    [general_information]                                                     NVARCHAR (64)  NULL,
    [date_time]                                                               DATETIME       NULL,
    [date_time_lat]                                                           FLOAT (53)     NULL,
    [date_time_lon]                                                           FLOAT (53)     NULL,
    [marketplace]                                                             NVARCHAR (64)  NULL,
    [lco]                                                                     NVARCHAR (64)  NULL,
    [district_manager]                                                        NVARCHAR (64)  NULL,
    [supervisor]                                                              NVARCHAR (64)  NULL,
    [inspection_type]                                                         NVARCHAR (64)  NULL,
    [tractor_truck_information]                                               NVARCHAR (64)  NULL,
    [asset_num]                                                               NVARCHAR (64)  NULL,
    [odometer_reading]                                                        NVARCHAR (64)  NULL,
    [safety_critical_items_requiring_inspection_prior_to_vehicle_use]         NVARCHAR (64)  NULL,
    [description_1]                                                           NVARCHAR (64)  NULL,
    [air_compressor]                                                          NVARCHAR (64)  NULL,
    [air_lines]                                                               NVARCHAR (64)  NULL,
    [clutch]                                                                  NVARCHAR (64)  NULL,
    [fifth_wheel]                                                             NVARCHAR (64)  NULL,
    [coupling_device]                                                         NVARCHAR (64)  NULL,
    [clearance_marker_lights]                                                 NVARCHAR (64)  NULL,
    [tire_chains]                                                             NVARCHAR (64)  NULL,
    [battery]                                                                 NVARCHAR (64)  NULL,
    [defroster]                                                               NVARCHAR (64)  NULL,
    [engine]                                                                  NVARCHAR (64)  NULL,
    [drive_line]                                                              NVARCHAR (64)  NULL,
    [front_axle]                                                              NVARCHAR (64)  NULL,
    [fuel_tank]                                                               NVARCHAR (64)  NULL,
    [heater]                                                                  NVARCHAR (64)  NULL,
    [horn]                                                                    NVARCHAR (64)  NULL,
    [lights_head_stop_tail_dash_turn_indicators]                              NVARCHAR (64)  NULL,
    [mirrors]                                                                 NVARCHAR (64)  NULL,
    [muffler]                                                                 NVARCHAR (64)  NULL,
    [oil_pressure]                                                            NVARCHAR (64)  NULL,
    [radiator]                                                                NVARCHAR (64)  NULL,
    [rear_end]                                                                NVARCHAR (64)  NULL,
    [reflectors]                                                              NVARCHAR (64)  NULL,
    [safety_equipment_fire_extinguisher_flags_flares_fuses_spare_bulbs]       NVARCHAR (64)  NULL,
    [springs]                                                                 NVARCHAR (64)  NULL,
    [starter]                                                                 NVARCHAR (64)  NULL,
    [steering]                                                                NVARCHAR (64)  NULL,
    [tachometer]                                                              NVARCHAR (64)  NULL,
    [tires]                                                                   NVARCHAR (64)  NULL,
    [transmission]                                                            NVARCHAR (64)  NULL,
    [wheels]                                                                  NVARCHAR (64)  NULL,
    [windows]                                                                 NVARCHAR (64)  NULL,
    [windshield_wipers_washer]                                                NVARCHAR (64)  NULL,
    [trailer_information]                                                     NVARCHAR (64)  NULL,
    [is_trailer_pulled]                                                       NVARCHAR (64)  NULL,
    [trailer_asset_num]                                                       NVARCHAR (64)  NULL,
    [trailer_brake_connections]                                               NVARCHAR (64)  NULL,
    [tailer_brakes]                                                           NVARCHAR (64)  NULL,
    [tailer_tires]                                                            NVARCHAR (64)  NULL,
    [tailer_wheels]                                                           NVARCHAR (64)  NULL,
    [tailer_lights_all]                                                       NVARCHAR (64)  NULL,
    [trailer_springs]                                                         NVARCHAR (64)  NULL,
    [trailer_hitch]                                                           NVARCHAR (64)  NULL,
    [tailer_landing_gear]                                                     NVARCHAR (64)  NULL,
    [step1_driver_completing_inspection]                                      NVARCHAR (64)  NULL,
    [description_2]                                                           NVARCHAR (64)  NULL,
    [yes_condition_of_vehicle_is_satisfactory_in_working_order]               NVARCHAR (64)  NULL,
    [no_condition_of_vehicle_is_not_satisfactory_all_issues_defects_noted]    NVARCHAR (64)  NULL,
    [above_issues_defects_require_correction]                                 NVARCHAR (64)  NULL,
    [reparir_cost_greater_than_50_dollars_or_repair_time_greater_than_1_hour] NVARCHAR (64)  NULL,
    [can_repairs_be_made_by_driver]                                           NVARCHAR (64)  NULL,
    [repairs_made_by_driver]                                                  NVARCHAR (MAX) NULL,
    [driver_name]                                                             NVARCHAR (128) NULL,
    [driver_signature]                                                        NVARCHAR (64)  NULL,
    [maintenance_department_requirements]                                     NVARCHAR (64)  NULL,
    [description_3]                                                           NVARCHAR (64)  NULL,
    [defects_corrected]                                                       NVARCHAR (64)  NULL,
    [deffect_correction_date]                                                 DATETIME       NULL,
    [repair_company]                                                          NVARCHAR (128) NULL,
    [third_party_mechanic_name]                                               NVARCHAR (MAX) NULL,
    [mechanic_name]                                                           NVARCHAR (64)  NULL,
    [mechanics_signature]                                                     NVARCHAR (64)  NULL,
    [oncoming_driver_signature_requirement]                                   NVARCHAR (64)  NULL,
    [driver_signature_date]                                                   DATETIME       NULL,
    [signature_driver_name]                                                   NVARCHAR (128) NULL,
    [signature]                                                               NVARCHAR (64)  NULL,
    [r01_comments]                                                            NVARCHAR (MAX) NULL,
    [r01_inserted_on]                                                         DATETIME       NULL,
    [r01_batch_id]                                                            INT            NULL,
    [r02_pre_trip]                                                            INT            NULL,
    [r02_post_trip]                                                           INT            NULL,
    [r02_satisfactory]                                                        INT            NULL,
    [r02_defective]                                                           INT            NULL,
    [r02_na]                                                                  INT            NULL,
    [r02_yes]                                                                 INT            NULL,
    [r02_no]                                                                  INT            NULL,
    [r02_kes]                                                                 INT            NULL,
    [r02_3rd_party]                                                           INT            NULL,
    [upload_date]                                                             DATETIME       NULL,
    [work_order_id]                                                           NVARCHAR (255) NULL
);
GO

