SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- DROP TABLE [reporting].[MDM_Assets]
CREATE TABLE [reporting].[MDM_Assets](
	[asset_id] [int] NOT NULL,
	[asset_num] [nvarchar](60) NOT NULL,
	[asset_desc] [nvarchar](255) NULL,
	[asset_class] [nvarchar](255) NULL,
	[manufacturer] [nvarchar](255) NULL,
	[model] [nvarchar](255) NULL,
	[model_year] [nvarchar](255) NULL,
	[series] [nvarchar](255) NULL,
	[serial_num] [nvarchar](255) NULL,
	[status] [nvarchar](20) NULL,
	[status_desc] [nvarchar](255) NULL,
	[source] [nvarchar](20) NULL,
	[marketed] [bit] NULL,
	[revenue_track] [bit] NULL,
	[parent_asset_num] [nvarchar](20) NULL,
	[child_relationship_type] [nvarchar](80) NULL,
	[loco_code] [nvarchar](20) NULL,
	[loco_name] [nvarchar](100) NULL,
	[loca_code] [nvarchar](20) NULL,
	[loca_name] [nvarchar](100) NULL,
	[mktp_code] [nvarchar](20) NULL,
	[mktp_name] [nvarchar](100) NULL,
	[lvl1_code] [nvarchar](20) NULL,
	[lvl1_name] [nvarchar](100) NULL,
	[lob_code] [nvarchar](20) NULL,
	[lob_name] [nvarchar](100) NULL,
	[dist_code] [nvarchar](20) NULL,
	[dist_name] [nvarchar](100) NULL,
	[mare_code] [nvarchar](20) NULL,
	[mare_name] [nvarchar](100) NULL,
	[yard_code] [nvarchar](20) NULL,
	[yard_name] [nvarchar](100) NULL,
	[tire_size] [nvarchar](255) NULL,
	[tire_size2] [nvarchar](255) NULL,
	[fifth_wheel] [nvarchar](255) NULL,
	[License_Plate] [nvarchar](25) NULL,
	[Number_of_Axles] [nvarchar](5) NULL,
	[Gross_Vehicle_Weight] [int] NULL,
	[dot_roadside_inspection] [bit] NULL,    
	[crosses_state_lines] [bit] NULL,
	[crosses_state_lines_with_trailer] [bit] NULL,
	[trailer_attached_dvir] [bit] NULL,
	[attached_as_trailer_dvir] [bit] NULL,
	[dot_fields_populated] [bit] NULL,
	[work_order] [nvarchar](255) NULL,
	[has_documentation] [bit] NULL,
	[upload_date] [datetime] NULL
) ON [PRIMARY]
GO
