CREATE TABLE [bronze].[freshservice_agents] (
    [agents.active]                                          BIT            NULL,
    [agents.address]                                         VARCHAR (8000) NULL,
    [agents.api_key_enabled]                                 BIT            NULL,
    [agents.auto_assign_status_changed_at]                   VARCHAR (8000) NULL,
    [agents.auto_assign_tickets]                             BIT            NULL,
    [agents.background_information]                          VARCHAR (8000) NULL,
    [agents.can_see_all_tickets_from_associated_departments] BIT            NULL,
    [agents.created_at]                                      VARCHAR (8000) NULL,
    [agents.custom_fields.employeeid]                        BIGINT         NULL,
    [agents.department_ids]                                  BIGINT         NULL,
    [agents.department_names]                                VARCHAR (8000) NULL,
    [agents.email]                                           VARCHAR (8000) NULL,
    [agents.external_id]                                     VARCHAR (8000) NULL,
    [agents.first_name]                                      VARCHAR (8000) NULL,
    [agents.has_logged_in]                                   BIT            NULL,
    [agents.id]                                              BIGINT         NULL,
    [agents.job_title]                                       VARCHAR (8000) NULL,
    [agents.language]                                        VARCHAR (8000) NULL,
    [agents.last_active_at]                                  VARCHAR (8000) NULL,
    [agents.last_login_at]                                   VARCHAR (8000) NULL,
    [agents.last_name]                                       VARCHAR (8000) NULL,
    [agents.location_id]                                     BIGINT         NULL,
    [agents.location_name]                                   VARCHAR (8000) NULL,
    [agents.mobile_phone_number]                             VARCHAR (8000) NULL,
    [agents.occasional]                                      BIT            NULL,
    [agents.reporting_manager_id]                            BIGINT         NULL,
    [agents.roles]                                           VARCHAR (8000) NULL,
    [agents.scoreboard_level_id]                             BIGINT         NULL,
    [agents.scoreboard_points]                               VARCHAR (8000) NULL,
    [agents.signature]                                       VARCHAR (8000) NULL,
    [agents.time_format]                                     VARCHAR (8000) NULL,
    [agents.time_zone]                                       VARCHAR (8000) NULL,
    [agents.updated_at]                                      VARCHAR (8000) NULL,
    [agents.vip_user]                                        BIT            NULL,
    [agents.work_phone_number]                               VARCHAR (8000) NULL,
    [agents.workspace_ids]                                   BIGINT         NULL,
    [agents.workspace_info]                                  VARCHAR (8000) NULL,
    [agents.member_of]                                       BIGINT         NULL,
    [agents.observer_of]                                     BIGINT         NULL,
    [agents.member_of_pending_approval]                      VARCHAR (8000) NULL,
    [agents.observer_of_pending_approval]                    VARCHAR (8000) NULL,
    [agents.workspace_info.workspace_id]                     BIGINT         NULL,
    [agents.workspace_info.scoreboard_level_id]              BIGINT         NULL,
    [agents.workspace_info.points]                           BIGINT         NULL,
    [agents.roles.role_id]                                   BIGINT         NULL,
    [agents.roles.assignment_scope]                          VARCHAR (8000) NULL,
    [agents.roles.groups]                                    BIGINT         NULL,
    [_ingestion_timestamp]                                   VARCHAR (8000) NULL,
    [_pipeline_run_id]                                       VARCHAR (8000) NULL,
    [_source_name]                                           VARCHAR (8000) NULL
);


GO

