CREATE TABLE [bronze].[freshservice_tickets] (
    [tickets.subject]                                VARCHAR (8000) NULL,
    [tickets.group_id]                               BIGINT         NULL,
    [tickets.department_id]                          BIGINT         NULL,
    [tickets.category]                               VARCHAR (8000) NULL,
    [tickets.sub_category]                           VARCHAR (8000) NULL,
    [tickets.item_category]                          VARCHAR (8000) NULL,
    [tickets.requester_id]                           BIGINT         NULL,
    [tickets.responder_id]                           BIGINT         NULL,
    [tickets.due_by]                                 VARCHAR (8000) NULL,
    [tickets.fr_escalated]                           BIT            NULL,
    [tickets.deleted]                                BIT            NULL,
    [tickets.spam]                                   BIT            NULL,
    [tickets.email_config_id]                        BIGINT         NULL,
    [tickets.fwd_emails]                             VARCHAR (8000) NULL,
    [tickets.reply_cc_emails]                        VARCHAR (8000) NULL,
    [tickets.cc_emails]                              VARCHAR (8000) NULL,
    [tickets.is_escalated]                           BIT            NULL,
    [tickets.fr_due_by]                              VARCHAR (8000) NULL,
    [tickets.id]                                     BIGINT         NULL,
    [tickets.priority]                               BIGINT         NULL,
    [tickets.status]                                 BIGINT         NULL,
    [tickets.source]                                 BIGINT         NULL,
    [tickets.created_at]                             VARCHAR (8000) NULL,
    [tickets.updated_at]                             VARCHAR (8000) NULL,
    [tickets.workspace_id]                           BIGINT         NULL,
    [tickets.requested_for_id]                       BIGINT         NULL,
    [tickets.to_emails]                              VARCHAR (8000) NULL,
    [tickets.type]                                   VARCHAR (8000) NULL,
    [tickets.description]                            VARCHAR (8000) NULL,
    [tickets.description_text]                       VARCHAR (8000) NULL,
    [tickets.custom_fields.major_incident_type]      VARCHAR (8000) NULL,
    [tickets.custom_fields.business_impact]          VARCHAR (8000) NULL,
    [tickets.custom_fields.impacted_locations]       VARCHAR (8000) NULL,
    [tickets.custom_fields.no_of_customers_impacted] VARCHAR (8000) NULL,
    [tickets.tasks_dependency_type]                  BIGINT         NULL,
    [_ingestion_timestamp]                           VARCHAR (8000) NULL,
    [_pipeline_run_id]                               VARCHAR (8000) NULL,
    [_source_name]                                   VARCHAR (8000) NULL
);


GO

