SELECT DISTINCT
    v.TABLE_SCHEMA AS ViewSchema,
    v.TABLE_NAME AS ViewName,
    t.TABLE_SCHEMA AS TableSchema,
    t.TABLE_NAME AS TableName
FROM 
    INFORMATION_SCHEMA.VIEWS v
JOIN 
    INFORMATION_SCHEMA.VIEW_TABLE_USAGE u
    ON v.TABLE_SCHEMA = u.VIEW_SCHEMA
    AND v.TABLE_NAME = u.VIEW_NAME
JOIN 
    INFORMATION_SCHEMA.TABLES t
    ON u.TABLE_SCHEMA = t.TABLE_SCHEMA
    AND u.TABLE_NAME = t.TABLE_NAME
LEFT JOIN 
    sys.tables st
    ON t.TABLE_NAME = st.name
LEFT JOIN 
    sys.schemas ss
    ON t.TABLE_SCHEMA = ss.name
ORDER BY 
    v.TABLE_SCHEMA, t.TABLE_SCHEMA, v.TABLE_NAME, t.TABLE_NAME;
