SELECT TOP (1000) [LogSequence]
      ,[ETL_Method_Name]
      ,[TriggerType]
      ,[PipelineName]
      ,[TriggerId]
      ,[TriggerName]
      ,[TriggerTime]
      ,[RunId]
      ,[SourceType]
      ,[SourceSchema]
      ,[SourceName]
      ,[TargetType]
      ,[TargetSchema]
      ,[TargetName]
      ,[RowsRead]
      ,[RowsWritten]
      ,[RunDuration_in_secs]
      ,[IntegrationRuntime]
      ,[Execution_Status]
      ,[RunActivity_Start_Time]
      ,[RunActivity_End_Time]
  FROM [metricsvault].[Integration_AuditLog]