CREATE VIEW [reporting].[15M_&_DAILY_RIG_INSPECTIONS] AS 
/*****************
Business Rules/ Definitions:
1.  Any day with activity between 6a-10p needs an inspection, regardless of what the activity is or the job it is on
2.  Daily Crew Members: Number of workers on a Job in a workday
3.	Days Worked: Number of days a worker worked on a rig
4.	Work Date: the date a worker performed work, this is not a datetime time stamp, just a date
NOTE: KPA FORM 287345 IS FOR HESS RIG AUDITS
*******************/
/* GET MAIN DATA TABLES */
WITH LABOR AS (
    /* GET LABOR INFORMATION FOR HESS JOBS */ 
    SELECT
        ASSET_NUMBER AS RIG, 
        WORK_DATE, 
        EMPLOYEE_ID AS EIN  -- NATIVE INT
    FROM DBO.LaborIncremental2
    WHERE CUSTOMER_ID = '000160' AND WORK_DATE >= '2023-12-22'
)

, HESS_RIGS AS (
    /* GET HESS RIGS FOR AN INNER JOIN */
    SELECT 
    FORMAT(H.RIG,'0000000') AS RIG,
    H.RIG_TYPE,
    CASE WHEN ROWNUM = 1 THEN '2024-01-01' ELSE STARTDATE END AS STARTDATE, -- HESS RIG TYPES DIDNT START TRACKING UNTIL 4-11-24, SO NEEDS TO BE BACKDATED
    CASE WHEN ENDDATE IS NULL THEN GETDATE() ELSE ENDDATE END AS ENDDATE, -- LOOKING FOR RIG CHANGE BETWEEN 24H AND DAYLIGHT
    M.YARD_CODE,
    M.YARD_NAME
    FROM (
        SELECT
            RIG, 
            Rig_Type,
            As_Of_Date AS STARTDATE,
            LEAD(1) OVER (PARTITION BY RIG, As_Of_Date ORDER BY RIG, As_Of_Date) AS ENDDATE,
            ROW_NUMBER() OVER (PARTITION BY RIG, AS_OF_DATE ORDER BY RIG, AS_OF_DATE) AS ROWNUM
        FROM REPORTING.Hess_Rig_List
    ) H 
    LEFT JOIN DBO.MDM_Assets M ON (FORMAT(H.RIG,'0000000') = M.ASSET_NUM )
)

/* GET ALL RIG ACTIVITY FOR EACH DAY */
, RIG_DAILY_WORK AS (
    SELECT DISTINCT
        FORMAT(CAST(A.Rig AS NUMERIC), '0000000') AS RIG, 
        CAST(A.ACTIVITYSTARTTIME AS DATE) AS ACTIVITY_DATE,
        MIN(A.ActivityStartTime) AS FIRST_ACTIVITY_START_TIME 
    FROM DBO.KeyView_Activities2 A
    INNER JOIN HESS_RIGS H ON (FORMAT(CAST(A.RIG AS NUMERIC), '0000000') = H.RIG)  -- ONLY KEEP HESS RIGS
    WHERE A.ACTIVITYSTARTTIME >= '2024-01-01 06:00:00' AND CAST(A.ACTIVITYSTARTTIME AS TIME) < '22:00:00'-- START ACTIVITIES IN JANUARY AND MUST BE AFTER 6AM
        AND A.ACTIVITYDESCRIPTION LIKE '%JSA%' --JSA REVIEW HAPPENS EACH WORK DAY
    GROUP BY A.RIG, CAST(A.ACTIVITYSTARTTIME AS DATE) 
)


/* COMBINE LABOR WITH HESS RIG INFORMATION */
, HESS_JOBS AS ( 
    SELECT DISTINCT 
        D.RIG,
        D.FIRST_ACTIVITY_START_TIME,
        D.ACTIVITY_DATE,
        CAST(L.EIN AS VARCHAR) AS EIN
    FROM RIG_DAILY_WORK D 
    LEFT JOIN LABOR L ON (D.RIG = L.RIG AND D.ACTIVITY_DATE = L.WORK_DATE) -- MATCH EIN TO THE CORRECT RIG BY WORK DATE
)

/* GET DAYS RIG WAS ACTIVELY WORKING */
, RIG_WORKED_DAYS AS (
    SELECT
        RIG,
        MONTH(ACTIVITY_DATE) AS ACTIVITY_MONTH,
        COUNT(DISTINCT ACTIVITY_DATE) AS RIG_WORKED_DAYS
    FROM HESS_JOBS
    GROUP BY RIG, MONTH(ACTIVITY_DATE) 
)

/* GET DAILY WORKERS BY RIG */
, DAILY_WORKERS AS (
    SELECT 
        RIG,
        ACTIVITY_DATE,
        COUNT(DISTINCT EIN) AS DAILY_WORKERS
    FROM HESS_JOBS
    GROUP BY RIG, ACTIVITY_DATE 
)

/* DETERMINE IF EACH RIG WORKED DAY HAS A 15-MIN REPORT */
, FIFTEEN_MIN_RPTS AS (
    SELECT DISTINCT 
        ASSETNUM AS RIG,
        'PIC 15 Min' as REPORT,
        FORMAT(CONVERT(DATE,DATETIME), 'MM-dd-yyyy') AS REPORT_START_DATE_15M, --REPORT START DATE, BROCK ASKED US TO USE THIS DATE FOR AUDITING
        FORMAT(CONVERT(DATE,REPORT_DATE), 'MM-dd-yyyy') as REPORT_SUBMIT_DATE_15M -- SUIBMITTED DATE

    FROM DBO.ISCOUT_160405 
    WHERE Customer LIKE '%HESS%' AND YEAR(CAST(REPORT_DATE AS DATE)) = 2024 
)

/* GET DAILY RIG REPORTS -- ALSO NOTE THIS TABLE IS NEW AND ONLY CAPTURES REPORTS FROM 6/3/24 FORWARD AS OF 6/21/24 */
, DAILY_INS AS (
    SELECT DISTINCT 
        S0_R22_assetNum AS RIG,
        'DAILY RIG INSP' AS REPORT,
        S0_R04_report_date AS REPORT_DATE,
        S5_Crew_Count AS CREW_COUNT
    FROM DBO.ISCOUT_DAILY_RIG_INSPECTION_VIEW
)


SELECT DISTINCT
    H.RIG,
    R.RIG_TYPE,
    R.YARD_CODE,
    R.YARD_NAME,
    H.FIRST_ACTIVITY_START_TIME,
    H.ACTIVITY_DATE,
    R.STARTDATE,
    R.ENDDATE,
    FORMAT(H.ACTIVITY_DATE, 'MM-yyyy') AS RIG_WORK_MONTH,
    F.REPORT_START_DATE_15M,
    F.REPORT_SUBMIT_DATE_15M,
    F.REPORT AS REPORT_15M,
    D.REPORT_DATE AS REPORT_DATE_DAILY,
    D.REPORT AS REPORT_DAILY,
    W.RIG_WORKED_DAYS,
    D.CREW_COUNT AS DAILY_RIG_REPORTED_DAILY_WORKERS,
    DW.DAILY_WORKERS AS LABOR_DAILY_WORKERS
FROM HESS_JOBS H   -- THIS IS THE DRIVING TABLE
LEFT JOIN HESS_RIGS R on (H.RIG = R.Rig AND (H.ACTIVITY_DATE >= R.STARTDATE AND H.ACTIVITY_DATE <= CAST(R.ENDDATE AS DATE)))
LEFT JOIN RIG_WORKED_DAYS W ON (H.RIG = W.RIG AND MONTH(H.ACTIVITY_DATE) = W.ACTIVITY_MONTH)  -- THIS PROVIDES THE DAYS THE RIG WAS WORKING
LEFT JOIN DAILY_WORKERS DW ON (H.RIG = DW.RIG AND H.ACTIVITY_DATE = DW.ACTIVITY_DATE)
LEFT JOIN FIFTEEN_MIN_RPTS F ON (H.RIG = F.RIG AND H.ACTIVITY_DATE = F.REPORT_START_DATE_15M)
LEFT JOIN DAILY_INS D ON (H.RIG = D.RIG AND CAST(H.ACTIVITY_DATE AS DATE) = D.REPORT_DATE)
WHERE H.EIN IS NOT NULL

;
GO

