CREATE VIEW [reporting].[FINANCE_SFDC_LAST_TICKET_DATE_VW] AS 

WITH TICKETS AS (
    SELECT 
        Asset_Number__c AS ASSET_NUMBER,
        Customer__c AS CUSTOMER,
        Ticket_End_Date__c AS TICKET_END_DT,
        Ticket_Number__c AS TICKET_NUMBER,
        Ticket_Total__c AS TICKET_TOTAL
    FROM DBO.SALESFORCE_TICKETS
) 

, MAX_TICKET_DATE AS (
    SELECT 
        ASSET_NUMBER,
        MAX(TICKET_END_DT) AS LAST_TICKET_DT
    FROM TICKETS 
    GROUP BY ASSET_NUMBER 
)
, ASSETS AS (
    SELECT 
        ASSET_NUM,
        LOCO_CODE,
        LOCO_NAME,
        MKTP_NAME,
        YARD_NAME
    FROM DBO.MDM_ASSETS 
)

, FINAL_TICKET AS (
    SELECT 
        T.ASSET_NUMBER,
        CUSTOMER,
        LAST_TICKET_DT,
        TICKET_NUMBER,
        TICKET_TOTAL
    FROM TICKETS T 
    INNER JOIN MAX_TICKET_DATE D ON (T.ASSET_NUMBER = D.ASSET_NUMBER AND T.TICKET_END_DT = D.LAST_TICKET_DT)
) 

SELECT
    T.*,
    A.LOCO_CODE,
    A.LOCO_NAME,
    A.MKTP_NAME,
    A.YARD_NAME
FROM FINAL_TICKET T 
LEFT JOIN ASSETS A ON (T.ASSET_NUMBER = A.ASSET_NUM)
;
GO

