CREATE VIEW [reporting].[HESS_ALL_ACTIVITIES_VW] AS 


WITH ALLACT AS (SELECT * FROM REPORTING.HESS_JOB_ACTIVITIES_EXCEPTIONS_VW)

, SUM_EXCEPTIONS AS (
    /* SUM EXCEPTIONS BY ACTIVITY NUMBER */
    SELECT 
        ACTIVITY_NUMBER,
        EXCEPTION_TYPE,
        COUNT(EXCEPTION_NUMBER) AS EXCEPTIONS_CNT,
        SUM(EXCEPT_DURATION_MIN) AS EXCEPT_DURATION_MIN
    FROM ALLACT 
    WHERE EXCEPTION_TYPE = 'Exception: wait'
    GROUP BY ACTIVITY_NUMBER , EXCEPTION_TYPE

)

, ALL_ACTIVITES AS (
    /* BUILD THE FINAL TABLE TO ALL ACTIVITES IN NPT REPORT */
    SELECT 
        A.JOBNUMBER,
        RIG,
        RIGTYPE,
        RIGSUBTYPE,
        WELL_NAME,
        WORKINGDEPTH,
        WELLBORECONFIG,
        WORKTYPE,
        JOBTYPE,
        JOBSTARTTIME,
        JOBENDTIME,
        RUSU,
        RDSU,
        RIG_UP,
        A.ACTIVITY_NUMBER,
        ACTIVITYSTARTTIME,
        ACTIVITYENDTIME, 
        ACTIVITYDESCRIPTION_ORIGINAL,
        ACTIVITYDESCRIPTION,
        ACTIVITY_ABBR,
        ACTIVITY_ERROR,
        DURATIONMINUTES AS ACTIVITY_DURATION,
        E.EXCEPT_DURATION_MIN,
        CASE WHEN E.EXCEPT_DURATION_MIN IS NULL THEN 0 ELSE E.EXCEPT_DURATION_MIN END AS WAIT_MIN,
        CASE WHEN E.EXCEPTIONS_CNT IS NULL THEN 0 ELSE E.EXCEPTIONS_CNT END AS EXCEPTIONS_CNT,
        CASE 
            WHEN E.EXCEPT_DURATION_MIN IS NULL THEN DURATIONMINUTES 
            ELSE DURATIONMINUTES - E.EXCEPT_DURATION_MIN END AS DURATION_WO_DELAY_MIN,
        CASE WHEN E.EXCEPT_DURATION_MIN IS NULL THEN 0 ELSE E.EXCEPT_DURATION_MIN/60 END AS WAIT_HR,
        CASE 
            WHEN E.EXCEPT_DURATION_MIN IS NULL THEN DURATIONMINUTES/60 
            ELSE (DURATIONMINUTES - E.EXCEPT_DURATION_MIN) / 60 END AS DURATION_WO_DELAY_HR,
        E.EXCEPTION_TYPE,
        JOBENDMONTH,
        JOBENDMONTHORDER,
        ACTIVITYENDDATE,
        ACTIVITYENDMONTH,
        ACTIVITYENDMONTHORDER 
    FROM ALLACT A 
    LEFT JOIN SUM_EXCEPTIONS E ON (A.ACTIVITY_NUMBER = E.ACTIVITY_NUMBER)
    WHERE EXCEPT_CNT = 1 -- THIS REMOVES ANY DUPLICATE ACTIVITY NUMBERS
)

SELECT * FROM ALL_ACTIVITES 

;
GO

