CREATE VIEW [reporting].[HESS_JOB_ACTIVITIES_EXCEPT_SUMMARIES_VW] AS 

WITH ACTIVITIES AS (
    SELECT * FROM REPORTING.HESS_JOB_ACTIVITIES_VW
)

, NPT_EXCEPTIONS AS (
    /* NOTE: SUM ONLY RIG>UNSCHEDULED EXCEPTIONS ASSOCIATED WITH THE HESS ACTIVITIES ABOVE */
    SELECT 
        E.ACTIVITY_NUMBER,
        COUNT(EXCEPTION_NUMBER) AS RIG_UNSCHED_EXCEPT_COUNT,
        SUM(DURATION) AS RIG_UNSCHED_DURATION_MIN,
        SUM(DURATION) / 60 AS RIG_UNSCHED_DURATION_HR
    FROM DBO.KEYVIEW_JOB_ACTIVITY_EXCEPTION E 
    INNER JOIN ACTIVITIES A ON (E.ACTIVITY_NUMBER = A.ACTIVITY_NUMBER)
    WHERE UPPER(VARIANCE_DESC_01) = 'RIG' AND UPPER(VARIANCE_DESC_04) = 'UNSCHEDULED' 
    GROUP BY E.ACTIVITY_NUMBER
)

, EXCEPTION_WAIT AS (
    /* NOTE: SUM ALL EXCEPTIONS (WAIT TIME) ASSOCIATED WITH THE HESS ACTIVITIES ABOVE */
    SELECT 
        E.ACTIVITY_NUMBER,
        COUNT(EXCEPTION_NUMBER) AS TOT_EXCEPTION_COUNT,
        SUM(DURATION) AS TOT_EXCEPTION_DURATION_MIN,
        SUM(DURATION) / 60 AS TOT_EXCEPTION_DURARTION_HR
    FROM DBO.KEYVIEW_JOB_ACTIVITY_EXCEPTION E 
    INNER JOIN ACTIVITIES A ON (E.ACTIVITY_NUMBER = A.ACTIVITY_NUMBER)
    GROUP BY E.ACTIVITY_NUMBER
)

, DATASET AS (
    /* COMPOSE FINAL DATASET */
    /* NOTE: EXCEPTION_DURATIONMINUTES COMES FROM THE KEYVIEW ACTIVITIES2 TABLE AND NOT THE ACTUAL EXCEPTIONS TABLE */
    SELECT 
        A.*,
        W.TOT_EXCEPTION_COUNT,
        W.TOT_EXCEPTION_DURATION_MIN,
        W.TOT_EXCEPTION_DURARTION_HR,
        N.RIG_UNSCHED_EXCEPT_COUNT,
        N.RIG_UNSCHED_DURATION_MIN,
        N.RIG_UNSCHED_DURATION_HR
    FROM ACTIVITIES A 
    LEFT JOIN EXCEPTION_WAIT W ON (A.ACTIVITY_NUMBER = W.ACTIVITY_NUMBER)
    LEFT JOIN NPT_EXCEPTIONS N ON (A.ACTIVITY_NUMBER = N.ACTIVITY_NUMBER)
)

SELECT 
    *
FROM DATASET   

;
GO

