CREATE VIEW [reporting].[HESS_CREW_TURNOVER_VW] AS 

/* CREATE A VIEW THAT CALCULATES HESS MONTHLY CREW TURNOVER FOR THE EXECUTIVE SUMMARY DASHBOARD */

WITH LABOR AS (
    SELECT 
        EIN,
        WORKMONTH,
        FORMAT(CONVERT(DATE, TERM_DATE), 'MM-yyyy') AS TERM_MONTH
    FROM REPORTING.HESS_KPI_SAFETY_BONUS_EMPLOYEE_VW
    WHERE DATEDIFF(M,DATEFROMPARTS(RIGHT(WORKMONTH,4),LEFT(WORKMONTH,2),'01'), GETDATE()) < 13 

)

, CREW AS (
    SELECT 
        WORKMONTH,
        COUNT(DISTINCT EIN) AS CREW_COUNT
    FROM LABOR
    GROUP BY WORKMONTH
)

, TURNOVER AS (
    SELECT 
        TERM_MONTH,
        COUNT(DISTINCT EIN) AS TURNOVER_COUNT
    FROM LABOR 
    WHERE TERM_MONTH IS NOT NULL  
    GROUP BY TERM_MONTH
)

SELECT 
    WORKMONTH,
    RIGHT(WORKMONTH, 4) AS WORKYEAR,
    CASE 
        WHEN DATEFROMPARTS(RIGHT(WORKMONTH,4),LEFT(WORKMONTH,2),'01') <= '2024-04-01' THEN .05 ELSE .03 END AS TURNOVER_THRESHOLD,
    CREW_COUNT,
    CASE WHEN TURNOVER_COUNT IS NULL THEN 0 ELSE TURNOVER_COUNT END AS TURNOVER_COUNT,
    CASE WHEN TURNOVER_COUNT IS NULL THEN 0 ELSE CONVERT(FLOAT,TURNOVER_COUNT) / CONVERT(FLOAT,CREW_COUNT) END AS CREW_TURNOVER
FROM CREW C 
LEFT JOIN TURNOVER T ON (C.WORKMONTH = T.TERM_MONTH)
;
GO

