CREATE VIEW [reporting].[HESS_JOBSTART_TO_RIGUP_VW] AS 

/* CALCULATE THE JOBSTARTTIME TO THE FIRST RIG UP SERVICE UNIT FOR EACH JOB AS A NEW HESS METRIC */

WITH ACTIVITIES AS (
    /* GET ALL HESS ACTIVITIES STARTING AT THE BEGINNING OF 2024 */
    SELECT 
        FORMAT(CONVERT(INT,RIG), '0000000') AS RIG ,
        JOBNUMBER,
        WELL_NAME,
        WELLBORECONFIG,
        WORKTYPE,
        JOBTYPE,
        WORKINGDEPTH,
        JOBSTARTTIME,
        JOBENDTIME,
        FORMAT(JOBENDTIME, 'MM-yyyy') AS JOBENDMONTH,
        CUSTOMERORGUNIT,
        YARD,
        ROW_NUMBER() OVER (PARTITION BY JOBNUMBER ORDER BY ACTIVITYSTARTTIME ASC) AS RUSU_CNT,
        MIN(ACTIVITYSTARTTIME) OVER (PARTITION BY JOBNUMBER ORDER BY ACTIVITYSTARTTIME ASC) AS RUSU
    FROM DBO.KEYVIEW_ACTIVITIES2 
    WHERE Activity_Description = 'RUSU' AND CUSTOMERORGUNIT LIKE '%Hess%' AND JOBSTARTTIME >= '2024-01-01'
)

, RUSU_COUNT AS (
    /* COUNT EXTRACT HOW MANY TIMES A JOB RIGGED UP */
    SELECT 
        JOBNUMBER,
        MAX(RUSU_CNT) AS RUSU_COUNT
    FROM ACTIVITIES
    GROUP BY JOBNUMBER 
)

, HESS_RIGS AS (
    /* GET HESS RIG TYPES BY DAY */
    SELECT * FROM REPORTING.HESS_RIG_LIST_HIST 
)

, JOB_PREP_TIME AS (
    SELECT 
        A.JOBNUMBER,
        (DATEDIFF(MS, A.JOBSTARTTIME, A.RUSU) / 1000.0) / 60.0 AS PREP_MINUTES,
        ((DATEDIFF(MS, A.JOBSTARTTIME, A.RUSU) / 1000.0) / 60.0) / 60.0 AS PREP_HOURS
    FROM ACTIVITIES A 
)

, DATASET AS (
    SELECT DISTINCT 
        A.RIG,
        H.RIGTYPE,
        H.RIGSUBTYPE,
        A.JOBNUMBER,
        A.WELL_NAME,
        A.WELLBORECONFIG,
        A.WORKTYPE,
        A.JOBTYPE,
        A.WORKINGDEPTH,
        A.JOBSTARTTIME,
        A.JOBENDTIME,
        A.RUSU,
        SUBSTRING(A.YARD, CHARINDEX('-', A.YARD) + 1, LEN(A.YARD)) AS YARD, 
        T.PREP_MINUTES,
        T.PREP_HOURS,
        C.RUSU_COUNT,
        A.JOBENDMONTH,
        (YEAR(JOBENDTIME)*100 ) + MONTH(JOBENDTIME) AS JOBENDMONTHORDER
    FROM ACTIVITIES A 
    LEFT JOIN HESS_RIGS H ON (A.RIG = H.RIG AND CONVERT(DATE,A.JOBENDTIME) = H.OPDATE)
    LEFT JOIN RUSU_COUNT C ON (A.JOBNUMBER = C.JOBNUMBER)
    LEFT JOIN JOB_PREP_TIME T ON (A.JOBNUMBER = T.JOBNUMBER)
    WHERE A.RUSU_CNT = 1 
)

SELECT 
    *
FROM DATASET;
GO

