CREATE VIEW [reporting].[HESS_RIG_WORKED_MOST_VW] AS 

/* ------------------ BEGIN CODE BLOCK  ------------------ */

WITH __LABOR__ AS (
    /* GRAB THE EINS FROM THE LABOR TABLE */
    SELECT DISTINCT 
        L.ASSET_NUMBER AS RIG,
        FORMAT(L.WORK_DATE, 'MM-yyyy') AS WORK_MONTH,
        L.EMPLOYEE_ID AS EIN,
        SUM(L.DURATION  ) AS DURATION
    FROM DBO.LABORINCREMENTAL2 L
    WHERE CUSTOMER_ID = '000160' AND WORK_DATE > '2022-12-01' AND ASSET_NUMBER NOT LIKE 'L%'
    GROUP BY ASSET_NUMBER, FORMAT(L.WORK_DATE, 'MM-yyyy'), EMPLOYEE_ID 
)

, __RIG_WORKED_MOST__ AS (
    SELECT 
        *, 
        ROW_NUMBER() OVER (PARTITION BY WORK_MONTH, EIN ORDER BY DURATION DESC ) AS [MULTI_RIG_VALIDATION]
    FROM (
        SELECT 
            WORK_MONTH,
            EIN,
            RIG,
            DURATION,
            RANK() OVER (PARTITION BY WORK_MONTH, EIN ORDER BY DURATION DESC ) AS [TOP_RIG]     
        FROM __LABOR__ 
    ) D 
    WHERE TOP_RIG = 1 
)


SELECT 
    EIN,
    WORK_MONTH,
    RIG,
    DURATION,
    MULTI_RIG_VALIDATION,
    CASE 
        WHEN MAX(MULTI_RIG_VALIDATION) OVER (PARTITION BY EIN, WORK_MONTH) > 1 THEN 'TIED MAX RIG DURATION' ELSE '' END AS MULTI_RIG_FLAG
FROM __RIG_WORKED_MOST__

;
GO

