CREATE VIEW [reporting].[HESS_KPA_INSPECTIONS_CREW] AS


/* NOTE GRAB ALL HESS RIGS/ ACTIVITIES */
WITH HESS_ACTIVITIES AS (
    /* GATHER ALL ACTIVITY FOR HESS RIGS, MAKE SURE TO BACK OFF 1 SECOND FOR ANY ACTIVITIES ENDING AT MIDNIGHT TO KEEP THEM IN THE CORRECT DAY */
    SELECT 
        FORMAT(CONVERT(INT, RIG), '0000000') AS RIG,
        JOBNUMBER,
        ACTIVITY_NUMBER,
        CASE WHEN CONVERT(TIME,ACTIVITYENDTIME) = '00:00:00.000' THEN CONVERT(DATE,DATEADD(S,-1,ACTIVITYENDTIME)) ELSE CONVERT(DATE,ACTIVITYENDTIME) END AS ACTIVITYDATE,
        CASE WHEN CONVERT(TIME,ACTIVITYENDTIME) = '00:00:00.000' THEN EOMONTH(DATEADD(S,-1,ACTIVITYENDTIME)) ELSE EOMONTH(ACTIVITYENDTIME) END AS ACTIVITYMONTH,
        ACTIVITY_DESCRIPTION AS ACTIVITYABBREV,
        ACTIVITYDESCRIPTION AS ACTIVITYDESC,
        DURATIONMINUTES
    FROM DBO.KEYVIEW_ACTIVITIES2 A 
    WHERE CUSTOMERORGUNIT LIKE '%Hess%' AND ACTIVITYENDTIME IS NOT NULL --NULL ENDTIME MEANS IT IS AN OPEN ACTIIVTY SO IT SHOULD NOT BE INCLUDED IN THE REPORT
)

, HESS_RIGS_TYPE AS (
    SELECT 
        * 
    FROM REPORTING.HESS_RIG_LIST_HIST
)

, HESS_RIGS AS (
    /* JUST GET A DISTINCT LIST OF HESS RIGS */
    SELECT DISTINCT RIG FROM HESS_RIGS_TYPE
)


, RIG_DETAIL AS (
    SELECT 
        ASSET_NUM AS RIG,
        LOCO_CODE,
        LOCO_NAME,
        MKTP_CODE,
        MKTP_NAME,
        YARD_CODE,
        YARD_NAME 
    FROM DBO.MDM_ASSETS A 
    INNER JOIN HESS_RIGS R ON (A.ASSET_NUM = R.RIG) 
)

, DAILY_JOB AS (
    /* CALCULATE THE DAILY SUMARIES OF ACTIVITIES AND DURATION BY RIG/ JOB */
    SELECT 
        RIG,
        JOBNUMBER,
        ACTIVITYMONTH,
        ACTIVITYDATE,
        COUNT(DISTINCT ACTIVITY_NUMBER) AS DAILY_ACTIVITIES,
        SUM(DURATIONMINUTES)/60 AS DAILY_DURATION_HR
    FROM HESS_ACTIVITIES
    GROUP BY RIG, JOBNUMBER, ACTIVITYMONTH, ACTIVITYDATE
)

, DAILY_RIG AS (
    SELECT 
        RIG,
        ACTIVITYMONTH,
        ACTIVITYDATE,
        COUNT(DISTINCT ACTIVITY_NUMBER) AS DAILY_ACTIVITIES,
        SUM(DURATIONMINUTES)/60 AS DAILY_DURATION_HR
    FROM HESS_ACTIVITIES
    GROUP BY RIG, ACTIVITYMONTH, ACTIVITYDATE
)

, CREW AS (
    /* GET CREW INFORMATION BY DATE RIG JOB */
    SELECT 
        ASSET_NUMBER,
        WORK_DATE,
        EMPLOYEE_ID AS EIN,
        SUM(DURATION) AS WORKER_DURATION_HR
    FROM DBO.LABORINCREMENTAL2 L  
    INNER JOIN HESS_RIGS H ON (H.RIG = L.ASSET_NUMBER)
    GROUP BY ASSET_NUMBER, WORK_DATE, EMPLOYEE_ID
)

, DAILY_CREW AS (
    SELECT 
        ASSET_NUMBER,
        WORK_DATE,
        COUNT(DISTINCT EIN) AS DAILY_CREW_COUNT,
        SUM(WORKER_DURATION_HR) AS DAILY_CREW_DURATION
    FROM CREW
    GROUP BY ASSET_NUMBER, WORK_DATE
)

, WORKER AS (
    SELECT 
        EIN,
        FIRST_NAME,
        LAST_NAME,
        JOB_CODE,
        JOB_FAMILY,
        HIRE_DATE,
        TERM_DATE
    FROM DBO.EMPLOYEES 
)

, RIG_CREW AS (
    /* COMBINE THE RIG AND CREW INFORMATION */
    SELECT 
        H.RIG,
        H.RIGTYPE,
        R.ACTIVITYDATE AS WORK_DATE,
        FORMAT(EOMONTH(H.OPDATE), 'MM-yyyy') AS WORK_MONTH,
        R.DAILY_ACTIVITIES,
        R.DAILY_DURATION_HR,
        D.DAILY_CREW_COUNT,
        D.DAILY_CREW_DURATION,
        C.EIN,
        C.WORKER_DURATION_HR,
        W.FIRST_NAME,
        W.LAST_NAME,
        W.JOB_CODE,
        W.JOB_FAMILY,
        W.HIRE_DATE,
        W.TERM_DATE
    FROM HESS_RIGS_TYPE H 
    LEFT JOIN DAILY_RIG R ON (H.RIG = R.RIG AND H.OPDATE = R.ACTIVITYDATE)
    LEFT JOIN DAILY_CREW D ON (R.RIG = D.ASSET_NUMBER AND R.ACTIVITYDATE = D.WORK_DATE)
    LEFT JOIN CREW C ON (R.RIG = C.ASSET_NUMBER AND R.ACTIVITYDATE = C.WORK_DATE) 
    LEFT JOIN WORKER W ON (C.EIN = W.EIN)
)
SELECT * FROM RIG_CREW
WHERE WORK_MONTH > '05-2024'

;
GO

