CREATE VIEW [REPORTING].[HESS_RIG_ACTIVITY] AS 
SELECT 
   A.*, H.Rig_Type
FROM DBO.KeyView_Activities2 A 
LEFT JOIN REPORTING.Hess_Rig_List H ON (A.RIG = H.RIG AND A.JOBSTARTTIME >= H.AS_OF_DATE)
WHERE CustomerOrgUnit LIKE '%Hess%' AND JOBSTARTTIME >= '2023-12-23'
;
GO

