CREATE VIEW [reporting].[HESS_MONTHLY_EHS_VW] AS 

/* CREATE A VIEW THAT CAPTURES THE MONTH EHS EXCEPTIONS FROM THE [reporting].[HESS_JOB_ACTIVITIES_EXCEPTIONS_VW] VIEW  */
/* TO CREATE A SIMPLE BAR CHART FOR THE SUMMARY DASHBOARD */
WITH RIGLIST AS (
SELECT DISTINCT 
    RIGTYPE,
    FORMAT(OPDATE, 'MM-yyyy') AS EXCEPT_MONTH,
    (YEAR(OPDATE)*100) + MONTH(OPDATE) AS MONTH_ORDER
FROM REPORTING.HESS_RIG_LIST_HIST
)     

, EHS AS (
    SELECT 
        RIGTYPE,
        FORMAT(EXCEPT_START_TIME,'MM-yyyy') as EXCEPT_MONTH,
        COUNT(EXCEPTION_NUMBER) as EHS_COUNT
    FROM REPORTING.HESS_JOB_ACTIVITIES_EXCEPTIONS_VW
    WHERE EXCEPTION_TYPE LIKE '%wait' AND WAIT_CATEGORY = 'Safety' AND WAIT_REASON = 'Safety Incident'
    GROUP BY RIGTYPE,FORMAT(EXCEPT_START_TIME,'MM-yyyy')
)

SELECT 
    R.RIGTYPE,
    R.EXCEPT_MONTH,
    R.MONTH_ORDER,
    CASE WHEN E.EHS_COUNT IS NULL THEN 0 ELSE E.EHS_COUNT END AS EHS_COUNT
FROM RIGLIST R
LEFT JOIN EHS E ON (R.RIGTYPE = E.RIGTYPE AND R.EXCEPT_MONTH = E.EXCEPT_MONTH)
;
GO

