CREATE VIEW [reporting].[HESS_WORKER_VW] AS

WITH EMPLOYEE AS (
    SELECT DISTINCT 
        L.EMPLOYEE_ID,
        L.JOB_CODE,
        E.JOB_FAMILY AS 'JOB/POSITION',
        E.LCO_CODE AS EMPLOYEE_LCO,
        E.LCO_NAME AS EMPLOYEE_LOCO_NAME,
        CONVERT(DATE,L.WORK_DATE) AS WORK_DATE,
        FORMAT(L.DURATION, '0.00') AS HOURS,
        L.ASSET_NUMBER,
        A.LOCO_CODE AS ASSET_LOC,
        L.CUSTOMER_ID,
        'HESS CORP' AS CUSTOMER_INFO,
        FORMAT(CONVERT(DATE,E.HIRE_DATE), 'MM/dd/yyyy') AS 'DATE OF LAST HIRE'
    FROM DBO.LaborIncremental2 L
    LEFT JOIN DBO.MDM_ASSETS A  ON (L.ASSET_NUMBER = A.ASSET_NUM )
    LEFT JOIN DBO.EMPLOYEES E ON (L.EMPLOYEE_ID = E.EIN)
    WHERE L.CUSTOMER_ID = '000160'  
)
 

SELECT * FROM EMPLOYEE
;
GO

