-- Total   = 355,094
-- Dups    =  78,164
-- Singles = 276,930
SELECT [JobID]
      ,[DateOpened]
      ,[DateCreated]
      ,[JobStatus]
      ,[PositionTitle]
      ,[JobCategory]
      ,[Location]
      ,[HiringManager]
      ,[Recruiter]
      ,[Marketplace]
      ,[ManagementDistrict]
      ,[CostLocation]
      ,[LOB]
      ,[ReasonForJob]
      ,[PersonID]
      ,[CandidateName]
      ,[City]
      ,[Abbreviation]
      ,[Ethnicity]
      ,[Gender]
      ,[DL]
      ,[Experience]
      ,[EducationType]
      ,[VeteranStatus_Description]
      ,[AverageIndustryExperienceYears]
      ,[Employer]
      ,[PrevPositionTitle]
      ,[ReferredBy]
      ,[ReferralBonus]
      ,[Source]
      ,[SubmittalDate]
      ,[ActivityStatus]
      ,[DispositionCode]
 --     ,[ActivityDate]
      ,[FunnelStatus]
      ,[CandidateType]
      ,[OfferAcceptDate]
      ,[StartDate]
      ,[Employer_Resized]
      ,[PrevPositionTitle_Resized]
      ,COUNT(*) CNT 
  FROM [dbo].[GR8P_CandidateJobTracking]
  GROUP BY [JobID]
      ,[DateOpened]
      ,[DateCreated]
      ,[JobStatus]
      ,[PositionTitle]
      ,[JobCategory]
      ,[Location]
      ,[HiringManager]
      ,[Recruiter]
      ,[Marketplace]
      ,[ManagementDistrict]
      ,[CostLocation]
      ,[LOB]
      ,[ReasonForJob]
      ,[PersonID]
      ,[CandidateName]
      ,[City]
      ,[Abbreviation]
      ,[Ethnicity]
      ,[Gender]
      ,[DL]
      ,[Experience]
      ,[EducationType]
      ,[VeteranStatus_Description]
      ,[AverageIndustryExperienceYears]
      ,[Employer]
      ,[PrevPositionTitle]
      ,[ReferredBy]
      ,[ReferralBonus]
      ,[Source]
      ,[SubmittalDate]
      ,[ActivityStatus]
      ,[DispositionCode]
 --     ,[ActivityDate]
      ,[FunnelStatus]
      ,[CandidateType]
      ,[OfferAcceptDate]
      ,[StartDate]
      ,[Employer_Resized]
      ,[PrevPositionTitle_Resized]
HAVING COUNT(*) = 1
