CREATE TABLE [curated].[GR8P_EIN_LOOKUP] (
    [HashKey]        NVARCHAR (32) NOT NULL,
    [ChkSum]         NVARCHAR (32) NOT NULL,
    [LoadDate]       DATETIME2 (7) NOT NULL,
    [SourceSystem]   NVARCHAR (50) NOT NULL,
    [REMOTE_EXEC_ID] NVARCHAR (64) NULL,
    [COMPLETED]      NVARCHAR (1)  NULL,
    [PERSONID]       NVARCHAR (9)  NULL,
    [REQUISITIONID]  NVARCHAR (20) NULL,
    [LASTNAME]       NVARCHAR (30) NULL,
    [FIRSTNAME]      NVARCHAR (30) NULL,
    [MIDDLENAME]     NVARCHAR (20) NULL,
    [PRIMARYPHONE]   NVARCHAR (20) NULL,
    [PRIMARYEMAIL]   NVARCHAR (50) NULL,
    [STARTDATE]      NVARCHAR (20) NULL,
    [JOBCODE]        NVARCHAR (20) NULL,
    [SSN]            NVARCHAR (64) NULL,
    [EIN]            NVARCHAR (9)  NULL,
    [RETURNMSG]      NVARCHAR (40) NULL,
    [INSERTED_ON]    DATETIME2 (0) NULL
);


GO

