CREATE TABLE [hr_reporting].[2022_Current_with_EIN] (
    [Location_Code]                                       SMALLINT       NULL,
    [LVL1_Line_of_Business]                               SMALLINT       NULL,
    [LVL2_Department]                                     VARCHAR (4)    NULL,
    [MarketPlace]                                         NVARCHAR (50)  NULL,
    [Employee_Status]                                     NVARCHAR (50)  NULL,
    [Reg_Temp]                                            NVARCHAR (50)  NULL,
    [Full_Part]                                           NVARCHAR (50)  NULL,
    [Action]                                              NVARCHAR (50)  NULL,
    [Reason_Code]                                         NVARCHAR (50)  NULL,
    [Reason_Description]                                  NVARCHAR (50)  NULL,
    [Vol_Inv_Term]                                        NVARCHAR (50)  NULL,
    [Employee_ID]                                         INT            NULL,
    [GR8People_ID]                                        VARCHAR (6)    NULL,
    [Experienced_Y_N]                                     VARCHAR (20)   NULL,
    [Previous_Employer]                                   NVARCHAR (50)  NULL,
    [Previous_Job]                                        NVARCHAR (100) NULL,
    [Job_Code]                                            NVARCHAR (50)  NULL,
    [Job_Title]                                           NVARCHAR (50)  NULL,
    [Grouping]                                            NVARCHAR (50)  NULL,
    [Effective_Date]                                      DATE           NULL,
    [Year]                                                SMALLINT       NULL,
    [Eligible_for_OT_Y_N]                                 BIT            NULL,
    [Department_ID]                                       SMALLINT       NULL,
    [State_Location_Info]                                 NVARCHAR (50)  NULL,
    [Manager_ID]                                          INT            NULL,
    [Last_Hired_Date]                                     DATE           NULL,
    [Original_Hire_Date]                                  DATE           NULL,
    [Rehire_Date]                                         DATE           NULL,
    [Termination_Date]                                    DATE           NULL,
    [Rehire_Y_N]                                          BIT            NULL,
    [Attrition]                                           BIT            NULL,
    [Days_Worked]                                         SMALLINT       NULL,
    [hours_of_overtime_for_last_month]                    FLOAT (53)     NULL,
    [hours_of_overtime_for_year]                          FLOAT (53)     NULL,
    [Date_of_last_Promotion]                              DATE           NULL,
    [Years_since_last_promotion_from_last_sal_change_rpt] FLOAT (53)     NULL,
    [increase_decrease]                                   FLOAT (53)     NULL,
    [Years_in_current_role_from_95_rpt]                   FLOAT (53)     NULL
);
GO

