--DROP PROCEDURE metricsvault.sp_InsertPipelineAudit
CREATE PROCEDURE metricsvault.sp_InsertPipelineAudit
    @PipelineName NVARCHAR(255),
    @PipelineRunId NVARCHAR(255),
    @JobId NVARCHAR(255),
    @ActivityName NVARCHAR(255),
    @ActivityType NVARCHAR(255),
    @ActivityRunId NVARCHAR(255),
    @SourceSchema NVARCHAR(255),
    @SourceName NVARCHAR(255),
    @DataRead BIGINT,
    @DataWritten BIGINT,
    @FilesRead INT,
    @FilesWritten INT,
    @TargetSchema NVARCHAR(255),
    @TargetName NVARCHAR(255),
    @ExecutionStartTime DATETIME2,
    @ExecutionEndTime DATETIME2,
    @Duration INT,
    @Status NVARCHAR(50),
    @Error NVARCHAR(MAX),
    @Output NVARCHAR(MAX),
    @ExecutionDetails NVARCHAR(MAX),
    @StatusCode NVARCHAR(50),
    @ExecutionStatus NVARCHAR(50),
    @RecoveryStatus NVARCHAR(50)
AS
BEGIN
    INSERT INTO metricsvault.PipelineAudit (
        PipelineName,
        PipelineRunId,
        JobId,
        ActivityName,
        ActivityType,
        ActivityRunId,
        SourceSchema,
        SourceName,
        DataRead,
        DataWritten,
        FilesRead,
        FilesWritten,
        TargetSchema,
        TargetName,
        ExecutionStartTime,
        ExecutionEndTime,
        Duration,
        Status,
        Error,
        Output,
        ExecutionDetails,
        StatusCode,
        ExecutionStatus,
        RecoveryStatus
    )
    VALUES (
        @PipelineName,
        @PipelineRunId,
        @JobId,
        @ActivityName,
        @ActivityType,
        @ActivityRunId,
        @SourceSchema,
        @SourceName,
        @DataRead,
        @DataWritten,
        @FilesRead,
        @FilesWritten,
        @TargetSchema,
        @TargetName,
        @ExecutionStartTime,
        @ExecutionEndTime,
        @Duration,
        @Status,
        @Error,
        @Output,
        @ExecutionDetails,
        @StatusCode,
        @ExecutionStatus,
        @RecoveryStatus
    );
END;

GO

