CREATE TABLE [dbo].[BOA_FIN_TRANS] (
    [TRH_SequenceNum]                         NVARCHAR (10)   NULL,
    [TRH_MasterCardRecSeqNum]                 NVARCHAR (10)   NULL,
    [TRH_MasterCardLoadDate]                  NVARCHAR (10)   NULL,
    [TRH_MasterCardLoadTime]                  NVARCHAR (10)   NULL,
    [ProcessingStartDate]                     NVARCHAR (10)   NULL,
    [ProcessingStartTime]                     NVARCHAR (10)   NULL,
    [ProcessingEndDate]                       NVARCHAR (10)   NULL,
    [ProcessingEndTime]                       NVARCHAR (10)   NULL,
    [FileReferenceNum]                        NVARCHAR (30)   NULL,
    [CDFVersionNum]                           NVARCHAR (5)    NULL,
    [RunModeIndicator]                        NVARCHAR (5)    NULL,
    [ProcessorNum]                            NVARCHAR (20)   NULL,
    [ProcessorName]                           NVARCHAR (20)   NULL,
    [MasterCardFileSequenceNum]               NVARCHAR (10)   NULL,
    [MasterCardResetNum]                      NVARCHAR (6)    NULL,
    [nboundSourceFormat]                      NVARCHAR (5)    NULL,
    [ICANumber]                               NVARCHAR (15)   NULL,
    [IssuerNumber]                            NVARCHAR (15)   NULL,
    [CorporationNumber]                       NVARCHAR (15)   NULL,
    [AccountNumber]                           NVARCHAR (20)   NULL,
    [ProcessorTransactionId]                  NVARCHAR (30)   NULL,
    [SequenceNum]                             NVARCHAR (10)   NULL,
    [MaintenanceCode]                         NVARCHAR (5)    NULL,
    [MasterCardRecSeqNum]                     NVARCHAR (10)   NULL,
    [MasterCardLoadDate]                      NVARCHAR (10)   NULL,
    [MasterCardLoadTime]                      NVARCHAR (10)   NULL,
    [MasterCardEstimatedTaxIndicator]         NVARCHAR (5)    NULL,
    [MasterCardFinancialTransactionId]        NVARCHAR (15)   NULL,
    [AlternateAccountNumber]                  NVARCHAR (20)   NULL,
    [AlternateAccountType]                    NVARCHAR (5)    NULL,
    [AlternateAccountNumber2]                 NVARCHAR (20)   NULL,
    [AlternateAccountType2]                   NVARCHAR (5)    NULL,
    [AcquirerReferenceData]                   NVARCHAR (40)   NULL,
    [CardHolderTransactionType]               NVARCHAR (5)    NULL,
    [PostingDate]                             NVARCHAR (10)   NULL,
    [TransactionDate]                         NVARCHAR (10)   NULL,
    [ProcessingDate]                          NVARCHAR (10)   NULL,
    [ApprovalCode]                            NVARCHAR (10)   NULL,
    [BanknetReferenceNum]                     NVARCHAR (15)   NULL,
    [DebitOrCreditIndicator]                  NVARCHAR (5)    NULL,
    [AmountInOriginalCurrency]                DECIMAL (18, 2) NULL,
    [OriginalCurrencyCode]                    NVARCHAR (5)    NULL,
    [AmountInPostedCurrency]                  DECIMAL (18, 2) NULL,
    [PostedCurrencyCode]                      NVARCHAR (5)    NULL,
    [PostedCurrencyConversionDate]            NVARCHAR (10)   NULL,
    [PostedConversionRate]                    DECIMAL (18, 6) NULL,
    [AmountInBillingCurrency]                 DECIMAL (18, 2) NULL,
    [BillingCurrencyCode]                     NVARCHAR (5)    NULL,
    [BillingCurrencyConversionDate]           NVARCHAR (10)   NULL,
    [BillingConversionRate]                   DECIMAL (18, 6) NULL,
    [CustomerCode]                            NVARCHAR (128)  NULL,
    [TotalTaxAmount]                          DECIMAL (18, 2) NULL,
    [TotalTaxCollectedIndicator]              NVARCHAR (1)    NULL,
    [CardAcceptorReferenceNum]                NVARCHAR (30)   NULL,
    [DestinationPostalCode]                   NVARCHAR (15)   NULL,
    [DestinationCountryCode]                  NVARCHAR (5)    NULL,
    [ShipFromPostalCode]                      NVARCHAR (15)   NULL,
    [UniqueInvoiceNum]                        NVARCHAR (40)   NULL,
    [TaxExemptIndicator]                      NVARCHAR (1)    NULL,
    [MemoFlag]                                NVARCHAR (1)    NULL,
    [DisputeTrackingNum]                      NVARCHAR (10)   NULL,
    [IssuerTransactionCode]                   NVARCHAR (5)    NULL,
    [TransactionCategory]                     NVARCHAR (5)    NULL,
    [TransactionCodeQualifier]                NVARCHAR (15)   NULL,
    [DataSource]                              NVARCHAR (15)   NULL,
    [MatchSwitch]                             NVARCHAR (15)   NULL,
    [AcquiringICA]                            NVARCHAR (15)   NULL,
    [CardAcceptorId]                          NVARCHAR (30)   NULL,
    [CardAcceptorName]                        NVARCHAR (128)  NULL,
    [CardAcceptorStreetAddress]               NVARCHAR (128)  NULL,
    [CardAcceptorCity]                        NVARCHAR (60)   NULL,
    [CardAcceptorStateProvince]               NVARCHAR (5)    NULL,
    [CardAcceptorLocationPostalCode]          NVARCHAR (60)   NULL,
    [CardAcceptorCountryCode]                 NVARCHAR (5)    NULL,
    [SoleProprietorName]                      NVARCHAR (60)   NULL,
    [CardAcceptorCustomerServiceTelephoneNum] NVARCHAR (15)   NULL,
    [LegalCorporationName]                    NVARCHAR (60)   NULL,
    [CardAcceptorBusinessCode]                NVARCHAR (10)   NULL,
    [CardAcceptorType]                        NVARCHAR (4)    NULL,
    [CardAcceptorTaxId]                       NVARCHAR (15)   NULL,
    [TaxAmountIndicator]                      NVARCHAR (5)    NULL,
    [TaxAmount]                               DECIMAL (18, 2) NULL,
    [TaxRate]                                 DECIMAL (18, 5) NULL,
    [TaxTypeIdentifier]                       NVARCHAR (5)    NULL
);
GO

