CREATE TABLE [dbo].[D365_VendorJournalHeader] (
    [JOURNALBATCHNUMBER] VARCHAR (50)  NULL,
    [DESCRIPTION]        VARCHAR (MAX) NULL,
    [ISPOSTED]           VARCHAR (10)  NULL,
    [JOURNALNAME]        VARCHAR (50)  NULL,
    [SALESTAXINCLUDED]   VARCHAR (50)  NULL
);
GO

