CREATE TABLE [dbo].[D365_POHeader] (
    [PURCHASEORDERNUMBER]                VARCHAR (20)  NULL,
    [ACCOUNTINGDATE]                     VARCHAR (20)  NULL,
    [CURRENCYCODE]                       VARCHAR (5)   NULL,
    [DEFAULTLEDGERDIMENSIONDISPLAYVALUE] VARCHAR (50)  NULL,
    [INVOICETYPE]                        VARCHAR (20)  NULL,
    [INVOICEVENDORACCOUNTNUMBER]         VARCHAR (20)  NULL,
    [ORDERVENDORACCOUNTNUMBER]           VARCHAR (20)  NULL,
    [PURCHASEORDERNAME]                  VARCHAR (MAX) NULL,
    [PURCHASEORDERSTATUS]                VARCHAR (50)  NULL,
    [VENDORORDERREFERENCE]               VARCHAR (MAX) NULL
);
GO

