SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[D365_VendorJournalLines](
	[JOURNALBATCHNUMBER] [varchar](50) NULL,
	[LINENUMBER] [numeric](18, 3) NULL,
	[ACCOUNTDISPLAYVALUE] [varchar](50) NULL,
	[ASSETID] [varchar](50) NULL,
	[ASSETTRANSTYPE] [varchar](50) NULL,
	[CREDIT] [numeric](18, 6) NULL,
	[CURRENCY] [varchar](10) NULL,
	[DATE] [varchar](20) NULL,
	[DEFAULTDIMENSIONDISPLAYVALUE] [varchar](50) NULL,
	[DELIVERYDATE] [varchar](20) NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[DUEDATE] [varchar](20) NULL,
	[INVOICE] [varchar](50) NULL,
	[INVOICEDATE] [varchar](20) NULL,
	[OFFSETACCOUNTDISPLAYVALUE] [varchar](50) NULL,
	[TRANSACTIONTYPE] [varchar](50) NULL,
	[VOUCHER] [varchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO

DROP INDEX IF EXISTS [IDX_D365_VendorJournalLines_VOUCHER] ON [dbo].[D365_VendorJournalLines]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_VendorJournalLines_VOUCHER] ON [dbo].[D365_VendorJournalLines]
(
	[VOUCHER] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO