CREATE TABLE [dbo].[D365_ENTITY_EXTRACTS] (
    [ENTITY_NAME]          NVARCHAR (60) NOT NULL,
    [MAX_LAST_UPDATE_DATE] NVARCHAR (40) NULL,
    [RECORDS_EXTRACTED]    INT           NULL,
    [LAST_EXTRACTION_DATE] DATETIME2 (7) NULL
);
GO

ALTER TABLE [dbo].[D365_ENTITY_EXTRACTS]
    ADD CONSTRAINT [PK_D365_ENTITY_EXTRACTS] PRIMARY KEY CLUSTERED ([ENTITY_NAME] ASC);
GO

