SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [dbo].[D365_General_Journal_entry]
GO
CREATE TABLE [dbo].[D365_General_Journal_entry](
	[GENERALJOURNALACCOUNTENTRYRECID] bigint NOT NULL,
	[ACCOUNTDISPLAYVALUE] varchar(50) NOT NULL,
	[ACCOUNTINGCURRENCYAMOUNT] numeric(15,2) NOT NULL,
	[ACCOUNTINGDATE] datetime2(7) NOT NULL,
	[CUSTOMERACCOUNT] varchar(20) NULL,
	[CUSTOMERNAME] varchar(100) NULL,
	[DESCRIPTION] varchar(500) NULL,
	[DOCUMENTDATE] datetime2(7) NOT NULL,
	[DOCUMENTNUMBER] varchar(20) NULL,
	[ISCORRECTION] varchar(5) NOT NULL,
	[ISCREDIT] varchar(5) NOT NULL,
	[JOURNALCATEGORY] varchar(20) NOT NULL,
	[JOURNALNUMBER] varchar(15) NOT NULL,
	[LEDGERACCOUNT] varchar(80) NOT NULL,
	[LEDGERNAME] varchar(5) NOT NULL,
	[POSTINGLAYER] varchar(10) NOT NULL,
	[POSTINGTYPE] varchar(50) NOT NULL,
	[QUANTITY] integer NOT NULL,
	[REPORTINGCURRENCYAMOUNT] numeric(15,2) NOT NULL,
	[TRANSACTIONCURRENCYAMOUNT] numeric(15,2) NOT NULL,
	[TRANSACTIONCURRENCYCODE] varchar(5) NOT NULL,
	[TRANSACTIONCURRENCYCREDITAMOUNT] numeric(15,2) NOT NULL,
	[TRANSACTIONCURRENCYDEBITAMOUNT] numeric(15,2) NOT NULL,
	[VENDORACCOUNT] integer NULL,
	[VENDORNAME] varchar(80) NULL,
	[VOUCHER] varchar(20) NOT NULL,
	[GL_ACCOUNT]  AS (substring([LEDGERACCOUNT],(20),(6))) PERSISTED,    
	[VOUCHER_VARCHAR]  AS (CONVERT([varchar](20),[VOUCHER])) PERSISTED,	
	[FN_LOC]  AS (substring([LEDGERACCOUNT],(1),(3))) PERSISTED,    
	[ExecutionRunId] nvarchar(100) NULL
) ON [PRIMARY] 
GO
ALTER TABLE [dbo].[D365_General_Journal_entry] ADD  CONSTRAINT [PK_D365_General_Journal_entry_v2] PRIMARY KEY CLUSTERED 
(
	[GENERALJOURNALACCOUNTENTRYRECID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_LEDGERACCOUNT] ON [dbo].[D365_General_Journal_entry]
GO
DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_VOUCHER] ON [dbo].[D365_General_Journal_entry]
GO
DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_FN_LOC] ON [dbo].[D365_General_Journal_entry]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_GL_ACCOUNT] ON [dbo].[D365_General_Journal_entry]
(
	[GL_ACCOUNT] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_LEDGERACCOUNT] ON [dbo].[D365_General_Journal_entry]
(
	[LEDGERACCOUNT] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_VOUCHER] ON [dbo].[D365_General_Journal_entry]
(
	[VOUCHER] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_FN_LOC] ON [dbo].[D365_General_Journal_entry]
(
	[FN_LOC] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
