SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [dbo].[D365_General_Journal_entry]
GO
CREATE TABLE [dbo].[D365_General_Journal_entry] (
    [GENERALJOURNALACCOUNTENTRYRECID] BIGINT          NOT NULL,
    [ACCOUNTDISPLAYVALUE]             VARCHAR (50)    NOT NULL,
    [ACCOUNTINGCURRENCYAMOUNT]        NUMERIC (15, 2) NOT NULL,
    [ACCOUNTINGDATE]                  DATETIME2 (7)   NOT NULL,
    [CUSTOMERACCOUNT]                 VARCHAR (20)    NULL,
    [CUSTOMERNAME]                    VARCHAR (100)   NULL,
    [DESCRIPTION]                     VARCHAR (500)   NULL,
    [DOCUMENTDATE]                    DATETIME2 (7)   NOT NULL,
    [DOCUMENTNUMBER]                  VARCHAR (20)    NULL,
    [ISCORRECTION]                    VARCHAR (5)     NOT NULL,
    [ISCREDIT]                        VARCHAR (5)     NOT NULL,
    [JOURNALCATEGORY]                 VARCHAR (20)    NOT NULL,
    [JOURNALNUMBER]                   VARCHAR (15)    NOT NULL,
    [LEDGERACCOUNT]                   VARCHAR (80)    NOT NULL,
    [LEDGERNAME]                      VARCHAR (5)     NOT NULL,
    [POSTINGLAYER]                    VARCHAR (10)    NOT NULL,
    [POSTINGTYPE]                     VARCHAR (50)    NOT NULL,
    [QUANTITY]                        INT             NOT NULL,
    [REPORTINGCURRENCYAMOUNT]         NUMERIC (15, 2) NOT NULL,
    [TRANSACTIONCURRENCYAMOUNT]       NUMERIC (15, 2) NOT NULL,
    [TRANSACTIONCURRENCYCODE]         VARCHAR (5)     NOT NULL,
    [TRANSACTIONCURRENCYCREDITAMOUNT] NUMERIC (15, 2) NOT NULL,
    [TRANSACTIONCURRENCYDEBITAMOUNT]  NUMERIC (15, 2) NOT NULL,
    [VENDORACCOUNT]                   VARCHAR (20)    NULL,
    [VENDORNAME]                      VARCHAR (80)    NULL,
    [VOUCHER]                         VARCHAR (20)    NOT NULL,
    [GL_ACCOUNT]                      AS              (substring([LEDGERACCOUNT],(20),(6))) PERSISTED,
    [VOUCHER_VARCHAR]                 AS              (CONVERT([varchar](20),[VOUCHER])) PERSISTED,
    [FN_LOC]                          AS              (substring([LEDGERACCOUNT],(1),(3))) PERSISTED,
    [ExecutionRunId]                  VARCHAR (100)   NULL,
    CONSTRAINT [PK_D365_General_Journal_entry_v2] PRIMARY KEY CLUSTERED ([GENERALJOURNALACCOUNTENTRYRECID] ASC)
); 
GO
ALTER TABLE [dbo].[D365_General_Journal_entry] ADD  CONSTRAINT [PK_D365_General_Journal_entry_v2] PRIMARY KEY CLUSTERED 
(
	[GENERALJOURNALACCOUNTENTRYRECID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_LEDGERACCOUNT] ON [dbo].[D365_General_Journal_entry]
GO
DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_VOUCHER] ON [dbo].[D365_General_Journal_entry]
GO
DROP INDEX IF EXISTS [IDX_D365_General_Journal_entry_FN_LOC] ON [dbo].[D365_General_Journal_entry]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_GL_ACCOUNT] ON [dbo].[D365_General_Journal_entry]
(
	[GL_ACCOUNT] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_LEDGERACCOUNT] ON [dbo].[D365_General_Journal_entry]
(
	[LEDGERACCOUNT] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_VOUCHER] ON [dbo].[D365_General_Journal_entry]
(
	[VOUCHER] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_D365_General_Journal_entry_FN_LOC] ON [dbo].[D365_General_Journal_entry]
(
	[FN_LOC] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
