CREATE TABLE [dbo].[D365_GeneralJournal] (
    [GENERALJOURNALACCOUNTENTRYRECID] NUMERIC (18)    NOT NULL,
    [LEDGERACCOUNT]                   VARCHAR (50)    NULL,
    [TRANSACTIONCURRENCYCODE]         VARCHAR (10)    NULL,
    [TRANSACTIONCURRENCYCREDITAMOUNT] NUMERIC (18, 6) NULL,
    [TRANSACTIONCURRENCYDEBITAMOUNT]  NUMERIC (18, 6) NULL,
    [VOUCHER]                         VARCHAR (50)    NULL
);
GO

ALTER TABLE [dbo].[D365_GeneralJournal]
    ADD CONSTRAINT [PK_D365_GeneralJournal] PRIMARY KEY CLUSTERED ([GENERALJOURNALACCOUNTENTRYRECID] ASC);
GO

