CREATE TABLE [dbo].[D365_MainAccount] (
    [CHARTOFACCOUNTS]                           VARCHAR (20)  NULL,
    [MAINACCOUNTID]                             VARCHAR (20)  NULL,
    [ACCOUNTCATEGORYDESCRIPTION]                VARCHAR (MAX) NULL,
    [ACTIVEFROM]                                VARCHAR (20)  NULL,
    [ACTIVETO]                                  VARCHAR (20)  NULL,
    [BALANCECONTROL]                            VARCHAR (20)  NULL,
    [CHARTOFACCOUNTSRECID]                      VARCHAR (20)  NULL,
    [CLOSING]                                   VARCHAR (20)  NULL,
    [DEBITCREDITDEFAULT]                        VARCHAR (20)  NULL,
    [DEBITCREDITREQUIREMENT]                    VARCHAR (20)  NULL,
    [DEFAULTCONSOLIDATIONACCOUNT]               VARCHAR (50)  NULL,
    [DEFAULTCURRENCY]                           VARCHAR (10)  NULL,
    [DONOTALLOWMANUALENTRY]                     VARCHAR (10)  NULL,
    [EXCHANGEADJUSTMENTRATETYPE]                VARCHAR (50)  NULL,
    [FINANCIALREPORTINGCURRENCYTRANSLATIONTYPE] VARCHAR (50)  NULL,
    [FINANCIALREPORTINGEXCHANGERATETYPE]        VARCHAR (50)  NULL,
    [FOREIGNCURRENCYREVALUATION]                VARCHAR (50)  NULL,
    [ISSUSPENDED]                               VARCHAR (50)  NULL,
    [MAINACCOUNTCATEGORY]                       VARCHAR (50)  NULL,
    [MAINACCOUNTRECID]                          VARCHAR (50)  NULL,
    [MAINACCOUNTTYPE]                           VARCHAR (50)  NULL,
    [MONETARY]                                  VARCHAR (50)  NULL,
    [NAME]                                      VARCHAR (MAX) NULL,
    [OFFSETACCOUNTDISPLAYVALUE]                 VARCHAR (50)  NULL,
    [OPENINGACCOUNTID]                          VARCHAR (50)  NULL,
    [POSTINGTYPE]                               VARCHAR (50)  NULL,
    [REPORTINGEXCHANGEADJUSTMENTRATETYPE]       VARCHAR (50)  NULL,
    [USER]                                      VARCHAR (50)  NULL,
    [VALIDATECURRENCY]                          VARCHAR (20)  NULL,
    [VALIDATEPOSTINGTYPE]                       VARCHAR (20)  NULL,
    [VALIDATEUSER]                              VARCHAR (20)  NULL
);
GO

