CREATE TABLE [dbo].[Emburse_ExpenseExport] (
    [CardLast4Digits]    NVARCHAR (10)   NULL,
    [MCC]                NVARCHAR (10)   NULL,
    [TxnNumber]          NVARCHAR (50)   NULL,
    [PostDate]           NVARCHAR (20)   NULL,
    [PurchaseDate]       NVARCHAR (20)   NULL,
    [ItemTotal]          NUMERIC (18, 2) NULL,
    [Amount]             NUMERIC (18, 2) NULL,
    [ReimbAmount]        NUMERIC (18, 2) NULL,
    [ItemDescription]    NVARCHAR (MAX)  NULL,
    [CardEmployeeID]     NVARCHAR (20)   NULL,
    [CHFullName]         NVARCHAR (MAX)  NULL,
    [PayeeName]          NVARCHAR (MAX)  NULL,
    [VendorName]         NVARCHAR (MAX)  NULL,
    [GLAccount]          NVARCHAR (50)   NULL,
    [GLAccountDesc]      NVARCHAR (MAX)  NULL,
    [GLLoco]             NVARCHAR (50)   NULL,
    [GLLocoDesc]         NVARCHAR (MAX)  NULL,
    [FullString]         NVARCHAR (MAX)  NULL,
    [ItemExpCatComment]  NVARCHAR (MAX)  NULL,
    [CHSignoffDate]      NVARCHAR (20)   NULL,
    [CHSignoffFullName]  NVARCHAR (MAX)  NULL,
    [MgrSignoffDate]     NVARCHAR (20)   NULL,
    [MgrSignoffFullName] NVARCHAR (MAX)  NULL,
    [ExpFolderName]      NVARCHAR (MAX)  NULL,
    [GrpName]            NVARCHAR (MAX)  NULL,
    [WorkOrder]          NVARCHAR (20)   NULL,
    [VoucherInvoiceNum]  NVARCHAR (20)   NULL,
    [LineNumber]         NVARCHAR (20)   NULL,
    [FileName]           NVARCHAR (100)  NULL,
    [InsertDate]         DATETIME2 (7)   NULL,
    [ImageProcessed]     SMALLINT        NULL
);
GO

