CREATE TABLE [dbo].[FreshService_Tickets] (
    [ticket_id]                NVARCHAR (30)  NOT NULL,
    [created_at]               NVARCHAR (30)  NULL,
    [updated_at]               NVARCHAR (30)  NULL,
    [opened_at]                NVARCHAR (30)  NULL,
    [group_escalated]          NVARCHAR (10)  NULL,
    [inbound_count]            NVARCHAR (30)  NULL,
    [status_updated_at]        NVARCHAR (30)  NULL,
    [outbound_count]           NVARCHAR (30)  NULL,
    [pending_since]            NVARCHAR (30)  NULL,
    [resolved_at]              NVARCHAR (30)  NULL,
    [closed_at]                NVARCHAR (30)  NULL,
    [first_assigned_at]        NVARCHAR (30)  NULL,
    [assigned_at]              NVARCHAR (30)  NULL,
    [agent_responded_at]       NVARCHAR (30)  NULL,
    [requester_responded_at]   NVARCHAR (30)  NULL,
    [first_responded_at]       NVARCHAR (30)  NULL,
    [first_resp_time_in_secs]  NVARCHAR (30)  NULL,
    [resolution_time_in_secs]  NVARCHAR (30)  NULL,
    [workspace_id]             NVARCHAR (30)  NULL,
    [subject]                  NVARCHAR (MAX) NULL,
    [group_id]                 NVARCHAR (30)  NULL,
    [department_id]            NVARCHAR (30)  NULL,
    [category]                 NVARCHAR (50)  NULL,
    [sub_category]             NVARCHAR (50)  NULL,
    [item_category]            NVARCHAR (50)  NULL,
    [requester_id]             NVARCHAR (30)  NULL,
    [responder_id]             NVARCHAR (30)  NULL,
    [due_by]                   NVARCHAR (30)  NULL,
    [fr_escalated]             NVARCHAR (10)  NULL,
    [deleted]                  NVARCHAR (10)  NULL,
    [spam]                     NVARCHAR (10)  NULL,
    [email_config_id]          NVARCHAR (50)  NULL,
    [fwd_emails]               NVARCHAR (MAX) NULL,
    [reply_cc_emails]          NVARCHAR (MAX) NULL,
    [cc_emails]                NVARCHAR (MAX) NULL,
    [is_escalated]             NVARCHAR (10)  NULL,
    [fr_due_by]                NVARCHAR (30)  NULL,
    [id]                       NVARCHAR (30)  NULL,
    [priority]                 NVARCHAR (30)  NULL,
    [status]                   NVARCHAR (30)  NULL,
    [source]                   NVARCHAR (30)  NULL,
    [created_at2]              NVARCHAR (30)  NULL,
    [updated_at2]              NVARCHAR (30)  NULL,
    [requested_for_id]         NVARCHAR (30)  NULL,
    [to_emails]                NVARCHAR (MAX) NULL,
    [type]                     NVARCHAR (30)  NULL,
    [description]              NVARCHAR (MAX) NULL,
    [description_text]         NVARCHAR (MAX) NULL,
    [major_incident_type]      NVARCHAR (30)  NULL,
    [business_impact]          NVARCHAR (30)  NULL,
    [impacted_locations]       NVARCHAR (30)  NULL,
    [no_of_customers_impacted] NVARCHAR (30)  NULL,
    [INSERTED_ON]              DATETIME2 (7)  NULL
);
GO

ALTER TABLE [dbo].[FreshService_Tickets]
    ADD CONSTRAINT [PK_FreshService_Tickets] PRIMARY KEY CLUSTERED ([ticket_id] ASC);
GO

