CREATE TABLE [dbo].[IScout_WSLC_Exceptions] (
    [FORM_ID]    INT            NULL,
    [REPORT]     NVARCHAR (256) NULL,
    [EIN]        NVARCHAR (9)   NULL,
    [FIRST_NAME] NVARCHAR (128) NULL,
    [LAST_NAME]  NVARCHAR (128) NULL,
    [LOB_CODE]   NVARCHAR (24)  NULL,
    [JOB_CODE]   NVARCHAR (128) NULL,
    [JOB_FAMILY] NVARCHAR (128) NULL,
    [MP_CODE]    NVARCHAR (128) NULL,
    [MP_NAME]    NVARCHAR (256) NULL,
    [LCO_CODE]   NVARCHAR (128) NULL,
    [LCO_NAME]   NVARCHAR (256) NULL
);
GO

