CREATE TABLE [dbo].[IScout_159094] (
    [link]             NVARCHAR (128) NULL,
    [report]           NVARCHAR (128) NULL,
    [report_number]    NVARCHAR (20)  NULL,
    [report_date]      NVARCHAR (30)  NULL,
    [updated]          NVARCHAR (30)  NULL,
    [updated_time]     NVARCHAR (20)  NULL,
    [version]          NVARCHAR (5)   NULL,
    [observer]         NVARCHAR (64)  NULL,
    [observer_emp_num] NVARCHAR (64)  NULL,
    [duration]         NVARCHAR (10)  NULL,
    [latitude]         NVARCHAR (30)  NULL,
    [longitude]        NVARCHAR (30)  NULL,
    [temperature]      NVARCHAR (7)   NULL,
    [wind_speed]       NVARCHAR (20)  NULL,
    [weather]          NVARCHAR (20)  NULL,
    [score_percent]    NVARCHAR (10)  NULL,
    [Q01]              NVARCHAR (64)  NULL,
    [Q02]              NVARCHAR (64)  NULL,
    [Q02_LAT]          NVARCHAR (64)  NULL,
    [Q02_LON]          NVARCHAR (64)  NULL,
    [Q03]              NVARCHAR (64)  NULL,
    [Q04]              NVARCHAR (64)  NULL,
    [Q05]              NVARCHAR (64)  NULL,
    [Q06]              NVARCHAR (64)  NULL,
    [Q07]              NVARCHAR (64)  NULL,
    [Q08]              NVARCHAR (64)  NULL,
    [Q09]              NVARCHAR (64)  NULL,
    [Q10]              NVARCHAR (64)  NULL,
    [Q11]              NVARCHAR (64)  NULL,
    [Q12]              NVARCHAR (64)  NULL,
    [Q13]              NVARCHAR (64)  NULL,
    [Q14]              NVARCHAR (64)  NULL,
    [Q15]              NVARCHAR (64)  NULL,
    [Q16]              NVARCHAR (64)  NULL,
    [Q17]              NVARCHAR (64)  NULL,
    [Q18]              NVARCHAR (64)  NULL,
    [Q19]              NVARCHAR (64)  NULL,
    [Q20]              NVARCHAR (64)  NULL,
    [Q21]              NVARCHAR (64)  NULL,
    [Q22]              NVARCHAR (64)  NULL,
    [Q23]              NVARCHAR (64)  NULL,
    [Q24]              NVARCHAR (64)  NULL,
    [Q25]              NVARCHAR (64)  NULL,
    [Q26]              NVARCHAR (64)  NULL,
    [Q27]              NVARCHAR (64)  NULL,
    [Q28]              NVARCHAR (64)  NULL,
    [Q29]              NVARCHAR (64)  NULL,
    [Q30]              NVARCHAR (64)  NULL,
    [Q41]              NVARCHAR (64)  NULL,
    [Q42]              NVARCHAR (64)  NULL,
    [Q43]              NVARCHAR (64)  NULL,
    [Q44]              NVARCHAR (64)  NULL,
    [Q45]              NVARCHAR (64)  NULL,
    [Q46]              NVARCHAR (64)  NULL,
    [Q47]              NVARCHAR (64)  NULL,
    [Q48]              NVARCHAR (64)  NULL,
    [Q49]              NVARCHAR (64)  NULL,
    [Q50]              NVARCHAR (64)  NULL,
    [Q51]              NVARCHAR (64)  NULL,
    [Q52]              NVARCHAR (64)  NULL,
    [Q53]              NVARCHAR (64)  NULL,
    [Q54]              NVARCHAR (64)  NULL,
    [Q55]              NVARCHAR (64)  NULL,
    [Q56]              NVARCHAR (64)  NULL,
    [Q57]              NVARCHAR (64)  NULL,
    [Q58]              NVARCHAR (64)  NULL,
    [Q59]              NVARCHAR (64)  NULL,
    [Q60]              NVARCHAR (64)  NULL,
    [Q61]              NVARCHAR (64)  NULL,
    [Q62]              NVARCHAR (64)  NULL,
    [Q63]              NVARCHAR (64)  NULL,
    [Q64]              NVARCHAR (64)  NULL,
    [Q65]              NVARCHAR (64)  NULL,
    [Q66]              NVARCHAR (64)  NULL,
    [Q67]              NVARCHAR (64)  NULL,
    [Q68]              NVARCHAR (64)  NULL,
    [Q69]              NVARCHAR (64)  NULL,
    [Q70]              NVARCHAR (64)  NULL,
    [Q71]              NVARCHAR (64)  NULL,
    [Q72]              NVARCHAR (64)  NULL,
    [Q73]              NVARCHAR (MAX) NULL,
    [Q74]              NVARCHAR (128) NULL,
    [Q75]              NVARCHAR (64)  NULL,
    [Q76]              NVARCHAR (64)  NULL,
    [Q77]              NVARCHAR (64)  NULL,
    [Q78]              NVARCHAR (64)  NULL,
    [Q79]              NVARCHAR (64)  NULL,
    [Q88_WorkOrderNum] NVARCHAR (64)  NULL,
    [Q80]              NVARCHAR (128) NULL,
    [Q81]              NVARCHAR (MAX) NULL,
    [Q82]              NVARCHAR (64)  NULL,
    [Q83]              NVARCHAR (64)  NULL,
    [Q84]              NVARCHAR (64)  NULL,
    [Q85]              NVARCHAR (64)  NULL,
    [Q86]              NVARCHAR (128) NULL,
    [Q87]              NVARCHAR (64)  NULL,
    [R01_COMMENTS]     NVARCHAR (MAX) NULL,
    [R01_InsertedOn]   DATETIME       NULL,
    [R01_BatchID]      INT            NULL,
    [R02_PRETRIP]      INT            NULL,
    [R02_POSTTRIP]     INT            NULL,
    [R02_SATISFACTORY] INT            NULL,
    [R02_DEFECTIVE]    INT            NULL,
    [R02_NA]           INT            NULL,
    [R02_YES]          INT            NULL,
    [R02_NO]           INT            NULL,
    [R02_KES]          INT            NULL,
    [R02_3RDPARTY]     INT            NULL,
    [Deleted]          INT            DEFAULT ((0)) NULL,
    [DeletedOn]        DATETIME       NULL,
    [Q_All_Defects]    NVARCHAR (5)   NULL
);
GO

