CREATE TABLE [dbo].[IScout_Safety_Meeting] (
    [S01_link]              NVARCHAR (128) NULL,
    [S02_report]            NVARCHAR (256) NULL,
    [S03_report_number]     NVARCHAR (128) NULL,
    [S04_report_date]       NVARCHAR (30)  NULL,
    [S05_updated]           NVARCHAR (30)  NULL,
    [S06_updated_time]      NVARCHAR (20)  NULL,
    [S07_version]           NVARCHAR (5)   NULL,
    [S08_observer]          NVARCHAR (64)  NULL,
    [S09_observer_emp_num]  NVARCHAR (20)  NULL,
    [S10_duration]          NVARCHAR (10)  NULL,
    [S11_latitude]          NVARCHAR (30)  NULL,
    [S12_longitude]         NVARCHAR (30)  NULL,
    [S13_temperature]       NVARCHAR (7)   NULL,
    [S14_wind_speed]        NVARCHAR (20)  NULL,
    [S15_weather]           NVARCHAR (20)  NULL,
    [S16_7adlpre8k27n0x45]  NVARCHAR (50)  NULL,
    [S17_Marketplace]       NVARCHAR (64)  NULL,
    [S18_LCO]               NVARCHAR (64)  NULL,
    [S19_District_Manager]  NVARCHAR (64)  NULL,
    [S20_Supervisor_PIC]    NVARCHAR (64)  NULL,
    [S21_Trainer]           NVARCHAR (64)  NULL,
    [S22_1wyg0gminqkr5ad2]  NVARCHAR (50)  NULL,
    [S23_j706l6m6dx1natjv]  NVARCHAR (50)  NULL,
    [S24_ebbhiasq03ft9mfd]  NVARCHAR (50)  NULL,
    [S25_11y4ihruzf5fe8j2]  NVARCHAR (50)  NULL,
    [S26_n5acfnz2ipa33qma]  NVARCHAR (50)  NULL,
    [S27_Additional_Topics] NVARCHAR (MAX) NULL,
    [S28_8hobod1rxxl4fxvd]  NVARCHAR (50)  NULL,
    [S29_bw5mg58yp2e7hput]  NVARCHAR (50)  NULL,
    [S30_Employee_Count]    NVARCHAR (10)  NULL,
    [S31_Employee]          NVARCHAR (MAX) NULL,
    [S32_parentrepnum]      NVARCHAR (50)  NULL,
    [S33_parentlink]        NVARCHAR (50)  NULL,
    [S34_surrogate]         NVARCHAR (50)  NULL,
    [S97_form_id]           INT            NULL,
    [S99_InsertedOn]        DATETIME       NULL,
    [S99_BatchID]           INT            NULL
);
GO

