CREATE TABLE [dbo].[IScout_266378] (
    [link]                            NVARCHAR (512) NULL,
    [report]                          NVARCHAR (256) NULL,
    [report_number]                   NVARCHAR (20)  NULL,
    [report_date]                     NVARCHAR (30)  NULL,
    [updated]                         NVARCHAR (30)  NULL,
    [upadted_time]                    NVARCHAR (20)  NULL,
    [version]                         NVARCHAR (5)   NULL,
    [observer]                        NVARCHAR (128) NULL,
    [observer_emp_num]                NVARCHAR (128) NULL,
    [duration]                        NVARCHAR (10)  NULL,
    [latitude]                        NVARCHAR (30)  NULL,
    [longitude]                       NVARCHAR (30)  NULL,
    [temperature]                     NVARCHAR (7)   NULL,
    [wind_speed]                      NVARCHAR (20)  NULL,
    [weather]                         NVARCHAR (20)  NULL,
    [General_Information]             NVARCHAR (512) NULL,
    [Marketplace]                     NVARCHAR (50)  NULL,
    [LCO]                             NVARCHAR (128) NULL,
    [Manager]                         NVARCHAR (128) NULL,
    [Sr_Supervisor]                   NVARCHAR (128) NULL,
    [Supervisor]                      NVARCHAR (128) NULL,
    [Rig_Operator_PIC]                NVARCHAR (256) NULL,
    [Rig_Asset_No]                    NVARCHAR (32)  NULL,
    [Customer]                        NVARCHAR (128) NULL,
    [Consultant_Name]                 NVARCHAR (128) NULL,
    [Well_Name_Lease_No]              NVARCHAR (128) NULL,
    [Service_Quality]                 NVARCHAR (128) NULL,
    [Supervisor_Participation]        NVARCHAR (10)  NULL,
    [Service_Quality_Concerns]        NVARCHAR (10)  NULL,
    [Service_Quality_Opportunities]   NVARCHAR (50)  NULL,
    [Supervisor_Comments]             NVARCHAR (MAX) NULL,
    [General_Questions]               NVARCHAR (MAX) NULL,
    [General_Question_Notes]          NVARCHAR (MAX) NULL,
    [Description_of_Visit]            NVARCHAR (256) NULL,
    [Visit_Comments]                  NVARCHAR (MAX) NULL,
    [Employee_Responsible_Inspection] NVARCHAR (128) NULL,
    [Employee_Name]                   NVARCHAR (128) NULL,
    [Employee_Signature]              NVARCHAR (10)  NULL,
    [select_yes]                      NVARCHAR (5)   NULL,
    [select_no]                       NVARCHAR (5)   NULL,
    [select_crew]                     NVARCHAR (5)   NULL,
    [select_process]                  NVARCHAR (5)   NULL,
    [select_equipment]                NVARCHAR (5)   NULL,
    [parentrepnum]                    NVARCHAR (5)   NULL,
    [parentlink]                      NVARCHAR (5)   NULL,
    [surrogate]                       NVARCHAR (5)   NULL,
    [InsertedOn]                      DATETIME       NULL,
    [BatchID]                         INT            NULL
);
GO

