CREATE TABLE [dbo].[IScout_322882] (
    [S0_R01_link]             NVARCHAR (128)  NULL,
    [S0_R02_report]           NVARCHAR (128)  NULL,
    [S0_R03_report_number]    NVARCHAR (20)   NULL,
    [S0_R04_report_date]      NVARCHAR (30)   NULL,
    [S0_R05_updated]          NVARCHAR (30)   NULL,
    [S0_R06_updated_time]     NVARCHAR (20)   NULL,
    [S0_R07_version]          NVARCHAR (5)    NULL,
    [S0_R08_observer]         NVARCHAR (64)   NULL,
    [S0_R09_observer_emp_num] NVARCHAR (64)   NULL,
    [S0_R10_duration]         NVARCHAR (10)   NULL,
    [S0_R11_latitude]         NVARCHAR (30)   NULL,
    [S0_R12_longitude]        NVARCHAR (30)   NULL,
    [S0_R13_temperature]      NVARCHAR (7)    NULL,
    [S0_R14_wind_speed]       NVARCHAR (20)   NULL,
    [S0_R15_weather]          NVARCHAR (20)   NULL,
    [S0_R16_dateTime]         NVARCHAR (40)   NULL,
    [S0_R17_marketplace]      NVARCHAR (64)   NULL,
    [S0_R18_LCO]              NVARCHAR (64)   NULL,
    [S0_R19_district_manager] NVARCHAR (64)   NULL,
    [S0_R20_supervisor]       NVARCHAR (64)   NULL,
    [S0_R21_operator_PIC]     NVARCHAR (64)   NULL,
    [S0_R22_assetNum]         NVARCHAR (64)   NULL,
    [S0_R23_shiftType]        NVARCHAR (64)   NULL,
    [S0_R24_crewType]         NVARCHAR (64)   NULL,
    [S0_R25_customer]         NVARCHAR (128)  NULL,
    [S1_R17]                  NVARCHAR (5)    NULL,
    [S1_R18]                  NVARCHAR (5)    NULL,
    [S1_R19]                  NVARCHAR (5)    NULL,
    [S1_R20]                  NVARCHAR (5)    NULL,
    [S1_R21]                  NVARCHAR (128)  NULL,
    [S1_R22]                  NVARCHAR (5)    NULL,
    [S1_R23]                  NVARCHAR (30)   NULL,
    [S1_R24]                  NVARCHAR (30)   NULL,
    [S1_R25]                  NVARCHAR (30)   NULL,
    [S1_R26]                  NVARCHAR (30)   NULL,
    [S1_R27]                  NVARCHAR (30)   NULL,
    [S2_R29]                  NVARCHAR (5)    NULL,
    [S2_R30]                  NVARCHAR (5)    NULL,
    [S2_R31]                  NVARCHAR (5)    NULL,
    [S2_R32]                  NVARCHAR (5)    NULL,
    [S2_R33]                  NVARCHAR (5)    NULL,
    [S2_R34]                  NVARCHAR (5)    NULL,
    [S2_R35]                  NVARCHAR (5)    NULL,
    [S2_R36]                  NVARCHAR (5)    NULL,
    [S2_R37]                  NVARCHAR (5)    NULL,
    [S2_R38]                  NVARCHAR (128)  NULL,
    [S2_R39]                  NVARCHAR (128)  NULL,
    [S3_R41]                  NVARCHAR (5)    NULL,
    [S3_R42]                  NVARCHAR (5)    NULL,
    [S3_R43]                  NVARCHAR (5)    NULL,
    [S3_R44]                  NVARCHAR (5)    NULL,
    [S3_R45]                  NVARCHAR (5)    NULL,
    [S3_R46]                  NVARCHAR (5)    NULL,
    [S3_R47]                  NVARCHAR (5)    NULL,
    [S3_R48]                  NVARCHAR (128)  NULL,
    [S3_R49]                  NVARCHAR (128)  NULL,
    [S4_R51]                  NVARCHAR (1024) NULL,
    [S4_R52]                  NVARCHAR (1024) NULL,
    [S4_R54]                  NVARCHAR (128)  NULL,
    [S4_R54_SIGNED]           NVARCHAR (5)    NULL,
    [S4_R56]                  NVARCHAR (128)  NULL,
    [S4_R56_SIGNED]           NVARCHAR (5)    NULL,
    [S4_R58]                  NVARCHAR (128)  NULL,
    [S4_R58_SIGNED]           NVARCHAR (5)    NULL,
    [S99_InsertedOn]          DATETIME        NULL,
    [S99_BatchID]             INT             NULL,
    [S0_R15_score_percent]    NVARCHAR (5)    NULL,
    [S0_R26_Employee_Number]  INT             NULL,
    [S0_R27_Approved_Driver]  NVARCHAR (5)    NULL,
    [S1_R1]                   NVARCHAR (5)    NULL,
    [S1_R2]                   NVARCHAR (5)    NULL,
    [S1_R17_1]                NVARCHAR (5)    NULL,
    [S1_R17_2]                NVARCHAR (5)    NULL,
    [S1_R17_3]                NVARCHAR (5)    NULL,
    [S1_R17_4]                NVARCHAR (5)    NULL,
    [S1_R19_1]                NVARCHAR (5)    NULL,
    [S1_R19_2]                NVARCHAR (5)    NULL,
    [S1_R19_3]                NVARCHAR (512)  NULL,
    [S1_R19_4]                NVARCHAR (5)    NULL,
    [S2_R30_1]                NVARCHAR (5)    NULL,
    [S5_Description]          NVARCHAR (512)  NULL,
    [S5_Crew_Count]           INT             NULL,
    [S5_Crew_EIN]             NVARCHAR (MAX)  NULL,
    [S99_Form_No]             INT             NULL
);
GO

