--DROP TABLE IF EXISTS [dbo].[KeyView_Job_Activity_Exception] 
--Loaded in MDMQA, missing in MDMDB
CREATE TABLE [dbo].[KeyView_Job_Activity_Exception] (
    [JOB_ID]            NUMERIC (18)    NULL,
    [ACTIVITY_NUMBER]   NUMERIC (18)    NULL,
    [START_TIME]        DATETIME        NULL,
    [EXCEPTION_TYPE_ID] INT             NULL,
    [EXCEPTION_TYPE]    VARCHAR (50)    NULL,
    [END_TIME]          DATETIME        NULL,
    [DURATION]          NUMERIC (18, 6) NULL,
    [UPDATED]           VARCHAR (1)     NULL,
    [EXCEPTION_NUMBER]  NUMERIC (18)    NULL,
    [COMPLETE]          VARCHAR (1)     NULL,
    [NOTE_ID]           NUMERIC (18)    NULL,
    [AUTOCLASSIFIED]    VARCHAR (1)     NULL,
    [LAST_UPDATE]       DATETIME        NULL,
    [BILLABLE]          VARCHAR (1)     NULL,
    [NOTE_TEXT]         NVARCHAR (MAX)  NULL,
    [VARIANCE_ID_01]    INT             NULL,
    [VARIANCE_ID_02]    INT             NULL,
    [VARIANCE_ID_03]    INT             NULL,
    [VARIANCE_ID_04]    INT             NULL,
    [VARIANCE_ID_05]    INT             NULL,
    [VARIANCE_DESC_01]  VARCHAR (100)   NULL,
    [VARIANCE_DESC_02]  VARCHAR (100)   NULL,
    [VARIANCE_DESC_03]  VARCHAR (100)   NULL,
    [VARIANCE_DESC_04]  VARCHAR (100)   NULL,
    [VARIANCE_DESC_05]  VARCHAR (100)   NULL
);
GO

CREATE INDEX IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE
ON KeyView_Job_Activity_Exception (EXCEPTION_TYPE);

CREATE INDEX IDX_KeyView_Job_Activity_Exception_END_TIME
ON KeyView_Job_Activity_Exception (END_TIME)
INCLUDE (ACTIVITY_NUMBER, START_TIME, EXCEPTION_TYPE, EXCEPTION_NUMBER, VARIANCE_DESC_01, VARIANCE_DESC_04);

CREATE INDEX IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01
ON KeyView_Job_Activity_Exception (EXCEPTION_TYPE)
INCLUDE (VARIANCE_DESC_01);

CREATE INDEX IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01_03_04_05
ON KeyView_Job_Activity_Exception (EXCEPTION_TYPE)
INCLUDE (VARIANCE_DESC_01, VARIANCE_DESC_03, VARIANCE_DESC_04, VARIANCE_DESC_05);

CREATE INDEX IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01_02_03_04_05
ON KeyView_Job_Activity_Exception (EXCEPTION_TYPE, VARIANCE_DESC_01)
INCLUDE (VARIANCE_DESC_02, VARIANCE_DESC_03, VARIANCE_DESC_04, VARIANCE_DESC_05);

CREATE INDEX idx_job_activity_exception
ON DBO.KEYVIEW_JOB_ACTIVITY_EXCEPTION (EXCEPTION_TYPE, END_TIME)
INCLUDE (JOB_ID, ACTIVITY_NUMBER, VARIANCE_DESC_01, VARIANCE_DESC_04, VARIANCE_DESC_05, DURATION);

GO
CREATE NONCLUSTERED INDEX [idx_job_activity_exception]
    ON [dbo].[KeyView_Job_Activity_Exception]([EXCEPTION_TYPE] ASC, [END_TIME] ASC)
    INCLUDE([JOB_ID], [ACTIVITY_NUMBER], [VARIANCE_DESC_01], [VARIANCE_DESC_04], [VARIANCE_DESC_05], [DURATION]);
GO


CREATE NONCLUSTERED INDEX [IDX_KeyView_Job_Activity_Exception_END_TIME]
    ON [dbo].[KeyView_Job_Activity_Exception]([END_TIME] ASC)
    INCLUDE([ACTIVITY_NUMBER], [START_TIME], [EXCEPTION_TYPE], [DURATION], [EXCEPTION_NUMBER], [VARIANCE_DESC_01], [VARIANCE_DESC_02], [VARIANCE_DESC_03], [VARIANCE_DESC_04], [VARIANCE_DESC_05], [NOTE_TEXT]);
GO


CREATE NONCLUSTERED INDEX [IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE]
    ON [dbo].[KeyView_Job_Activity_Exception]([EXCEPTION_TYPE] ASC);
GO


CREATE NONCLUSTERED INDEX [IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01]
    ON [dbo].[KeyView_Job_Activity_Exception]([EXCEPTION_TYPE] ASC)
    INCLUDE([VARIANCE_DESC_01]);
GO


CREATE NONCLUSTERED INDEX [IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01_02_03_04_05]
    ON [dbo].[KeyView_Job_Activity_Exception]([EXCEPTION_TYPE] ASC, [VARIANCE_DESC_01] ASC)
    INCLUDE([VARIANCE_DESC_02], [VARIANCE_DESC_03], [VARIANCE_DESC_04], [VARIANCE_DESC_05]);
GO


CREATE NONCLUSTERED INDEX [IDX_KeyView_Job_Activity_Exception_EXCEPTION_TYPE_VARIANCE_DESC_01_03_04_05]
    ON [dbo].[KeyView_Job_Activity_Exception]([EXCEPTION_TYPE] ASC)
    INCLUDE([VARIANCE_DESC_01], [VARIANCE_DESC_03], [VARIANCE_DESC_04], [VARIANCE_DESC_05]);
GO


CREATE NONCLUSTERED INDEX [idx_KeyView_Job_Activity_Exception_VARIANCE_DESC_04]
    ON [dbo].[KeyView_Job_Activity_Exception]([VARIANCE_DESC_04] ASC)
    INCLUDE([EXCEPTION_TYPE], [VARIANCE_DESC_01], [VARIANCE_DESC_02], [VARIANCE_DESC_03], [VARIANCE_DESC_05]);
GO

