--DROP TABLE IF EXISTS [dbo].[KeyView_Job] 
--Loaded in MDMQA, missing in MDMDB
GO
CREATE TABLE [dbo].[KeyView_Job](
	[Job_ID] [numeric](18, 0) NOT NULL,
	[Job_Type_ID] [numeric](18, 0) NULL,
	[Start_Time] [datetime] NOT NULL,
	[End_Time] [datetime] NULL,
	[Perf_Depth] [numeric](18, 0) NULL,
	[Well_Type_ID] [numeric](18, 0) NULL,
	[TAC_PREUNSET_TENSION] [numeric](18, 0) NULL,
	[TAC_SET_TENSION] [numeric](18, 0) NULL,
	[DELAY_ESTIMATE] [numeric](18, 0) NULL,
	[CUSTOMER_JOB_ID] [nvarchar](20) NULL,
	[JOB_CLASS_ID] [numeric](18, 0) NULL,
	[WELLBORE_CONFIG_ID] [numeric](18, 0) NULL,
	[WSR_SUBMITTED_DATE] [datetime] NULL,
	[REGION_SET_ID] [numeric](18, 0) NULL,
	[ASSET_ID] [numeric](18, 0) NULL,
	[ASSIGNMENT_ID] [numeric](18, 0) NULL,
	[OU_ID] [numeric](18, 0) NULL,
	[CUSTOMER_OU_ID] [numeric](18, 0) NULL,
	[GPS_TIME] [datetime] NULL,
	[LATITUDE] [numeric](18, 0) NULL,
	[LONGITUDE] [numeric](18, 0) NULL,
	[WELL_ID] [numeric](18, 0) NULL,
	[SYSTEM_ASSIGNED_WELL_ID] [numeric](18, 0) NULL,
	[WELL_CONFIRMED] [bit] NULL,
	[LAST_UPDATE] [datetime] NULL,
	[TASK_ID] [numeric](18, 0) NULL,
	[JT_DESCRIPTION] [nvarchar](100) NULL,
	[JT_WORK_TYPE] [nvarchar](100) NULL,
	[MJ_DESCRIPTION] [nvarchar](100) NULL,
	[MJ_WORK_TYPE] [nvarchar](100) NULL,
	[WELL_API_NUMBER] [nvarchar](50) NULL,
	[WELL_SERIAL_NUMBER] [nvarchar](100) NULL,
	[WELL_DISTRICT] [nvarchar](100) NULL,
	[WELL_FIELD] [nvarchar](100) NULL,
	[WELLBORE_DESCRIPTION] [nvarchar](100) NULL,
	[OU_DISPLAY_NAME] [nvarchar](100) NULL,
	[OU_YARD_ID] [numeric](18, 0) NULL,
	[KV_ORG_UNIT] [nvarchar](100) NULL,
	[CU_ORG_UNIT] [nvarchar](100) NULL,
	[LOADED_EXECID] [nvarchar](100) NULL
) ON [PRIMARY]
GO
