CREATE TABLE [dbo].[KeyView_Events] (
    [JOB_ID]        NUMERIC (18)  NOT NULL,
    [EVENT_NUMBER]  NUMERIC (18)  NOT NULL,
    [EVENT_ID]      NUMERIC (18)  NULL,
    [START_TIME]    DATETIME      NULL,
    [END_TIME]      DATETIME      NULL,
    [SEVERITY]      NUMERIC (18)  NULL,
    [RDC_COMMENT]   VARCHAR (256) NULL,
    [LAST_UPDATE]   DATETIME      NULL,
    [DESCRIPTION]   VARCHAR (100) NULL,
    [ALARM]         VARCHAR (5)   NULL,
    [SERVICE_LEVEL] NUMERIC (18)  NULL,
    [DISPLAY_LEVEL] NUMERIC (18)  NULL
);
GO

ALTER TABLE [dbo].[KeyView_Events]
    ADD CONSTRAINT [PK_KeyView_Events] PRIMARY KEY CLUSTERED ([JOB_ID] ASC, [EVENT_NUMBER] ASC);
GO

