CREATE TABLE [dbo].[KeyViewAssetTransReport] (
    [AssetNumber]    VARCHAR (20)  NOT NULL,
    [Series]         VARCHAR (50)  NULL,
    [Status]         VARCHAR (20)  NULL,
    [LastEventDate]  VARCHAR (20)  NULL,
    [LastWTDate]     VARCHAR (20)  NULL,
    [DaysDiff]       VARCHAR (20)  NULL,
    [LastJobEndDate] VARCHAR (20)  NULL,
    [AREA_CODE]      VARCHAR (50)  NULL,
    [AREA_NAME]      VARCHAR (128) NULL,
    [CNTY_CODE]      VARCHAR (50)  NULL,
    [CNTY_NAME]      VARCHAR (128) NULL,
    [CONT_CODE]      VARCHAR (50)  NULL,
    [CONT_NAME]      VARCHAR (128) NULL,
    [DEPT_CODE]      VARCHAR (50)  NULL,
    [DEPT_NAME]      VARCHAR (128) NULL,
    [DIST_CODE]      VARCHAR (50)  NULL,
    [DIST_NAME]      VARCHAR (128) NULL,
    [HEMI_CODE]      VARCHAR (50)  NULL,
    [HEMI_NAME]      VARCHAR (128) NULL,
    [LOB_CODE]       VARCHAR (50)  NULL,
    [LOB_NAME]       VARCHAR (128) NULL,
    [LOCA_CODE]      VARCHAR (50)  NULL,
    [LOCA_NAME]      VARCHAR (128) NULL,
    [LOCO_CODE]      VARCHAR (50)  NULL,
    [LOCO_NAME]      VARCHAR (128) NULL,
    [LVL1_CODE]      VARCHAR (50)  NULL,
    [LVL1_NAME]      VARCHAR (128) NULL,
    [LVL2_CODE]      VARCHAR (50)  NULL,
    [LVL2_NAME]      VARCHAR (128) NULL,
    [MAREA_CODE]     VARCHAR (50)  NULL,
    [MAREA_NAME]     VARCHAR (128) NULL,
    [MKTP_CODE]      VARCHAR (50)  NULL,
    [MKTP_NAME]      VARCHAR (128) NULL,
    [SEG_CODE]       VARCHAR (50)  NULL,
    [SEG_NAME]       VARCHAR (128) NULL,
    [SVC_CODE]       VARCHAR (50)  NULL,
    [SVC_NAME]       VARCHAR (128) NULL,
    [YARD_CODE]      VARCHAR (50)  NULL,
    [YARD_NAME]      VARCHAR (128) NULL
);
GO

