CREATE TABLE [dbo].[KVP_Activity] (
    [ACTIVITY_ID]          NUMERIC (18)  NOT NULL,
    [ACTIVITY_TYPE_ID]     NUMERIC (18)  NOT NULL,
    [DESCRIPTION]          VARCHAR (100) NULL,
    [FULL_DESCRIPTION]     VARCHAR (100) NULL,
    [GROUP_ID]             NUMERIC (18)  NULL,
    [START_SUMMARY]        VARCHAR (5)   NOT NULL,
    [SUMMARY_TEXT]         VARCHAR (256) NULL,
    [ACTIVITY_CATEGORY_ID] VARCHAR (10)  NOT NULL,
    [ACTIVITY_CLASS_ID]    VARCHAR (10)  NOT NULL,
    [ENGINE_USAGE_GROUP]   VARCHAR (10)  NOT NULL,
    [INCLUDE_IDLE_TIME]    VARCHAR (5)   NOT NULL
);
GO

ALTER TABLE [dbo].[KVP_Activity]
    ADD CONSTRAINT [PK_KVP_Activity] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC);
GO

