CREATE TABLE [dbo].[KVP_JOB_EVENT] (
    [JOB_ID]        NUMERIC (18)  NOT NULL,
    [EVENT_NUMBER]  NUMERIC (18)  NOT NULL,
    [EVENT_ID]      NUMERIC (18)  NULL,
    [START_TIME]    DATETIME      NULL,
    [END_TIME]      DATETIME      NULL,
    [SEVERITY]      NUMERIC (18)  NULL,
    [RDC_COMMENT]   VARCHAR (256) NULL,
    [LAST_UPDATE]   DATETIME      NULL,
    [B_TRANSACTION] VARCHAR (100) NULL,
    [extracted]     DATETIME2 (7) NULL,
    [transmitted]   DATETIME2 (7) NULL
);
GO

ALTER TABLE [dbo].[KVP_JOB_EVENT]
    ADD CONSTRAINT [PK_KVP_JOB_EVENT] PRIMARY KEY CLUSTERED ([JOB_ID] ASC, [EVENT_NUMBER] ASC);
GO

