CREATE TABLE [dbo].[KVP_JOB_ACTIVITY_EXCEPTION] (
    [JOB_ID]            NUMERIC (18)  NOT NULL,
    [EXCEPTION_NUMBER]  NUMERIC (18)  NOT NULL,
    [ACTIVITY_NUMBER]   NUMERIC (18)  NOT NULL,
    [START_TIME]        DATE          NOT NULL,
    [EXCEPTION_TYPE_ID] NUMERIC (18)  NOT NULL,
    [END_TIME]          DATE          NULL,
    [UPDATED]           VARCHAR (10)  NULL,
    [COMPLETE]          VARCHAR (10)  NULL,
    [NOTE_ID]           NUMERIC (18)  NULL,
    [AUTOCLASSIFIED]    VARCHAR (10)  NULL,
    [LAST_UPDATE]       DATE          NULL,
    [BILLABLE]          VARCHAR (10)  NULL,
    [B_TRANSACTION]     VARCHAR (100) NULL,
    [extracted]         DATETIME2 (7) NULL,
    [transmitted]       DATETIME2 (7) NULL
);
GO

ALTER TABLE [dbo].[KVP_JOB_ACTIVITY_EXCEPTION]
    ADD CONSTRAINT [PK_KeyView_JOB_ACTIVITY_EXCEPTION_RAW] PRIMARY KEY CLUSTERED ([JOB_ID] ASC, [EXCEPTION_NUMBER] ASC);
GO

