CREATE TABLE [dbo].[LaborIncremental2] (
    [ROW_ID]            NVARCHAR (20)    NOT NULL,
    [SOURCE_FILE]       NVARCHAR (255)   NULL,
    [RUN_DATE]          DATETIME2 (7)    DEFAULT (getdate()) NULL,
    [CHANGED_DATE]      DATETIME2 (7)    NULL,
    [CREATED_BY]        NVARCHAR (50)    NULL,
    [BILLING_FLAG]      NVARCHAR (1)     NULL,
    [ASSET_NUMBER]      NVARCHAR (50)    NULL,
    [CUSTOMER_ID]       NVARCHAR (50)    NULL,
    [JOB_CODE]          NVARCHAR (50)    NULL,
    [WORK_DATE]         DATETIME2 (7)    NULL,
    [WORK_STATE]        NVARCHAR (50)    NULL,
    [WORK_TYPE]         NVARCHAR (50)    NULL,
    [WORK_TYPE_CODE]    NVARCHAR (50)    NULL,
    [STATUS_CODE]       NVARCHAR (50)    NULL,
    [EMPLOYEE_ID]       INT              NULL,
    [DURATION]          DECIMAL (18, 10) NULL,
    [CUSTOMER_ORDER_ID] NVARCHAR (50)    NULL,
    [PAY_RATE]          DECIMAL (18, 10) NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);
GO

CREATE INDEX IDX_LaborIncremental2_ASSET_NUMBER
ON LaborIncremental2 (ASSET_NUMBER)
INCLUDE (SOURCE_FILE, RUN_DATE, CHANGED_DATE, CREATED_BY, BILLING_FLAG, CUSTOMER_ID, JOB_CODE, WORK_DATE, WORK_STATE, WORK_TYPE, WORK_TYPE_CODE, STATUS_CODE, EMPLOYEE_ID, DURATION, CUSTOMER_ORDER_ID, PAY_RATE);

CREATE INDEX IDX_LaborIncremental2_SOURCE_FILE_WORK_TYPE
ON LaborIncremental2 (SOURCE_FILE)
INCLUDE (WORK_TYPE, RUN_DATE, CHANGED_DATE, CREATED_BY, BILLING_FLAG, ASSET_NUMBER, CUSTOMER_ID, JOB_CODE, WORK_DATE, WORK_STATE, WORK_TYPE_CODE, STATUS_CODE, EMPLOYEE_ID, DURATION, CUSTOMER_ORDER_ID, PAY_RATE);

CREATE INDEX IDX_LaborIncremental2_CUSTOMER_ID_WORK_DATE
ON LaborIncremental2 (CUSTOMER_ID, WORK_DATE)
INCLUDE (SOURCE_FILE, RUN_DATE, CHANGED_DATE, CREATED_BY, BILLING_FLAG, ASSET_NUMBER, JOB_CODE, WORK_STATE, WORK_TYPE, WORK_TYPE_CODE, STATUS_CODE, EMPLOYEE_ID, DURATION, CUSTOMER_ORDER_ID, PAY_RATE);
