CREATE TABLE [dbo].[LOCO_Hierarchy] (
    [LOCO_ID]   INT            NOT NULL,
    [LOCO_CODE] VARCHAR (50)   NULL,
    [LOCO_NAME] NVARCHAR (250) NULL,
    [LOB_NAME]  VARCHAR (250)  NULL,
    [MKTP_NAME] VARCHAR (250)  NULL,
    [DIST_NAME] VARCHAR (250)  NULL,
    [YARD_NAME] VARCHAR (250)  NULL
);
GO

