CREATE TABLE [dbo].[LOCO_Hierarchy] (
    [LOCO_ID]             INT           NOT NULL,
    [LOCO_CODE]           VARCHAR (50)  NULL,
    [LOCO_NAME]           VARCHAR (150) NULL,
    [LOCO_STATUS]         VARCHAR (20)  NULL,
    [LOCO_REVENUE_FLAG]   INT           NULL,
    [LOCO_EXPENSE_FLAG]   INT           NULL,
    [LOCO_FINANCIAL_FLAG] INT           NULL,
    [LOCO_SOURCE]         VARCHAR (20)  NULL,
    [LOCO_CREATED_AT]     DATE          NULL,
    [LOCO_UPDATED_AT]     DATE          NULL,
    [LOCA_CODE]           VARCHAR (50)  NULL,
    [LOCA_NAME]           VARCHAR (150) NULL,
    [LOCA_ID]             INT           NULL,
    [AREA_CODE]           VARCHAR (50)  NULL,
    [AREA_NAME]           VARCHAR (150) NULL,
    [AREA_ID]             INT           NULL,
    [MKTP_CODE]           VARCHAR (50)  NULL,
    [MKTP_NAME]           VARCHAR (150) NULL,
    [MKTP_ID]             INT           NULL,
    [CTRY_CODE]           VARCHAR (50)  NULL,
    [CTRY_NAME]           VARCHAR (150) NULL,
    [CTRY_ID]             INT           NULL,
    [CONT_CODE]           VARCHAR (50)  NULL,
    [CONT_NAME]           VARCHAR (150) NULL,
    [CONT_ID]             INT           NULL,
    [HEMI_CODE]           VARCHAR (50)  NULL,
    [HEMI_NAME]           VARCHAR (150) NULL,
    [HEMI_ID]             INT           NULL,
    [LVL1_CODE]           VARCHAR (50)  NULL,
    [LVL1_NAME]           VARCHAR (150) NULL,
    [LVL1_ID]             INT           NULL,
    [LOB_CODE]            VARCHAR (50)  NULL,
    [LOB_NAME]            VARCHAR (150) NULL,
    [LOB_ID]              INT           NULL,
    [SERV_CODE]           VARCHAR (50)  NULL,
    [SERV_NAME]           VARCHAR (150) NULL,
    [SERV_ID]             INT           NULL,
    [SEGM_CODE]           VARCHAR (50)  NULL,
    [SEGM_NAME]           VARCHAR (150) NULL,
    [SEGM_ID]             INT           NULL,
    [LVL2_CODE]           VARCHAR (50)  NULL,
    [LVL2_NAME]           VARCHAR (150) NULL,
    [LVL2_ID]             INT           NULL,
    [DEPT_CODE]           VARCHAR (50)  NULL,
    [DEPT_NAME]           VARCHAR (150) NULL,
    [DEPT_ID]             INT           NULL,
    [DIST_CODE]           VARCHAR (50)  NULL,
    [DIST_NAME]           VARCHAR (150) NULL,
    [DIST_ID]             INT           NULL,
    [MARE_CODE]           VARCHAR (50)  NULL,
    [MARE_NAME]           VARCHAR (150) NULL,
    [MARE_ID]             INT           NULL,
    [IORG_CODE]           VARCHAR (50)  NULL,
    [IORG_NAME]           VARCHAR (150) NULL,
    [IORG_ID]             INT           NULL,
    [YARD_CODE]           VARCHAR (50)  NULL,
    [YARD_NAME]           VARCHAR (150) NULL,
    [YARD_ID]             INT           NULL
);
GO

