CREATE TABLE [dbo].[Salesforce_Invoice_Header] (
    [AFE_REQUIREMENTS_C]                 NVARCHAR (50)  NULL,
    [ALTSYNC_C]                          NVARCHAR (50)  NULL,
    [APPROVER_REQUIREMENTS_C]            NVARCHAR (100) NULL,
    [BALANCE_C]                          FLOAT (53)     NULL,
    [BARCODE64_C]                        NVARCHAR (MAX) NULL,
    [BARCODE_C]                          NVARCHAR (200) NULL,
    [BILL_TO_SITE_REQUIREMENTS_C]        NVARCHAR (100) NULL,
    [BILL_TO_C]                          NVARCHAR (100) NULL,
    [CONDITIONAL_DATA_C]                 NVARCHAR (50)  NULL,
    [CONTRACT_REQUIREMENTS_C]            NVARCHAR (50)  NULL,
    [CONVERTED_FROM_DRAFT_TO_INVOICE_C]  NVARCHAR (50)  NULL,
    [COST_CENTER_REQUIREMENTS_C]         NVARCHAR (50)  NULL,
    [COUNT_OF_INVOICES_C]                TINYINT        NULL,
    [CREATEDBYID]                        NVARCHAR (50)  NULL,
    [CREATEDDATE]                        NVARCHAR (50)  NULL,
    [CREDIT_REVISION_NUMBER_C]           NVARCHAR (50)  NULL,
    [CREDIT_TAXES_C]                     FLOAT (53)     NULL,
    [CREDIT_TOTAL_C]                     FLOAT (53)     NULL,
    [CUSTOMER_NUMBER_C]                  INT            NULL,
    [DRAFT_DATE_C]                       NVARCHAR (50)  NULL,
    [EDI_VALIDATION_COUNT_ON_INV_ITEM_C] TINYINT        NULL,
    [EXTRACTED_TO_AZURE_C]               NVARCHAR (50)  NULL,
    [FX5_BALANCE_DUE_C]                  FLOAT (53)     NULL,
    [FX5_CUSTOMERACCOUNT_C]              NVARCHAR (50)  NULL,
    [FX5_DUE_DATE_C]                     NVARCHAR (30)  NULL,
    [FX5_INVOICE_DATE_C]                 DATE           NULL,
    [FX5_OFFICE_C]                       NVARCHAR (50)  NULL,
    [FX5_PAYMENT_TERMS_C]                NVARCHAR (10)  NULL,
    [FX5_PRICE_BOOK_C]                   NVARCHAR (50)  NULL,
    [FX5_STATUS_C]                       NVARCHAR (10)  NULL,
    [FX5_SYNCID_C]                       NVARCHAR (50)  NULL,
    [FX5_TOTAL_CREDITS_C]                TINYINT        NULL,
    [FX5_TOTAL_INVOICE_C]                FLOAT (53)     NULL,
    [FX5_TOTAL_PAYMENTS_C]               TINYINT        NULL,
    [FX5_TRACKING_NUMBER_C]              NVARCHAR (50)  NULL,
    [FEATURE_CODE_REQUIREMENTS_C]        NVARCHAR (50)  NULL,
    [GENERAL_LEDGER_ID_REQUIREMENTS_C]   NVARCHAR (50)  NULL,
    [GROSS_CREDITS_C]                    FLOAT (53)     NULL,
    [GROSS_SALES_C]                      FLOAT (53)     NULL,
    [GROSS_TOTAL_C]                      FLOAT (53)     NULL,
    [ID]                                 NVARCHAR (50)  NULL,
    [INVOICESTATUS_C]                    NVARCHAR (50)  NULL,
    [INVOICE_NUMBER_C]                   NVARCHAR (50)  NULL,
    [INVOICE_REVISION_C]                 TINYINT        NULL,
    [INVOICE_STATUS_VALIDATION_CHECK_C]  NVARCHAR (50)  NULL,
    [INVOICE_TOTAL_C]                    FLOAT (53)     NULL,
    [ISDELETED]                          NVARCHAR (50)  NULL,
    [LASTACTIVITYDATE]                   NVARCHAR (30)  NULL,
    [LASTMODIFIEDBYID]                   NVARCHAR (50)  NULL,
    [LASTMODIFIEDDATE]                   NVARCHAR (50)  NULL,
    [LASTREFERENCEDDATE]                 NVARCHAR (30)  NULL,
    [LASTVIEWEDDATE]                     NVARCHAR (30)  NULL,
    [MARKETPLACE_NAME_C]                 NVARCHAR (50)  NULL,
    [MARKETPLACE_C]                      NVARCHAR (50)  NULL,
    [NAME]                               NVARCHAR (50)  NULL,
    [NETWORK_ACTIVITY_REQUIREMENTS_C]    NVARCHAR (100) NULL,
    [OFFICENAMES_C]                      NVARCHAR (200) NULL,
    [OTHER_EDI_INFO_REQUIREMENTS_C]      NVARCHAR (50)  NULL,
    [OWNERID]                            NVARCHAR (50)  NULL,
    [PO_REQUIREMENTS_C]                  NVARCHAR (100) NULL,
    [PLANT_CODE_REQUIREMENTS_C]          NVARCHAR (100) NULL,
    [PURCHASING_GROUP_REQUIREMENTS_C]    NVARCHAR (100) NULL,
    [RECORDTYPEID]                       NVARCHAR (50)  NULL,
    [RECORD_TYPE_C]                      NVARCHAR (50)  NULL,
    [REPORT_TOTAL_C]                     FLOAT (53)     NULL,
    [REQUESTOR_REQUIREMENTS_C]           NVARCHAR (50)  NULL,
    [REQUIRED_DATA_C]                    NVARCHAR (200) NULL,
    [ROUTING_CODE_REQUIREMENTS_C]        NVARCHAR (50)  NULL,
    [SALES_TAX_C]                        FLOAT (53)     NULL,
    [SHOWERRORCUSTREPORT_C]              NVARCHAR (50)  NULL,
    [SHOWERRORREPORT_C]                  BIT            NULL,
    [SYSTEMMODSTAMP]                     NVARCHAR (50)  NULL,
    [TAX_ERROR_DETAILS_C]                NVARCHAR (500) NULL,
    [TICKET_REPORT_C]                    NVARCHAR (50)  NULL,
    [USERNICK_C]                         NVARCHAR (50)  NULL,
    [WBS_ELEMENT_REQUIREMENTS_C]         NVARCHAR (50)  NULL,
    [WES_DRAFT_INVOICE_C]                NVARCHAR (50)  NULL,
    [WES_INVOICE_C]                      NVARCHAR (50)  NULL,
    [WORK_ORDER_REQUIREMENTS_C]          NVARCHAR (100) NULL
);
GO

