CREATE TABLE [dbo].[Salesforce_Invoice_Item] (
    [Id]                                NVARCHAR (18)   NOT NULL,
    [IsDeleted]                         NVARCHAR (5)    NULL,
    [Name]                              NVARCHAR (80)   NULL,
    [CreatedDate]                       DATETIME2 (0)   NULL,
    [CreatedById]                       NVARCHAR (18)   NULL,
    [LastModifiedDate]                  DATETIME2 (0)   NULL,
    [LastModifiedById]                  NVARCHAR (18)   NULL,
    [SystemModstamp]                    DATETIME2 (0)   NULL,
    [LastActivityDate]                  DATETIME2 (0)   NULL,
    [LastViewedDate]                    DATETIME2 (0)   NULL,
    [LastReferencedDate]                DATETIME2 (0)   NULL,
    [FX5__Invoice__c]                   NVARCHAR (18)   NULL,
    [FX5__COGS_Account__c]              NVARCHAR (18)   NULL,
    [FX5__Catalog_UOM__c]               NVARCHAR (50)   NULL,
    [FX5__Description__c]               NVARCHAR (255)  NULL,
    [FX5__Discount_Percent__c]          DECIMAL (18, 2) NULL,
    [FX5__Extended_Amount__c]           DECIMAL (18, 2) NULL,
    [FX5__Income_Account__c]            NVARCHAR (18)   NULL,
    [FX5__Item_Code__c]                 NVARCHAR (255)  NULL,
    [FX5__Parent_Invoice_Item__c]       NVARCHAR (18)   NULL,
    [FX5__Price_Book_Item__c]           NVARCHAR (18)   NULL,
    [FX5__Price__c]                     DECIMAL (18, 2) NULL,
    [FX5__Qty__c]                       DECIMAL (18, 2) NULL,
    [FX5__Sequence_Number__c]           DECIMAL (18, 4) NULL,
    [FX5__Ticket_Item__c]               NVARCHAR (18)   NULL,
    [FX5__CustomerAccount__c]           NVARCHAR (255)  NULL,
    [FX5__Office__c]                    NVARCHAR (255)  NULL,
    [FX5__Override__c]                  NVARCHAR (18)   NULL,
    [FX5__PBI_Override_Cost_Method__c]  NVARCHAR (18)   NULL,
    [FX5__PBI_Override_Price_Method__c] NVARCHAR (18)   NULL,
    [FX5__SyncID__c]                    NVARCHAR (50)   NULL,
    [AFE_Requirements__c]               NVARCHAR (255)  NULL,
    [Additional_Description__c]         NVARCHAR (255)  NULL,
    [Business_Unit__c]                  NVARCHAR (255)  NULL,
    [Cost_Center__c]                    NVARCHAR (255)  NULL,
    [Credit_Group_Id__c]                NVARCHAR (18)   NULL,
    [Credit_Group_Time_Stamp__c]        DATETIME2 (0)   NULL,
    [Credit_Item__c]                    NVARCHAR (5)    NULL,
    [Customer_Price__c]                 DECIMAL (18, 2) NULL,
    [Equipment_Asset_Number__c]         NVARCHAR (18)   NULL,
    [KES_ID_Requirements__c]            NVARCHAR (255)  NULL,
    [KeyId__c]                          NVARCHAR (50)   NULL,
    [Level_1__c]                        NVARCHAR (50)   NULL,
    [Level_2__c]                        NVARCHAR (50)   NULL,
    [List_Price__c]                     DECIMAL (18, 2) NULL,
    [Location__c]                       NVARCHAR (50)   NULL,
    [Network_Activity_Requirements__c]  NVARCHAR (255)  NULL,
    [PO_Line__c]                        NVARCHAR (10)   NULL,
    [Posted_IHUB__c]                    NVARCHAR (5)    NULL,
    [Service_Date__c]                   DATETIME2 (0)   NULL,
    [Tax_Product__c]                    NVARCHAR (MAX)  NULL,
    [Tax_State__c]                      NVARCHAR (10)   NULL,
    [Ticket_Number__c]                  NVARCHAR (20)   NULL,
    [Ticket_Office_Loco__c]             NVARCHAR (20)   NULL,
    [Transaction_Type__c]               NVARCHAR (MAX)  NULL,
    [WBS_Element_Requirements__c]       NVARCHAR (255)  NULL,
    [Well_City__c]                      NVARCHAR (80)   NULL,
    [Well_County__c]                    NVARCHAR (80)   NULL,
    [Well_Name__c]                      NVARCHAR (128)  NULL,
    [Well_State__c]                     NVARCHAR (20)   NULL,
    [Well_Zip__c]                       NVARCHAR (20)   NULL,
    [Sales_Tax__c]                      DECIMAL (18, 2) NULL,
    [AFE_Report__c]                     NVARCHAR (MAX)  NULL,
    [Approver_Report__c]                NVARCHAR (MAX)  NULL,
    [Asset__c]                          NVARCHAR (MAX)  NULL,
    [BillToReport__c]                   NVARCHAR (MAX)  NULL,
    [Bill_To_Site_Report__c]            NVARCHAR (MAX)  NULL,
    [Contract_Report__c]                NVARCHAR (MAX)  NULL,
    [Cost_Center_Report__c]             NVARCHAR (MAX)  NULL,
    [EDI_Validation__c]                 NVARCHAR (5)    NULL,
    [Extended_Total_Hidden__c]          DECIMAL (18, 2) NULL,
    [Extended_Total__c]                 DECIMAL (18, 2) NULL,
    [Feature_Code_Report__c]            NVARCHAR (MAX)  NULL,
    [General_Ledger_ID_Report__c]       NVARCHAR (MAX)  NULL,
    [Network_Activity_Report__c]        NVARCHAR (MAX)  NULL,
    [Other_EDI_Info_Report__c]          NVARCHAR (MAX)  NULL,
    [PO_Report__c]                      NVARCHAR (MAX)  NULL,
    [Plant_Code_Report__c]              NVARCHAR (MAX)  NULL,
    [Purchasing_Group_Report__c]        NVARCHAR (MAX)  NULL,
    [Requestor_Report__c]               NVARCHAR (MAX)  NULL,
    [Required_Data__c]                  NVARCHAR (MAX)  NULL,
    [Routing_Code_Report__c]            NVARCHAR (MAX)  NULL,
    [Service_Code__c]                   NVARCHAR (MAX)  NULL,
    [Service_Description__c]            NVARCHAR (MAX)  NULL,
    [Vanity_Code__c]                    NVARCHAR (20)   NULL,
    [Vanity_Description__c]             NVARCHAR (100)  NULL,
    [WBS_Element_Report__c]             NVARCHAR (MAX)  NULL,
    [Work_Order_Report__c]              NVARCHAR (MAX)  NULL,
    [Inv_Line_Num__c]                   DECIMAL (18)    NULL,
    [FX5__Catalog_Item__c]              NVARCHAR (MAX)  NULL,
    [Addl_Desc_Formula_Report__c]       NVARCHAR (MAX)  NULL,
    [Addl_Desc_Formula__c]              NVARCHAR (255)  NULL,
    [Asset2__c]                         NVARCHAR (100)  NULL,
    [Service_Date2__c]                  DATETIME2 (0)   NULL,
    [Service_Date_Report__c]            NVARCHAR (MAX)  NULL,
    [Service_Location__c]               NVARCHAR (100)  NULL,
    [Ticket_Number2__c]                 NVARCHAR (30)   NULL,
    [Ticket_Number_Report__c]           NVARCHAR (MAX)  NULL,
    [Well_Name_Report__c]               NVARCHAR (MAX)  NULL,
    [Include_in_Report__c]              NVARCHAR (MAX)  NULL,
    [Type__c]                           NVARCHAR (20)   NULL,
    [AltSync__c]                        NVARCHAR (5)    NULL,
    [FX5__ffx_Item_Type__c]             NVARCHAR (255)  NULL,
    [Do_Not_Delete__c]                  NVARCHAR (5)    NULL,
    CONSTRAINT [PK_Salesforce_Invoice_Item] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE NONCLUSTERED INDEX [NDX1_Salesforce_Invoice_Item]
    ON [dbo].[Salesforce_Invoice_Item]([FX5__Invoice__c] ASC, [Id] ASC);
GO

