CREATE TABLE [dbo].[Salesforce_Tickets] (
    [Id]                                      NVARCHAR (18)   NOT NULL,
    [IsDeleted]                               BIT             NULL,
    [Name]                                    NVARCHAR (240)  NULL,
    [RecordTypeId]                            NVARCHAR (18)   NULL,
    [CreatedDate]                             DATETIME2 (0)   NULL,
    [CreatedById]                             NVARCHAR (18)   NULL,
    [CreatedByUsername]                       NVARCHAR (50)   NULL,
    [LastModifiedDate]                        DATETIME2 (0)   NULL,
    [LastModifiedById]                        NVARCHAR (18)   NULL,
    [LastModifiedByUsername]                  NVARCHAR (50)   NULL,
    [SystemModstamp]                          DATETIME2 (0)   NULL,
    [LastActivityDate]                        DATETIME2 (0)   NULL,
    [LastViewedDate]                          DATETIME2 (0)   NULL,
    [LastReferencedDate]                      DATETIME2 (0)   NULL,
    [FX5__Job__c]                             NVARCHAR (18)   NULL,
    [FX5__Category__c]                        NVARCHAR (765)  NULL,
    [FX5__Checklist_Name__c]                  NVARCHAR (765)  NULL,
    [FX5__Created_in_Mobile__c]               BIT             NULL,
    [FX5__Customer_Survey_Performance__c]     NVARCHAR (765)  NULL,
    [FX5__Customer_Survey_Safety__c]          NVARCHAR (765)  NULL,
    [FX5__Customer_Survey_Satisfaction__c]    NVARCHAR (765)  NULL,
    [FX5__IsReadOnlyOnConsole__c]             BIT             NULL,
    [FX5__Notes__c]                           NVARCHAR (MAX)  NULL,
    [FX5__Office__c]                          NVARCHAR (3900) NULL,
    [FX5__Status__c]                          NVARCHAR (18)   NULL,
    [FX5__SyncID__c]                          NVARCHAR (150)  NULL,
    [FX5__Sync__c]                            BIT             NULL,
    [FX5__Ticket_Date__c]                     DATETIME2 (0)   NULL,
    [FX5__Tracking_Number__c]                 NVARCHAR (150)  NULL,
    [FX5__Warehouse__c]                       NVARCHAR (18)   NULL,
    [FX5__Work_End_Date__c]                   DATETIME2 (0)   NULL,
    [FX5__Work_Start_Date__c]                 DATETIME2 (0)   NULL,
    [Asset__c]                                NVARCHAR (18)   NULL,
    [Contact__c]                              NVARCHAR (225)  NULL,
    [County__c]                               NVARCHAR (3900) NULL,
    [Current_Date__c]                         DATETIME2 (0)   NULL,
    [Customer__c]                             NVARCHAR (3900) NULL,
    [Dispatcher__c]                           NVARCHAR (18)   NULL,
    [Disposal_Ticket__c]                      NVARCHAR (765)  NULL,
    [Geolocation_Accepted__c]                 BIT             NULL,
    [Geolocation_Available__c]                BIT             NULL,
    [Geolocation__Latitude__s]                DECIMAL (6, 3)  NULL,
    [Geolocation__Longitude__s]               DECIMAL (6, 3)  NULL,
    [Job_End_Date__c]                         DATETIME2 (0)   NULL,
    [Job_Start_Date__c]                       DATETIME2 (0)   NULL,
    [Key_Ticket_Number_Formatted__c]          NVARCHAR (60)   NULL,
    [Key_Ticket_Number__c]                    DECIMAL (18)    NULL,
    [Manual_Signature_or_Stamp_Accepted__c]   BIT             NULL,
    [Manual_Signature_or_Stamp__c]            BIT             NULL,
    [Marketplace__c]                          NVARCHAR (3900) NULL,
    [SWD_Type__c]                             NVARCHAR (765)  NULL,
    [SWD__c]                                  NVARCHAR (18)   NULL,
    [State__c]                                NVARCHAR (3900) NULL,
    [Status_Name__c]                          NVARCHAR (3900) NULL,
    [Well_Name__c]                            NVARCHAR (3900) NULL,
    [Work_Order__c]                           NVARCHAR (765)  NULL,
    [eSignature_Captured__c]                  BIT             NULL,
    [Ticket_Total__c]                         DECIMAL (18, 2) NULL,
    [Hub_Meter_Reading__c]                    DECIMAL (18)    NULL,
    [Ending_Hour_Meter_Reading__c]            DECIMAL (18)    NULL,
    [AFE_Requirements__c]                     NVARCHAR (150)  NULL,
    [Approver_Requirements__c]                NVARCHAR (150)  NULL,
    [Contract_Requirements__c]                NVARCHAR (150)  NULL,
    [Cost_Center_Requirements__c]             NVARCHAR (150)  NULL,
    [Feature_Code_Requirements__c]            NVARCHAR (150)  NULL,
    [General_Ledger_ID_Requirements__c]       NVARCHAR (150)  NULL,
    [Network_Activity_Requirements__c]        NVARCHAR (150)  NULL,
    [Other_EDI_Info_Requirements__c]          NVARCHAR (300)  NULL,
    [PO_Requirements__c]                      NVARCHAR (150)  NULL,
    [PO_Line_Requirements__c]                 NVARCHAR (150)  NULL,
    [Purchasing_Group_Requirements__c]        NVARCHAR (150)  NULL,
    [Requestor_Requirements__c]               NVARCHAR (150)  NULL,
    [Routing_Code_Requirements__c]            NVARCHAR (150)  NULL,
    [Work_Order_Requirements__c]              NVARCHAR (150)  NULL,
    [Provided_Requirements__c]                BIT             NULL,
    [Picture_Stamp__c]                        BIT             NULL,
    [API__c]                                  NVARCHAR (150)  NULL,
    [Alternate_Well_Name__c]                  NVARCHAR (150)  NULL,
    [Job_Type__c]                             NVARCHAR (18)   NULL,
    [Well_County__c]                          NVARCHAR (150)  NULL,
    [Well_Override__c]                        NVARCHAR (150)  NULL,
    [Well_State__c]                           NVARCHAR (6)    NULL,
    [Well__c]                                 NVARCHAR (18)   NULL,
    [Well_API__c]                             NVARCHAR (3900) NULL,
    [Billing_Category__c]                     NVARCHAR (150)  NULL,
    [Code_Requirements__c]                    NVARCHAR (150)  NULL,
    [Customer_Approver_Title__c]              NVARCHAR (150)  NULL,
    [Start_Time_old__c]                       NVARCHAR (24)   NULL,
    [Stop_Time_Old__c]                        NVARCHAR (24)   NULL,
    [Work_Description__c]                     NVARCHAR (MAX)  NULL,
    [Copy_Ticket__c]                          BIT             NULL,
    [Entered_in_KeyOps__c]                    BIT             NULL,
    [Job_Name__c]                             NVARCHAR (3900) NULL,
    [AltSync__c]                              BIT             NULL,
    [FX_Status_Text__c]                       NVARCHAR (765)  NULL,
    [Approval_Declined_Received_Date_Time__c] DATETIME2 (0)   NULL,
    [Approved_Declined_By_Email_Address__c]   NVARCHAR (240)  NULL,
    [Attachments_Exported__c]                 BIT             NULL,
    [Bottom_Gauge_1__c]                       DECIMAL (18, 1) NULL,
    [Bottom_Gauge_2__c]                       DECIMAL (18, 1) NULL,
    [Bottom_Gauge_3__c]                       DECIMAL (18, 1) NULL,
    [Bottom_Gauge_4__c]                       DECIMAL (18, 1) NULL,
    [Correction_Required__c]                  NVARCHAR (MAX)  NULL,
    [Customer_Email__c]                       NVARCHAR (240)  NULL,
    [Department__c]                           NVARCHAR (150)  NULL,
    [Email_Ticket_for_Approval__c]            BIT             NULL,
    [End_Mileage__c]                          DECIMAL (18)    NULL,
    [Exclude_Price_on_Ticket__c]              BIT             NULL,
    [Is_WC_Ticket__c]                         BIT             NULL,
    [Job_Class__c]                            NVARCHAR (765)  NULL,
    [Parent_Ticket__c]                        NVARCHAR (18)   NULL,
    [Plant_Code_Requirements__c]              NVARCHAR (150)  NULL,
    [Property_Name__c]                        NVARCHAR (150)  NULL,
    [SWD_Geolocation__Latitude__s]            DECIMAL (6, 3)  NULL,
    [SWD_Geolocation__Longitude__s]           DECIMAL (6, 3)  NULL,
    [Single_Day_Ticket__c]                    BIT             NULL,
    [Start_Mileage__c]                        DECIMAL (18)    NULL,
    [Start_Time__c]                           NVARCHAR (765)  NULL,
    [Stop_Time__c]                            NVARCHAR (765)  NULL,
    [Tank_No_1__c]                            NVARCHAR (60)   NULL,
    [Tank_No_2__c]                            NVARCHAR (60)   NULL,
    [Tank_No_3__c]                            NVARCHAR (60)   NULL,
    [Tank_No_4__c]                            NVARCHAR (60)   NULL,
    [Ticket_End_Date__c]                      DATETIME2 (0)   NULL,
    [Ticket_Number__c]                        NVARCHAR (3900) NULL,
    [Top_Gauge_1__c]                          DECIMAL (18, 1) NULL,
    [Top_Gauge_2__c]                          DECIMAL (18, 1) NULL,
    [Top_Gauge_3__c]                          DECIMAL (18, 1) NULL,
    [Top_Gauge_4__c]                          DECIMAL (18, 1) NULL,
    [Transfer_Ticket__c]                      BIT             NULL,
    [WBS_Element_Requirements__c]             NVARCHAR (150)  NULL,
    [Max_Ticket_Item_End_Date__c]             DATETIME2 (0)   NULL,
    [Max_Ticket_Item_Start_Date__c]           DATETIME2 (0)   NULL,
    [Ticket_Item_Count__c]                    DECIMAL (18)    NULL,
    [Ticket_Log_Count__c]                     DECIMAL (18)    NULL,
    [Bill_To_Site_Requirements__c]            NVARCHAR (240)  NULL,
    [Multi_Day_Ticket_Temp__c]                BIT             NULL,
    [No_Signature_Required__c]                BIT             NULL,
    [Well_Name_Report__c]                     NVARCHAR (3900) NULL,
    [Activity_Element_Requirements__c]        NVARCHAR (600)  NULL,
    [Customer_Approver_ID_Requirements__c]    NVARCHAR (600)  NULL,
    [Network_PM_Requirements__c]              NVARCHAR (600)  NULL,
    [Office_Loco__c]                          NVARCHAR (3900) NULL,
    [Asset_Number__c]                         NVARCHAR (3900) NULL,
    [Customer_Id__c]                          NVARCHAR (3900) NULL,
    [Email_Sent_Date_Time__c]                 DATETIME2 (0)   NULL,
    [Last_Email_Sent_Id__c]                   NVARCHAR (54)   NULL,
    [Job_Description__c]                      NVARCHAR (18)   NULL,
    [Required_Data__c]                        NVARCHAR (3900) NULL,
    [SWD2__c]                                 NVARCHAR (600)  NULL,
    [Swamper_Trainee__c]                      NVARCHAR (765)  NULL,
    [BBL_Log_Count__c]                        DECIMAL (18)    NULL,
    [Job_Employee_s__c]                       NVARCHAR (3900) NULL,
    [Pricing_Agreement__c]                    NVARCHAR (3900) NULL,
    [Reference__c]                            NVARCHAR (750)  NULL,
    [AccountTEST__c]                          NVARCHAR (18)   NULL,
    [Backup_2__c]                             NVARCHAR (MAX)  NULL,
    [Backup__c]                               NVARCHAR (MAX)  NULL,
    [Barcode__c]                              NVARCHAR (3900) NULL,
    [Bill_To_Parent__c]                       NVARCHAR (18)   NULL,
    [Billing_Validation__c]                   NVARCHAR (3900) NULL,
    [Capture_Picture_Stamp__c]                NVARCHAR (MAX)  NULL,
    [Customer_Approval_Email_Sent__c]         BIT             NULL,
    [Customer_ID_Text__c]                     NVARCHAR (150)  NULL,
    [Description__c]                          NVARCHAR (765)  NULL,
    [Draft__c]                                NVARCHAR (18)   NULL,
    [Final_Customer_Doc_Count__c]             DECIMAL (3)     NULL,
    [Grouping__c]                             NVARCHAR (765)  NULL,
    [Invoice__c]                              NVARCHAR (18)   NULL,
    [Job_Customer_Name__c]                    NVARCHAR (3900) NULL,
    [Office_LOB__c]                           NVARCHAR (3900) NULL,
    [OrgID__c]                                NVARCHAR (3900) NULL,
    [Preset_Descriptions__c]                  NVARCHAR (MAX)  NULL,
    [PricingWarningText__c]                   NVARCHAR (3900) NULL,
    [Rigs_Preset_Description__c]              NVARCHAR (MAX)  NULL,
    [ServiceTypeName__c]                      NVARCHAR (3900) NULL,
    [Service_Type__c]                         NVARCHAR (3900) NULL,
    [Ticket_Report__c]                        NVARCHAR (18)   NULL,
    [Total_Attachments__c]                    DECIMAL (18)    NULL,
    [EDIAFE__c]                               DECIMAL (18)    NULL,
    [EDICCenter__c]                           DECIMAL (18)    NULL,
    [EDINActivity__c]                         DECIMAL (18)    NULL,
    [EDIWBS__c]                               DECIMAL (18)    NULL,
    [Max_Stop_Time__c]                        DATETIME2 (0)   NULL,
    [Min_Start_Time__c]                       DATETIME2 (0)   NULL,
    [Conditional_Data__c]                     NVARCHAR (3900) NULL,
    [Scanned_Approved_Document__c]            BIT             NULL,
    [Audit_Completed__c]                      BIT             NULL,
    [Barcode64__c]                            NVARCHAR (MAX)  NULL,
    [User_Warning__c]                         NVARCHAR (3900) NULL,
    [EDI_Validation_count_on_Ticket_Item__c]  DECIMAL (18)    NULL,
    [Site__c]                                 NVARCHAR (3900) NULL,
    [Report_Bill_To_Site__c]                  BIT             NULL,
    [Count_Missing_BU__c]                     DECIMAL (18)    NULL,
    [Count_Missing_Level1__c]                 DECIMAL (18)    NULL,
    [Count_Missing_Level2__c]                 DECIMAL (18)    NULL,
    [Count_Missing_Location__c]               DECIMAL (18)    NULL,
    [Supervisor__c]                           NVARCHAR (18)   NULL,
    [Document_Extracted__c]                   BIT             NULL,
    [EFT_Error__c]                            NVARCHAR (765)  NULL,
    [Payroll_Verified__c]                     BIT             NULL,
    [DT__c]                                   NVARCHAR (60)   NULL,
    [Mobile_EDI_Validation_Count__c]          DECIMAL (18)    NULL,
    [TI_Payroll_Record_Count__c]              DECIMAL (18)    NULL,
    [Released__c]                             BIT             NULL,
    [AdminEmail__c]                           NVARCHAR (240)  NULL,
    [Admin_2_Email__c]                        NVARCHAR (240)  NULL,
    [Ops_Supervisor_Email2__c]                NVARCHAR (240)  NULL,
    [FX5__ReportSigned__c]                    DATETIME2 (0)   NULL,
    [FX5__StampCaptured__c]                   DATETIME2 (0)   NULL,
    [Min_Ticket_Item_Start_Date__c]           DATETIME2 (0)   NULL,
    [Rig__c]                                  NVARCHAR (750)  NULL,
    [Invoice_in_Progress__c]                  BIT             NULL,
    [Re_Send_Ticket_for_Approval__c]          BIT             NULL,
    [Manager_Approved_By__c]                  NVARCHAR (3900) NULL,
    [Manager_Approved__c]                     BIT             NULL,
    [EFT_Ticket_Type__c]                      NVARCHAR (765)  NULL,
    [EFT_Work_Description__c]                 NVARCHAR (MAX)  NULL,
    [Fluid_Hauled_Missing__c]                 DECIMAL (18)    NULL,
    [PY_Dates_Missing__c]                     DECIMAL (18)    NULL,
    [Children_Count__c]                       DECIMAL (18)    NULL,
    [Package_Count__c]                        DECIMAL (18)    NULL,
    [Void_Reason__c]                          NVARCHAR (MAX)  NULL,
    [UBill_Rollup__c]                         DECIMAL (18)    NULL,
    [Prior_Ticket_Number__c]                  NVARCHAR (765)  NULL,
    [Count_of_E_ENTER__c]                     DECIMAL (18)    NULL,
    [Ticket_Total_without_Parent__c]          DECIMAL (18, 2) NULL,
    [Ticket_Total_Difference__c]              DECIMAL (18, 2) NULL,
    [Manager_Approved_By_Hidden__c]           NVARCHAR (750)  NULL,
    [Supervisor_2__c]                         NVARCHAR (18)   NULL,
    [Driver__c]                               NVARCHAR (18)   NULL,
    [BBLs__c]                                 DECIMAL (18)    NULL,
    [ENTER_Codes_Util_Hrs__c]                 DECIMAL (18)    NULL,
    [Requested_Start_Time__c]                 DATETIME2 (0)   NULL,
    [Ticket_Time__c]                          DECIMAL (18, 2) NULL,
    [Dispatcher_Notes__c]                     NVARCHAR (765)  NULL,
    [WES_Ticket__c]                           BIT             NULL,
    [Rebuilt]                                 BIT             NULL,
    [Invoice_Name]                            NVARCHAR (64)   NULL,
    [Invoice_Number]                          NVARCHAR (64)   NULL,
    [Inserted]                                DATETIME2 (7)   NULL,
    [Updated]                                 DATETIME2 (7)   NULL,
    [Bid_Ticket_Type__c]                      NVARCHAR (256)  NULL,
    CONSTRAINT [PK_Salesforce_Tickets] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

ALTER TABLE [dbo].[Salesforce_Tickets]
    ADD CONSTRAINT [PK_Salesforce_Tickets] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

