CREATE TABLE [dbo].[Salesforce_Ticket_Item] (
    [Id]                                   NVARCHAR (18)   NOT NULL,
    [IsDeleted]                            BIT             NULL,
    [Name]                                 NVARCHAR (240)  NULL,
    [RecordTypeId]                         NVARCHAR (18)   NULL,
    [CreatedDate]                          DATETIME2 (0)   NULL,
    [CreatedById]                          NVARCHAR (18)   NULL,
    [LastModifiedDate]                     DATETIME2 (0)   NULL,
    [LastModifiedById]                     NVARCHAR (18)   NULL,
    [SystemModstamp]                       DATETIME2 (0)   NULL,
    [LastViewedDate]                       DATETIME2 (0)   NULL,
    [LastReferencedDate]                   DATETIME2 (0)   NULL,
    [FX5__Ticket__c]                       NVARCHAR (18)   NULL,
    [FX5__Auto_Added__c]                   BIT             NULL,
    [FX5__Breadcrumb__c]                   NVARCHAR (765)  NULL,
    [FX5__Catalog_Classification__c]       NVARCHAR (18)   NULL,
    [FX5__Catalog_Item__c]                 NVARCHAR (3900) NULL,
    [FX5__Catalog_Record_Type__c]          NVARCHAR (765)  NULL,
    [FX5__Catalog_Track_Inventory__c]      BIT             NULL,
    [FX5__Catalog_UOM__c]                  NVARCHAR (765)  NULL,
    [FX5__Contact__c]                      NVARCHAR (18)   NULL,
    [FX5__Cost_Plus_Markup_Amount__c]      DECIMAL (18, 2) NULL,
    [FX5__Cost_Plus_Markup_Percent__c]     DECIMAL (14, 2) NULL,
    [FX5__Cost__c]                         DECIMAL (18, 2) NULL,
    [FX5__Created_in_Mobile__c]            BIT             NULL,
    [FX5__Date_End__c]                     DATETIME2 (0)   NULL,
    [FX5__Date_Start__c]                   DATETIME2 (0)   NULL,
    [FX5__Description__c]                  NVARCHAR (765)  NULL,
    [FX5__Desired_Stage_Price__c]          DECIMAL (18, 2) NULL,
    [FX5__Discount_Percent__c]             DECIMAL (14, 2) NULL,
    [FX5__Equipment__c]                    NVARCHAR (18)   NULL,
    [FX5__Input_Qty__c]                    DECIMAL (18, 2) NULL,
    [FX5__Item_Code__c]                    NVARCHAR (765)  NULL,
    [FX5__On_Standby__c]                   BIT             NULL,
    [FX5__PBI_Default_Quantity__c]         DECIMAL (18, 2) NULL,
    [FX5__PBI_Enable_Dynamic_Parenting__c] BIT             NULL,
    [FX5__PBI_Included_Quantity__c]        DECIMAL (18, 2) NULL,
    [FX5__PBI_Locked_Description__c]       BIT             NULL,
    [FX5__PBI_Locked_Discount__c]          BIT             NULL,
    [FX5__PBI_Locked_Price_Markup__c]      BIT             NULL,
    [FX5__PBI_Maximum_Quantity__c]         DECIMAL (18, 2) NULL,
    [FX5__PBI_Minimum_Charge__c]           DECIMAL (18, 2) NULL,
    [FX5__PBI_Minimum_Quantity__c]         DECIMAL (18, 2) NULL,
    [FX5__PBI_Pricing_Method__c]           NVARCHAR (765)  NULL,
    [FX5__PBI_Required_Item__c]            BIT             NULL,
    [FX5__PBI_Requires_Parent_Item__c]     BIT             NULL,
    [FX5__PBI_Surcharge_Env__c]            BIT             NULL,
    [FX5__PBI_Surcharge_Fuel__c]           BIT             NULL,
    [FX5__Parent_Ticket_Item__c]           NVARCHAR (18)   NULL,
    [FX5__Price_Book_Item__c]              NVARCHAR (18)   NULL,
    [FX5__Price__c]                        DECIMAL (18, 2) NULL,
    [FX5__Quote_Item__c]                   NVARCHAR (18)   NULL,
    [FX5__Rule_Required_Item__c]           BIT             NULL,
    [FX5__Sequence_Number__c]              DECIMAL (16, 4) NULL,
    [FX5__Standby_Price__c]                DECIMAL (18, 2) NULL,
    [FX5__Surcharge_Rate_Env__c]           DECIMAL (14, 2) NULL,
    [FX5__Surcharge_Rate_Fuel__c]          DECIMAL (14, 2) NULL,
    [FX5__SyncID__c]                       NVARCHAR (150)  NULL,
    [FX5__Unstaged_Total_Price__c]         DECIMAL (18, 2) NULL,
    [FX5__Warehouse__c]                    NVARCHAR (18)   NULL,
    [Additional_Description__c]            NVARCHAR (765)  NULL,
    [Service_Type__c]                      NVARCHAR (150)  NULL,
    [Asset_Number__c]                      NVARCHAR (3900) NULL,
    [Asset__c]                             NVARCHAR (3900) NULL,
    [Billable_Hours__c]                    DECIMAL (18, 2) NULL,
    [Calc_Qty__c]                          DECIMAL (18, 2) NULL,
    [CatItem_ID__c]                        NVARCHAR (180)  NULL,
    [Customer_Price__c]                    DECIMAL (18, 2) NULL,
    [Customer_Unit_Price__c]               DECIMAL (18, 2) NULL,
    [Discount__c]                          DECIMAL (18, 2) NULL,
    [Discounted_Price__c]                  DECIMAL (18, 2) NULL,
    [Employee_Number__c]                   NVARCHAR (3900) NULL,
    [End_Date__c]                          DATETIME2 (0)   NULL,
    [Extended_Amount_Hidden__c]            DECIMAL (18, 2) NULL,
    [Extended_Amount__c]                   DECIMAL (18, 2) NULL,
    [Income_Code__c]                       NVARCHAR (765)  NULL,
    [Item_Code_Description__c]             NVARCHAR (3900) NULL,
    [Line_Asset_Number__c]                 NVARCHAR (3900) NULL,
    [List__c]                              DECIMAL (18, 2) NULL,
    [Long_Disc__c]                         DECIMAL (18, 6) NULL,
    [NB_Travel__c]                         DECIMAL (18)    NULL,
    [Payroll_Record__c]                    NVARCHAR (3900) NULL,
    [Qty__c]                               DECIMAL (18, 2) NULL,
    [Reason_for_Yard_Time__c]              NVARCHAR (765)  NULL,
    [Regular__c]                           DECIMAL (18, 2) NULL,
    [Repair_Maintenance__c]                DECIMAL (18, 2) NULL,
    [Start_Date__c]                        DATETIME2 (0)   NULL,
    [Ticket_Item_Lookup__c]                NVARCHAR (18)   NULL,
    [Ticket_Payroll_Lookup__c]             NVARCHAR (18)   NULL,
    [Ticket_Record_Type__c]                NVARCHAR (3900) NULL,
    [Title__c]                             NVARCHAR (3900) NULL,
    [Total_Hours_Entered__c]               DECIMAL (18, 2) NULL,
    [Total_Hours_Labor__c]                 DECIMAL (18, 2) NULL,
    [Training_Safety__c]                   DECIMAL (18, 2) NULL,
    [Training__c]                          DECIMAL (18, 2) NULL,
    [Travel__c]                            DECIMAL (18, 2) NULL,
    [Yard_Time__c]                         DECIMAL (18, 2) NULL,
    [Override_Emp_Name__c]                 NVARCHAR (150)  NULL,
    [Override_Emp__c]                      NVARCHAR (27)   NULL,
    [AFE_Requirements__c]                  NVARCHAR (150)  NULL,
    [Addl_Desc_Formula__c]                 NVARCHAR (3900) NULL,
    [AltSync__c]                           BIT             NULL,
    [Alternate_Job_Performed__c]           NVARCHAR (150)  NULL,
    [Cost_Center_Requirements__c]          NVARCHAR (150)  NULL,
    [Edit_Price_Flag__c]                   BIT             NULL,
    [Editable_Price__c]                    BIT             NULL,
    [Entry_Date_Time__c]                   DATETIME2 (0)   NULL,
    [Equipment_Record__c]                  NVARCHAR (3900) NULL,
    [Is_National_Price_Book_Item__c]       BIT             NULL,
    [Item_Record_Type__c]                  NVARCHAR (765)  NULL,
    [KES_ID_Requirements__c]               NVARCHAR (150)  NULL,
    [Network_Activity_Requirements__c]     NVARCHAR (150)  NULL,
    [PO_Line_Requirements__c]              NVARCHAR (15)   NULL,
    [Parent_Item_Record_Type__c]           NVARCHAR (765)  NULL,
    [Payroll_Group__c]                     NVARCHAR (3900) NULL,
    [Price_POR__c]                         DECIMAL (18, 2) NULL,
    [FX5__COGS_Account__c]                 NVARCHAR (18)   NULL,
    [Services_Record__c]                   NVARCHAR (3900) NULL,
    [Start_Date_TI__c]                     DATETIME2 (0)   NULL,
    [Target_For_Min_Max_Date_Rollup__c]    BIT             NULL,
    [WBS_Element_Requirements__c]          NVARCHAR (150)  NULL,
    [FX5__Income_Account__c]               NVARCHAR (18)   NULL,
    [Ticket_Equipment_Lookup__c]           NVARCHAR (18)   NULL,
    [Cost_Center_Report_Name__c]           NVARCHAR (3900) NULL,
    [WBS_Element_Report_Name__c]           NVARCHAR (3900) NULL,
    [Parent_Sync_Id__c]                    NVARCHAR (3900) NULL,
    [Package_Record__c]                    NVARCHAR (3900) NULL,
    [FX5__Invoice_Item__c]                 NVARCHAR (18)   NULL,
    [Asset_Description__c]                 NVARCHAR (3900) NULL,
    [FX5__AllowOverride__c]                BIT             NULL,
    [FX5__CustomerAccount__c]              NVARCHAR (3900) NULL,
    [FX5__Job__c]                          NVARCHAR (18)   NULL,
    [FX5__Office__c]                       NVARCHAR (3900) NULL,
    [FX5__Override__c]                     NVARCHAR (18)   NULL,
    [FX5__PBI_Override_Cost_Method__c]     NVARCHAR (18)   NULL,
    [FX5__PBI_Override_Price_Method__c]    NVARCHAR (18)   NULL,
    [AOCheck__c]                           BIT             NULL,
    [Asset_Utilization_Hours__c]           DECIMAL (18, 2) NULL,
    [Business_Unit__c]                     NVARCHAR (765)  NULL,
    [Children_Revenue_Total_Sum__c]        DECIMAL (18, 2) NULL,
    [EDICheck__c]                          NVARCHAR (3900) NULL,
    [FX_Maintenance_Date__c]               DATETIME2 (0)   NULL,
    [LCO__c]                               NVARCHAR (12)   NULL,
    [Level_1__c]                           NVARCHAR (12)   NULL,
    [Level_2__c]                           NVARCHAR (12)   NULL,
    [Original_Qty__c]                      DECIMAL (18, 2) NULL,
    [Revenue_Allocation__c]                DECIMAL (18, 2) NULL,
    [Revenue_Factor__c]                    DECIMAL (18, 2) NULL,
    [Revenue_Total_Hidden__c]              DECIMAL (18, 2) NULL,
    [Revenue_Total__c]                     DECIMAL (18, 2) NULL,
    [Vanity_Code__c]                       NVARCHAR (60)   NULL,
    [Vanity_Description__c]                NVARCHAR (300)  NULL,
    [Exclude_from_Invoice__c]              BIT             NULL,
    [EDI_Validation__c]                    BIT             NULL,
    [Required_Data__c]                     NVARCHAR (3900) NULL,
    [Required_EDI_Data__c]                 NVARCHAR (3900) NULL,
    [Rev_Total_Rev_Total_Hidden__c]        BIT             NULL,
    [Ticket_Date__c]                       DATETIME2 (0)   NULL,
    [EmployeeReport__c]                    BIT             NULL,
    [IsReadOnlyOnConsole__c]               BIT             NULL,
    [RTMS_Item__c]                         NVARCHAR (3900) NULL,
    [FX5__Rule_Action__c]                  NVARCHAR (18)   NULL,
    [Price_Data_Grid__c]                   DECIMAL (18, 2) NULL,
    [Asset2__c]                            NVARCHAR (3900) NULL,
    [Service_Date2__c]                     DATETIME2 (0)   NULL,
    [Service_Location__c]                  NVARCHAR (3900) NULL,
    [Ticket_Number2__c]                    NVARCHAR (3900) NULL,
    [Sum_of_Actual_Child_Amount__c]        DECIMAL (18)    NULL,
    [Type__c]                              NVARCHAR (3900) NULL,
    [EFT_Item__c]                          DECIMAL (18)    NULL,
    [Fluid_Hauled_Missing__c]              BIT             NULL,
    [Fluid_Hauled__c]                      NVARCHAR (765)  NULL,
    [PY_Dates_Missing__c]                  BIT             NULL,
    [UBill__c]                             DECIMAL (7, 2)  NULL,
    [LEM_Type__c]                          NVARCHAR (3900) NULL,
    [Catalog_Required_Manual_Entry__c]     BIT             NULL,
    [Catalog_UBill_Description__c]         NVARCHAR (600)  NULL,
    [Cloned_Ticket_Item__c]                NVARCHAR (765)  NULL,
    [Child_Item_Count__c]                  DECIMAL (18, 2) NULL,
    [Sum_of_Child_Item_Count__c]           DECIMAL (18)    NULL,
    [Employee_Name_Report__c]              NVARCHAR (3900) NULL,
    [Employee_Number_Report__c]            NVARCHAR (3900) NULL,
    [Employee_Role_Report__c]              NVARCHAR (3900) NULL,
    [Ticket_Status__c]                     NVARCHAR (3900) NULL
);
GO

ALTER TABLE [dbo].[Salesforce_Ticket_Item]
    ADD CONSTRAINT [PK_Salesforce_Ticket_Item] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

