CREATE TABLE [dbo].[Salesforce_Account] (
    [Id]                                        NVARCHAR (18)    NOT NULL,
    [IsDeleted]                                 NVARCHAR (5)     NULL,
    [MasterRecordId]                            NVARCHAR (50)    NULL,
    [Name]                                      NVARCHAR (MAX)   NULL,
    [Type]                                      NVARCHAR (40)    NULL,
    [RecordTypeId]                              NVARCHAR (18)    NULL,
    [ParentId]                                  NVARCHAR (18)    NULL,
    [BillingStreet]                             NVARCHAR (255)   NULL,
    [BillingCity]                               NVARCHAR (120)   NULL,
    [BillingState]                              NVARCHAR (240)   NULL,
    [BillingPostalCode]                         NVARCHAR (20)    NULL,
    [BillingCountry]                            NVARCHAR (80)    NULL,
    [BillingLatitude]                           NUMERIC (18, 15) NULL,
    [BillingLongitude]                          NUMERIC (18, 15) NULL,
    [BillingGeocodeAccuracy]                    NVARCHAR (20)    NULL,
    [BillingAddress]                            NVARCHAR (MAX)   NULL,
    [ShippingStreet]                            NVARCHAR (255)   NULL,
    [ShippingCity]                              NVARCHAR (120)   NULL,
    [ShippingState]                             NVARCHAR (240)   NULL,
    [ShippingPostalCode]                        NVARCHAR (20)    NULL,
    [ShippingCountry]                           NVARCHAR (80)    NULL,
    [ShippingLatitude]                          NUMERIC (18, 15) NULL,
    [ShippingLongitude]                         NUMERIC (18, 15) NULL,
    [ShippingGeocodeAccuracy]                   NVARCHAR (20)    NULL,
    [ShippingAddress]                           NVARCHAR (MAX)   NULL,
    [Phone]                                     NVARCHAR (120)   NULL,
    [Fax]                                       NVARCHAR (40)    NULL,
    [AccountNumber]                             NVARCHAR (120)   NULL,
    [Website]                                   NVARCHAR (255)   NULL,
    [PhotoUrl]                                  NVARCHAR (255)   NULL,
    [Sic]                                       NVARCHAR (20)    NULL,
    [Industry]                                  NVARCHAR (255)   NULL,
    [AnnualRevenue]                             DECIMAL (18)     NULL,
    [NumberOfEmployees]                         INT              NULL,
    [Ownership]                                 NVARCHAR (255)   NULL,
    [TickerSymbol]                              NVARCHAR (20)    NULL,
    [Description]                               NVARCHAR (MAX)   NULL,
    [Rating]                                    NVARCHAR (255)   NULL,
    [Site]                                      NVARCHAR (80)    NULL,
    [OwnerId]                                   NVARCHAR (18)    NULL,
    [CreatedDate]                               DATETIME2 (0)    NULL,
    [CreatedById]                               NVARCHAR (18)    NULL,
    [LastModifiedDate]                          DATETIME2 (0)    NULL,
    [LastModifiedById]                          NVARCHAR (18)    NULL,
    [SystemModstamp]                            DATETIME2 (0)    NULL,
    [LastActivityDate]                          DATETIME2 (0)    NULL,
    [LastViewedDate]                            DATETIME2 (0)    NULL,
    [LastReferencedDate]                        DATETIME2 (0)    NULL,
    [Jigsaw]                                    NVARCHAR (20)    NULL,
    [JigsawCompanyId]                           NVARCHAR (20)    NULL,
    [AccountSource]                             NVARCHAR (255)   NULL,
    [SicDesc]                                   NVARCHAR (80)    NULL,
    [Also_Known_As__c]                          NVARCHAR (255)   NULL,
    [Managed_Account__c]                        NVARCHAR (5)     NULL,
    [ISNet_World__c]                            NVARCHAR (30)    NULL,
    [KeyOps_Customer_Number__c]                 NVARCHAR (10)    NULL,
    [Central__c]                                NVARCHAR (5)     NULL,
    [Relationship_Grade__c]                     NVARCHAR (255)   NULL,
    [AccountMarketplace__c]                     NVARCHAR (18)    NULL,
    [Offshore__c]                               NVARCHAR (5)     NULL,
    [Gulf_Coast__c]                             NVARCHAR (5)     NULL,
    [Mexico__c]                                 NVARCHAR (5)     NULL,
    [Northeast__c]                              NVARCHAR (5)     NULL,
    [Permian_Basin__c]                          NVARCHAR (5)     NULL,
    [Rocky_Mountains__c]                        NVARCHAR (5)     NULL,
    [West_Coast__c]                             NVARCHAR (5)     NULL,
    [Convert_to_Customer__c]                    NVARCHAR (5)     NULL,
    [Current_User_Account_Owner__c]             NVARCHAR (5)     NULL,
    [Marketing_Use__c]                          NVARCHAR (MAX)   NULL,
    [Opportunities_Created__c]                  DECIMAL (18)     NULL,
    [Account_Short_Name__c]                     NVARCHAR (40)    NULL,
    [FX5__IsArchived__c ]                       NVARCHAR (5)     NULL,
    [FX5__Sync_to_Mobile__c ]                   NVARCHAR (5)     NULL,
    [Active_Location__c ]                       NVARCHAR (5)     NULL,
    [Address__c]                                NVARCHAR (100)   NULL,
    [Business_Development__c ]                  NVARCHAR (5)     NULL,
    [City__c ]                                  NVARCHAR (50)    NULL,
    [District_Code__c ]                         NVARCHAR (10)    NULL,
    [MDM_ROW_ID__c ]                            NVARCHAR (50)    NULL,
    [AltSync__c ]                               NVARCHAR (5)     NULL,
    [Associated_Platinum_Sheet__c ]             NVARCHAR (5)     NULL,
    [LCO_Code__c ]                              NVARCHAR (20)    NULL,
    [Location_Phone__c ]                        NVARCHAR (40)    NULL,
    [State__c ]                                 NVARCHAR (50)    NULL,
    [Zip_Code__c ]                              NVARCHAR (10)    NULL,
    [Location__Latitude__s]                     NUMERIC (10, 7)  NULL,
    [Location__Longitude__s]                    NUMERIC (10, 7)  NULL,
    [Location__c]                               NVARCHAR (50)    NULL,
    [County__c]                                 NVARCHAR (50)    NULL,
    [AFE_Requirements__c]                       NVARCHAR (255)   NULL,
    [Account_Num__c]                            NVARCHAR (40)    NULL,
    [Approver_Requirements__c]                  NVARCHAR (255)   NULL,
    [Billing_Requirement_Exists__c]             NVARCHAR (5)     NULL,
    [Contract_Requirements__c]                  NVARCHAR (255)   NULL,
    [Cost_Center_Requirements__c]               NVARCHAR (255)   NULL,
    [EDI_Invoice_Description_Requirements__c]   NVARCHAR (255)   NULL,
    [Feature_Code_Requirements__c]              NVARCHAR (255)   NULL,
    [General_Ledger_ID_Requirements__c]         NVARCHAR (255)   NULL,
    [Geolocation_Accepted__c]                   NVARCHAR (5)     NULL,
    [Manual_Signature_or_Stamp_Accepted__c]     NVARCHAR (5)     NULL,
    [Network_Activity_Requirements__c]          NVARCHAR (255)   NULL,
    [PO_Line_Requirements__c]                   NVARCHAR (255)   NULL,
    [PO_Requirements__c]                        NVARCHAR (255)   NULL,
    [Parent_Account_Id__c]                      NVARCHAR (20)    NULL,
    [Parent_Id__c]                              NVARCHAR (MAX)   NULL,
    [Purchasing_Group_Requirements__c]          NVARCHAR (255)   NULL,
    [Record_Type_Name__c]                       NVARCHAR (MAX)   NULL,
    [Requestor_Requirements__c]                 NVARCHAR (255)   NULL,
    [Routing_Code_Requirements__c]              NVARCHAR (255)   NULL,
    [Work_Order_Requirements__c]                NVARCHAR (255)   NULL,
    [Status__c]                                 NVARCHAR (255)   NULL,
    [District_Manager__c]                       NVARCHAR (18)    NULL,
    [LOB__c]                                    NVARCHAR (18)    NULL,
    [Marketplace__c]                            NVARCHAR (18)    NULL,
    [Additional_Description_TI_Requirements__c] NVARCHAR (255)   NULL,
    [Cost_Center_TI_Requirements__c]            NVARCHAR (255)   NULL,
    [Exclude_WC_Pricing_on_Ticket__c]           NVARCHAR (5)     NULL,
    [KES_ID_TI_Requirements__c]                 NVARCHAR (255)   NULL,
    [LOB_Name__c]                               NVARCHAR (255)   NULL,
    [Do_Not_Allow_Quotes__c]                    NVARCHAR (5)     NULL,
    [Network_Activity_TI_Requirements__c]       NVARCHAR (255)   NULL,
    [Plant_Code_Requirements__c]                NVARCHAR (255)   NULL,
    [WBS_Element_Requirements__c]               NVARCHAR (255)   NULL,
    [WBS_Element_TI_Requirements__c]            NVARCHAR (255)   NULL,
    [My_Id__c]                                  NVARCHAR (30)    NULL,
    [AFE_TI_Requirements__c]                    NVARCHAR (255)   NULL,
    [Bill_To_Site_Requirements__c]              NVARCHAR (255)   NULL,
    [Marketplace_Name__c]                       NVARCHAR (255)   NULL,
    [Activity_Element_Requirements__c]          NVARCHAR (255)   NULL,
    [Approver_ID_Requirements__c]               NVARCHAR (255)   NULL,
    [Network_PM_Requirements__c]                NVARCHAR (255)   NULL,
    [Contract_Customer__c]                      NVARCHAR (5)     NULL,
    [FX5__AR_Account__c]                        NVARCHAR (18)    NULL,
    [Auto_Add_Creator_to_Job_Crew__c]           NVARCHAR (5)     NULL,
    [Customer_Jobs__c]                          NUMERIC (18)     NULL,
    [Active_MSA__c]                             NVARCHAR (5)     NULL,
    [Available_Credit__c]                       NUMERIC (18)     NULL,
    [Business_Unit__c]                          NVARCHAR (10)    NULL,
    [Draft__c]                                  NVARCHAR (5)     NULL,
    [Grouping__c]                               NVARCHAR (255)   NULL,
    [Job_Increment__c]                          NUMERIC (18)     NULL,
    [Job_Type__c]                               NVARCHAR (18)    NULL,
    [Terms__c]                                  NVARCHAR (255)   NULL,
    [Customer_Reference__c]                     NVARCHAR (100)   NULL,
    [Admin_2__c]                                NVARCHAR (18)    NULL,
    [Admin__c]                                  NVARCHAR (18)    NULL,
    [Ops_Supervisor__c]                         NVARCHAR (18)    NULL,
    [FX5__Active__c]                            NVARCHAR (255)   NULL,
    [FX5__CustomerPriority__c]                  NVARCHAR (255)   NULL,
    [FX5__NumberofLocations__c]                 NUMERIC (3)      NULL,
    [FX5__SLAExpirationDate__c]                 DATETIME2 (0)    NULL,
    [FX5__SLASerialNumber__c]                   NVARCHAR (10)    NULL,
    [FX5__SLA__c]                               NVARCHAR (255)   NULL,
    [FX5__UpsellOpportunity__c]                 NVARCHAR (255)   NULL,
    [EFT_Customer__c]                           NVARCHAR (5)     NULL,
    [Available_Balance__c]                      NUMERIC (18, 2)  NULL,
    [Billing_Type__c]                           NVARCHAR (255)   NULL,
    [Open_Non_invoiced_Ticket_Balance__c]       NUMERIC (18, 2)  NULL
);
GO

ALTER TABLE [dbo].[Salesforce_Account]
    ADD CONSTRAINT [PK_Salesforce_Account] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

