CREATE TABLE [dbo].[Salesforce_Jobs] (
    [Id]                                      NVARCHAR (18)   NOT NULL,
    [OwnerId]                                 NVARCHAR (18)   NULL,
    [IsDeleted]                               BIT             NULL,
    [Name]                                    NVARCHAR (240)  NULL,
    [RecordTypeId]                            NVARCHAR (18)   NULL,
    [CreatedDate]                             DATETIME2 (0)   NULL,
    [CreatedById]                             NVARCHAR (18)   NULL,
    [LastModifiedDate]                        DATETIME2 (0)   NULL,
    [LastModifiedById]                        NVARCHAR (18)   NULL,
    [SystemModstamp]                          DATETIME2 (0)   NULL,
    [LastActivityDate]                        DATETIME2 (0)   NULL,
    [LastViewedDate]                          DATETIME2 (0)   NULL,
    [LastReferencedDate]                      DATETIME2 (0)   NULL,
    [FX5__AFE_Number__c]                      NVARCHAR (765)  NULL,
    [FX5__Actual_End_Date__c]                 DATETIME2 (0)   NULL,
    [FX5__Actual_Start_Date__c]               DATETIME2 (0)   NULL,
    [FX5__Category__c]                        NVARCHAR (765)  NULL,
    [FX5__Contact_Name__c]                    NVARCHAR (300)  NULL,
    [FX5__Contact_Phone__c]                   NVARCHAR (150)  NULL,
    [FX5__Created_in_Mobile__c]               BIT             NULL,
    [FX5__CustomerAccount__c]                 NVARCHAR (18)   NULL,
    [FX5__Customer_PO_Amount__c]              DECIMAL (18, 2) NULL,
    [FX5__Customer_PO__c]                     NVARCHAR (150)  NULL,
    [FX5__Directions__c]                      NVARCHAR (MAX)  NULL,
    [FX5__Job_Number__c]                      NVARCHAR (765)  NULL,
    [FX5__Notes__c]                           NVARCHAR (MAX)  NULL,
    [FX5__Office__c]                          NVARCHAR (18)   NULL,
    [FX5__Price_Book__c]                      NVARCHAR (18)   NULL,
    [FX5__Primary_Job_Contact__c]             NVARCHAR (18)   NULL,
    [FX5__Priority__c]                        NVARCHAR (765)  NULL,
    [FX5__Projected_End_Date__c]              DATETIME2 (0)   NULL,
    [FX5__Projected_Start_Date__c]            DATETIME2 (0)   NULL,
    [FX5__Quote2__c]                          NVARCHAR (18)   NULL,
    [Open_Ticket_Count__c]                    DECIMAL (18)    NULL,
    [FX5__Requested_Start_Date__c]            DATETIME2 (0)   NULL,
    [FX5__Segment__c]                         NVARCHAR (765)  NULL,
    [FX5__Site_Address1__c]                   NVARCHAR (300)  NULL,
    [FX5__Site_Address_2__c]                  NVARCHAR (300)  NULL,
    [FX5__Site_Arrival_Date__c]               DATETIME2 (0)   NULL,
    [FX5__Site_City__c]                       NVARCHAR (300)  NULL,
    [FX5__Site_Country__c]                    NVARCHAR (765)  NULL,
    [FX5__Site_Departure_Date__c]             DATETIME2 (0)   NULL,
    [FX5__Site_Latitude__c]                   DECIMAL (9, 6)  NULL,
    [FX5__Site_Longitude__c]                  DECIMAL (9, 6)  NULL,
    [FX5__Site_State__c]                      NVARCHAR (765)  NULL,
    [FX5__Site_Zip__c]                        NVARCHAR (60)   NULL,
    [FX5__Status__c]                          NVARCHAR (18)   NULL,
    [FX5__SyncID__c]                          NVARCHAR (150)  NULL,
    [FX5__Sync__c]                            BIT             NULL,
    [FX5__Tracking_Number__c]                 NVARCHAR (150)  NULL,
    [FX5__Warehouse__c]                       NVARCHAR (18)   NULL,
    [FX5__Well__c]                            NVARCHAR (18)   NULL,
    [API__c]                                  NVARCHAR (300)  NULL,
    [Customer_Formula__c]                     NVARCHAR (3900) NULL,
    [Customer_Override__c]                    NVARCHAR (150)  NULL,
    [Open_Ticket_Count_Roll_Up__c]            DECIMAL (18)    NULL,
    [Job_Type__c]                             NVARCHAR (18)   NULL,
    [LOCO__c]                                 NVARCHAR (3900) NULL,
    [Status_Name__c]                          NVARCHAR (3900) NULL,
    [Well_County__c]                          NVARCHAR (300)  NULL,
    [Well_Formula__c]                         NVARCHAR (3900) NULL,
    [Well_Override__c]                        NVARCHAR (150)  NULL,
    [Well_State__c]                           NVARCHAR (6)    NULL,
    [Job_Total__c]                            DECIMAL (18, 2) NULL,
    [AltSync__c]                              BIT             NULL,
    [Enable_Extended_Pricing__c]              BIT             NULL,
    [FX_Share_Assign_Related__c]              BIT             NULL,
    [FX_Status_Text__c]                       NVARCHAR (765)  NULL,
    [Well_County2__c]                         NVARCHAR (18)   NULL,
    [Well_State2__c]                          NVARCHAR (765)  NULL,
    [Alternate_Well_Name__c]                  NVARCHAR (600)  NULL,
    [Catch_All_Percentage__c]                 DECIMAL (18, 2) NULL,
    [LOB__c]                                  NVARCHAR (3900) NULL,
    [Market_Place__c]                         NVARCHAR (3900) NULL,
    [County__c]                               NVARCHAR (3900) NULL,
    [State__c]                                NVARCHAR (3900) NULL,
    [Well_Name__c]                            NVARCHAR (3900) NULL,
    [Well_API__c]                             NVARCHAR (3900) NULL,
    [Current_Date__c]                         DATETIME2 (0)   NULL,
    [Exclude_Price_on_Reports__c]             BIT             NULL,
    [Job_Crew_Members__c]                     NVARCHAR (750)  NULL,
    [Count_of_Non_Voided_Tickets__c]          DECIMAL (18)    NULL,
    [Last_Ticket_Date__c]                     DATETIME2 (0)   NULL,
    [AutoNamed__c]                            BIT             NULL,
    [Available_Pricing_Agreements2__c]        NVARCHAR (MAX)  NULL,
    [Available_Pricing_Agreements__c]         DECIMAL (18)    NULL,
    [Bottom_Hole_PSI__c]                      NVARCHAR (750)  NULL,
    [Casing_ID__c]                            NVARCHAR (765)  NULL,
    [Casing_Size__c]                          NVARCHAR (765)  NULL,
    [Casing_Weight__c]                        NVARCHAR (765)  NULL,
    [Coil_Tubing_Size__c]                     NVARCHAR (765)  NULL,
    [Crew_Planning_Total__c]                  DECIMAL (18)    NULL,
    [Equipment_Planning_Total__c]             DECIMAL (18)    NULL,
    [LOB_Name__c]                             NVARCHAR (3900) NULL,
    [Office2__c]                              NVARCHAR (3900) NULL,
    [StatusCheck__c]                          NVARCHAR (3900) NULL,
    [Tree_Connection_Pressure__c]             NVARCHAR (750)  NULL,
    [Tree_Connection_Size__c]                 NVARCHAR (750)  NULL,
    [Well_KOP__c]                             NVARCHAR (750)  NULL,
    [Well_PBTD__c]                            NVARCHAR (750)  NULL,
    [Well_TVD__c]                             NVARCHAR (750)  NULL,
    [Wellhead_PSI__c]                         NVARCHAR (750)  NULL,
    [Requested_Date_Time__c]                  DATETIME2 (0)   NULL,
    [CPA_Override__c]                         BIT             NULL,
    [Credit_and_Contract_Status__c]           NVARCHAR (765)  NULL,
    [Days_Since_Last_Ticket__c]               DECIMAL (18)    NULL,
    [JobURL__c]                               NVARCHAR (MAX)  NULL,
    [Next_Recurring_Time__c]                  DATETIME2 (0)   NULL,
    [OfficeServiceType__c]                    NVARCHAR (3900) NULL,
    [RecurringNow__c]                         BIT             NULL,
    [Recurring_End_Date__c]                   DATETIME2 (0)   NULL,
    [Recurring_Interval__c]                   DECIMAL (18)    NULL,
    [Recurring_Job_Tracking_Number__c]        NVARCHAR (3900) NULL,
    [Recurring_Job__c]                        NVARCHAR (18)   NULL,
    [Recurring_Last_Result_Error_Occurred__c] BIT             NULL,
    [Recurring_Last_Result__c]                NVARCHAR (MAX)  NULL,
    [Recurring_Source__c]                     NVARCHAR (18)   NULL,
    [Recurring_Time__c]                       DATETIME2 (0)   NULL,
    [Recurring__c]                            BIT             NULL,
    [Bill_To__c]                              NVARCHAR (18)   NULL,
    [Grouping__c]                             NVARCHAR (765)  NULL,
    [Approval__c]                             NVARCHAR (765)  NULL,
    [Credit_Limit__c]                         DECIMAL (18, 2) NULL,
    [EmailSent__c]                            BIT             NULL,
    [Expiration_Date__c]                      DATETIME2 (0)   NULL,
    [Invoiced_Tickets__c]                     DECIMAL (18)    NULL,
    [Ticket_Total__c]                         DECIMAL (18, 2) NULL,
    [FX5__Price_Book_2__c]                    NVARCHAR (18)   NULL,
    [FX5__Price_Book_3__c]                    NVARCHAR (18)   NULL,
    [AFE_Requirements__c]                     NVARCHAR (150)  NULL,
    [Approver_Requirements__c]                NVARCHAR (150)  NULL,
    [Asset__c]                                NVARCHAR (18)   NULL,
    [Conditional_Data__c]                     NVARCHAR (3900) NULL,
    [Contract_Requirements__c]                NVARCHAR (150)  NULL,
    [Cost_Center_Requirements__c]             NVARCHAR (150)  NULL,
    [Feature_Code_Requirements__c]            NVARCHAR (150)  NULL,
    [General_Ledger_ID_Requirements__c]       NVARCHAR (150)  NULL,
    [Network_Activity_Requirements__c]        NVARCHAR (150)  NULL,
    [Other_EDI_Info_Requirements__c]          NVARCHAR (300)  NULL,
    [PO_Requirements__c]                      NVARCHAR (150)  NULL,
    [Plant_Code_Requirements__c]              NVARCHAR (150)  NULL,
    [Purchasing_Group_Requirements__c]        NVARCHAR (150)  NULL,
    [Requestor_Requirements__c]               NVARCHAR (150)  NULL,
    [Required_Data__c]                        NVARCHAR (3900) NULL,
    [Routing_Code_Requirements__c]            NVARCHAR (150)  NULL,
    [WBS_Element_Requirements__c]             NVARCHAR (150)  NULL,
    [Work_Order_Requirements__c]              NVARCHAR (150)  NULL,
    [Invoiced_or_Drafted_Tickets_Count__c]    DECIMAL (18)    NULL,
    [Job_Class__c]                            NVARCHAR (765)  NULL,
    [Inserted]                                DATETIME2 (7)   NULL,
    [Updated]                                 DATETIME2 (7)   NULL,
    [Invoice_Id]                              NVARCHAR (18)   NULL,
    [Invoice_Name]                            NVARCHAR (64)   NULL,
    [Invoice_Number]                          NVARCHAR (64)   NULL
);
GO

ALTER TABLE [dbo].[Salesforce_Jobs]
    ADD CONSTRAINT [PK_Salesforce_Jobs] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

