CREATE TABLE [dbo].[Salesforce_Invoice] (
    [Id]                                  NVARCHAR (18)   NOT NULL,
    [OwnerId]                             NVARCHAR (18)   NULL,
    [IsDeleted]                           BIT             NULL,
    [Name]                                NVARCHAR (240)  NULL,
    [RecordTypeId]                        NVARCHAR (18)   NULL,
    [CreatedDate]                         DATETIME2 (0)   NULL,
    [CreatedById]                         NVARCHAR (18)   NULL,
    [CreatedByUsername]                   NVARCHAR (50)   NULL,
    [LastModifiedDate]                    DATETIME2 (0)   NULL,
    [LastModifiedById]                    NVARCHAR (18)   NULL,
    [LastModifiedUsername]                NVARCHAR (50)   NULL,
    [SystemModstamp]                      DATETIME2 (0)   NULL,
    [LastActivityDate]                    DATETIME2 (0)   NULL,
    [LastViewedDate]                      DATETIME2 (0)   NULL,
    [LastReferencedDate]                  DATETIME2 (0)   NULL,
    [FX5__Balance_Due__c]                 DECIMAL (18, 2) NULL,
    [FX5__CustomerAccount__c]             NVARCHAR (18)   NULL,
    [FX5__Due_Date__c]                    DATETIME2 (0)   NULL,
    [FX5__Invoice_Date__c]                DATETIME2 (0)   NULL,
    [FX5__Office__c]                      NVARCHAR (18)   NULL,
    [FX5__Payment_Terms__c]               NVARCHAR (765)  NULL,
    [FX5__Price_Book__c]                  NVARCHAR (18)   NULL,
    [FX5__Status__c]                      NVARCHAR (18)   NULL,
    [FX5__Tracking_Number__c]             NVARCHAR (150)  NULL,
    [FX5__Total_Credits__c]               DECIMAL (18, 2) NULL,
    [FX5__Total_Invoice__c]               DECIMAL (18, 2) NULL,
    [FX5__Total_Payments__c]              DECIMAL (18, 2) NULL,
    [FX5__SyncID__c]                      NVARCHAR (150)  NULL,
    [Balance__c]                          DECIMAL (18, 2) NULL,
    [Credit_Revision_Number__c]           DECIMAL (18)    NULL,
    [Credit_Total__c]                     DECIMAL (18, 2) NULL,
    [Customer_Number__c]                  NVARCHAR (40)   NULL,
    [Draft_Date__c]                       DATETIME2 (0)   NULL,
    [InvoiceStatus__c]                    NVARCHAR (765)  NULL,
    [Invoice_Number__c]                   NVARCHAR (765)  NULL,
    [Invoice_Revision__c]                 DECIMAL (18)    NULL,
    [Invoice_Total__c]                    DECIMAL (18, 2) NULL,
    [OfficeNames__c]                      NVARCHAR (765)  NULL,
    [Tax_Error_Details__c]                NVARCHAR (765)  NULL,
    [Credit_Taxes__c]                     DECIMAL (18, 2) NULL,
    [Gross_Credits__c]                    DECIMAL (18, 2) NULL,
    [Sales_Tax__c]                        DECIMAL (18, 2) NULL,
    [AFE_Requirements__c]                 NVARCHAR (150)  NULL,
    [Approver_Requirements__c]            NVARCHAR (150)  NULL,
    [Barcode64__c]                        NVARCHAR (MAX)  NULL,
    [Barcode__c]                          NVARCHAR (3900) NULL,
    [Bill_To_Site_Requirements__c]        NVARCHAR (240)  NULL,
    [Conditional_Data__c]                 NVARCHAR (3900) NULL,
    [Contract_Requirements__c]            NVARCHAR (150)  NULL,
    [Converted_from_Draft_to_Invoice__c]  BIT             NULL,
    [Cost_Center_Requirements__c]         NVARCHAR (150)  NULL,
    [EDI_Validation_count_on_INV_Item__c] DECIMAL (18)    NULL,
    [Feature_Code_Requirements__c]        NVARCHAR (150)  NULL,
    [General_Ledger_ID_Requirements__c]   NVARCHAR (150)  NULL,
    [Gross_Total__c]                      DECIMAL (18, 2) NULL,
    [Marketplace_Name__c]                 NVARCHAR (150)  NULL,
    [Marketplace__c]                      NVARCHAR (150)  NULL,
    [Network_Activity_Requirements__c]    NVARCHAR (150)  NULL,
    [Other_EDI_Info_Requirements__c]      NVARCHAR (300)  NULL,
    [PO_Requirements__c]                  NVARCHAR (150)  NULL,
    [Plant_Code_Requirements__c]          NVARCHAR (150)  NULL,
    [Purchasing_Group_Requirements__c]    NVARCHAR (150)  NULL,
    [Record_Type__c]                      NVARCHAR (40)   NULL,
    [Report_Total__c]                     DECIMAL (18, 2) NULL,
    [Requestor_Requirements__c]           NVARCHAR (150)  NULL,
    [Required_Data__c]                    NVARCHAR (3900) NULL,
    [Routing_Code_Requirements__c]        NVARCHAR (150)  NULL,
    [UserNick__c]                         NVARCHAR (3900) NULL,
    [WBS_Element_Requirements__c]         NVARCHAR (150)  NULL,
    [Work_Order_Requirements__c]          NVARCHAR (150)  NULL,
    [Gross_Sales__c]                      DECIMAL (18, 2) NULL,
    [Count_of_Invoices__c]                DECIMAL (18)    NULL,
    [Bill_To__c]                          NVARCHAR (18)   NULL,
    [Invoice_Status_Validation_Check__c]  BIT             NULL,
    [Ticket_Report__c]                    NVARCHAR (18)   NULL,
    [ShowErrorCustReport__c]              BIT             NULL,
    [ShowErrorReport__c]                  BIT             NULL,
    [AltSync__c]                          BIT             NULL,
    [WES_Draft_Invoice__c]                BIT             NULL,
    [WES_Invoice__c]                      BIT             NULL,
    [Inserted]                            DATETIME2 (7)   NULL,
    [Updated]                             DATETIME2 (7)   NULL,
    [Extracted]                           INT             NULL
);
GO

ALTER TABLE [dbo].[Salesforce_Invoice]
    ADD CONSTRAINT [PK_Salesforce_Invoice] PRIMARY KEY CLUSTERED ([Id] ASC);
GO

