CREATE TABLE [dbo].[WEX_FUELCARD_TRANSACTIONS] (
    [F01_RecordType]            NVARCHAR (2)    NULL,
    [F02_SequenceNum]           INT             NULL,
    [F03_FleetAccountName]      NVARCHAR (30)   NULL,
    [F04_FleetAccountNumber]    NVARCHAR (20)   NULL,
    [F05_CustomerAccountNumber] NVARCHAR (30)   NULL,
    [F06_TransactionDate]       NVARCHAR (8)    NULL,
    [F07_TransactionTime]       NVARCHAR (6)    NULL,
    [F08_PostingDate]           NVARCHAR (8)    NULL,
    [F09_PrevPostingDate]       NVARCHAR (8)    NULL,
    [F10a_ReallocInd]           NVARCHAR (3)    NULL,
    [F10b_CardType]             NVARCHAR (7)    NULL,
    [F11_CCN]                   NVARCHAR (18)   NULL,
    [F12_WEXVehicleNumber]      INT             NULL,
    [F13_CardSuffix]            INT             NULL,
    [F14_PurchaseDevDept]       NVARCHAR (20)   NULL,
    [F15_OptEmbossingField]     NVARCHAR (20)   NULL,
    [F16_CompanyVehicleNumber]  NVARCHAR (17)   NULL,
    [F17_VehicleDesc]           NVARCHAR (17)   NULL,
    [F18_LicensePlateNum]       NVARCHAR (10)   NULL,
    [F19_LicensePlateState]     NVARCHAR (2)    NULL,
    [F20_VehicleIdNum]          NVARCHAR (17)   NULL,
    [F21a_TicketNumber]         NVARCHAR (12)   NULL,
    [F21b_TankCapacity]         INT             NULL,
    [F22_DriverLastName]        NVARCHAR (30)   NULL,
    [F23_DriverFirstName]       NVARCHAR (30)   NULL,
    [F24_DriverMiddleName]      NVARCHAR (20)   NULL,
    [F25_EmployeeID]            NVARCHAR (15)   NULL,
    [F29_DriverPromptDept]      NVARCHAR (20)   NULL,
    [F30_PromptID]              INT             NULL,
    [F31a_WEXTransID]           NVARCHAR (16)   NULL,
    [F31b_SequenceNumber]       NVARCHAR (4)    NULL,
    [F32_BrandName]             NVARCHAR (12)   NULL,
    [F33_SiteName]              NVARCHAR (20)   NULL,
    [F34_SiteAddress]           NVARCHAR (20)   NULL,
    [F35_SiteCity]              NVARCHAR (20)   NULL,
    [F36_SiteState]             NVARCHAR (2)    NULL,
    [F37_SitePostalCode]        NVARCHAR (9)    NULL,
    [F38_CountryOfOrigin]       NVARCHAR (3)    NULL,
    [F39_TypeOfCurrency]        NVARCHAR (3)    NULL,
    [F40_SitePhone]             NVARCHAR (10)   NULL,
    [F41_SiteTIN]               NVARCHAR (10)   NULL,
    [F42_WEXSiteID]             NVARCHAR (8)    NULL,
    [F43_SiteTransType]         NVARCHAR (1)    NULL,
    [F44_WEXTransCode]          INT             NULL,
    [F45_NetworkTranType]       NVARCHAR (2)    NULL,
    [F46_CurrentOdometer]       DECIMAL (7)     NULL,
    [F47_AdjCurrentOdometer]    DECIMAL (7)     NULL,
    [F48_PrevOdometer]          DECIMAL (7)     NULL,
    [F49_AdjPrevOdometer]       DECIMAL (7)     NULL,
    [F50_AdjOdometerFlag]       NVARCHAR (1)    NULL,
    [F51_AdjPrevOdometerFlag]   NVARCHAR (1)    NULL,
    [F52_NACSCode]              NVARCHAR (4)    NULL,
    [F53_ProductName]           NVARCHAR (8)    NULL,
    [F54_ProductDesc]           NVARCHAR (30)   NULL,
    [F55_UOM]                   NVARCHAR (4)    NULL,
    [F56_UnitCost]              DECIMAL (13, 3) NULL,
    [F57_ContractPricing]       DECIMAL (11, 3) NULL,
    [F58_QuantityPurchased]     DECIMAL (11, 3) NULL,
    [F59_GrossDollars]          DECIMAL (11, 2) NULL,
    [F60_DistanceDriven]        DECIMAL (13)    NULL,
    [F61_DistancePerUnit]       DECIMAL (13, 3) NULL,
    [F62_CostPerDistance]       DECIMAL (13, 2) NULL,
    [F64_DiscountFlag]          NVARCHAR (1)    NULL,
    [F65_DiscountAmount]        DECIMAL (9, 2)  NULL,
    [F67_FuelTaxAmount]         DECIMAL (9, 2)  NULL,
    [F68_BilledFlag]            NVARCHAR (1)    NULL,
    [F69_NetDollars]            NVARCHAR (11)   NULL,
    [F70_WEXAuthCode]           NVARCHAR (6)    NULL,
    [F71_MultiTranFlag]         NVARCHAR (4)    NULL,
    [F81_UDNAME_01]             NVARCHAR (30)   NULL,
    [F82_UDNAME_02]             NVARCHAR (30)   NULL,
    [F83_UDNAME_03]             NVARCHAR (30)   NULL,
    [F84_UDNAME_04]             NVARCHAR (30)   NULL,
    [F85_UDNAME_05]             NVARCHAR (30)   NULL,
    [F86_UDNAME_06]             NVARCHAR (30)   NULL,
    [F87_UDNAME_07]             NVARCHAR (30)   NULL,
    [F88_UDNAME_08]             NVARCHAR (30)   NULL,
    [F89_UDNAME_09]             NVARCHAR (30)   NULL,
    [F90_UDNAME_10]             NVARCHAR (30)   NULL,
    [F91_UDNAME_11]             NVARCHAR (30)   NULL,
    [F92_UDNAME_12]             NVARCHAR (30)   NULL,
    [F93_UDNAME_13]             NVARCHAR (30)   NULL,
    [F94_UDNAME_14]             NVARCHAR (30)   NULL,
    [F95_UDVAL_01]              NVARCHAR (50)   NULL,
    [F96_UDVAL_02]              NVARCHAR (50)   NULL,
    [F97_UDVAL_03]              NVARCHAR (50)   NULL,
    [F98_UDVAL_04]              NVARCHAR (50)   NULL,
    [F99_UDVAL_05]              NVARCHAR (50)   NULL,
    [F100_UDVAL_06]             NVARCHAR (50)   NULL,
    [F101_UDVAL_07]             NVARCHAR (50)   NULL,
    [F102_UDVAL_08]             NVARCHAR (50)   NULL,
    [F103_UDVAL_09]             NVARCHAR (50)   NULL,
    [F104_UDVAL_10]             NVARCHAR (50)   NULL,
    [F105_UDVAL_11]             NVARCHAR (50)   NULL,
    [F106_UDVAL_12]             NVARCHAR (50)   NULL,
    [F107_UDVAL_13]             NVARCHAR (50)   NULL,
    [F108_UDVAL_14]             NVARCHAR (50)   NULL,
    [CREATED_DATE]              DATETIME2 (7)   NULL
);
GO

